### ISSUE TITLE
[SOLVED]  After entering ID crash [Mistake / Bug?]

### ISSUE THREAD

**Issue by iiAlphaWolf01** [Splamy/TS3AudioBot#100]
Hello i was trying to setup this bot i finally found out how to build it xD. but now when i open the .exe it asks for my ip so i enter that... then it asks for an server ID thingy so for me its 6 or 67 http://prntscr.com/g0xomq i tried both but i keep getting this error message: And also the permissions its asking for is on: http://prntscr.com/g0xtod

```
[13:18:38]   Info: [============ TS3AudioBot started =============]
[13:18:38]   Info: [=== Date:           donderdag 27 juli 2017 ===]
[13:18:38]   Info: [=== Time:                         13:18:38 ===]
[13:18:38]   Info: [==============================================]
[13:18:38]   Info: [============ Initializing Commands ===========]
[13:18:38]   Info: [============ Initializing Modules ============]
[13:18:38]   Info: [=========== Initializing Factories ===========]
[13:18:38]   Info: [=========== Registering callbacks ============]
[13:18:38]   Info: [================= Finalizing =================]
[13:18:38]   Info: [============== Connected & Done ==============]
[13:18:38]  Error: Critical program failure!. Exception:
MSG: permissions_client_insufficient: the command failed to execute: insufficient client permissions (missing permission:b_client_info_view)
TYPE:Ts3CommandException
STACK:   at TS3Client.WaitBlock.WaitForMessage[T]() in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\WaitBlock.cs:line 48
   at TS3Client.Full.Ts3FullClient.SendCommand[T](Ts3Command com) in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\Full\Ts3FullClient.cs:line 300
   at TS3Client.Ts3BaseFunctions.Send[T](String command, List`1 parameter) in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\Ts3BaseClient.cs:line 54
   at TS3Client.Ts3BaseFunctions.ClientInfo(UInt16 clientId) in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\Ts3BaseClient.cs:line 131
   at TS3AudioBot.Ts3Full.GetSelf() in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3AudioBot\Ts3Full.cs:line 203
   at TS3AudioBot.TeamspeakControl.OnConnected(Object sender, EventArgs e) in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3AudioBot\TeamspeakControl.cs:line 94
   at TS3Client.Full.Ts3FullClient.ProcessInitServer(InitServer initServer) in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\Full\Ts3FullClient.cs:line 285
   at TS3Client.Full.Ts3FullClient.InvokeEvent(LazyNotification lazyNotification) in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\Full\Ts3FullClient.cs:line 184
   at TS3Client.ExtraThreadEventDispatcher.DispatchLoop() in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\EventDispatcher.cs:line 113
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Error call Stack:
Void <Main>b__0(System.Object, System.UnhandledExceptionEventArgs)@0
System.Collections.Generic.IEnumerable`1[T] WaitForMessage[T]()@0
System.Collections.Generic.IEnumerable`1[T] SendCommand[T](TS3Client.Commands.Ts3Command)@0
System.Collections.Generic.IEnumerable`1[T] Send[T](System.String, System.Collections.Generic.List`1[TS3Client.Commands.ICommandPart])@0
TS3Client.Messages.ClientInfo ClientInfo(UInt16)@0
TS3Client.Messages.ClientData GetSelf()@0
Void OnConnected(System.Object, System.EventArgs)@0
Void ProcessInitServer(TS3Client.Messages.InitServer)@0
Void InvokeEvent(TS3Client.LazyNotification)@0
Void DispatchLoop()@0
Void ThreadStart_Context(System.Object)@0
Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)@0
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)@0
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)@0
Void ThreadStart()@0 T:TS3Query MessageLoop
[13:18:38]   Info: Exiting...
[13:18:38]   Info: Closing Mediaplayer...
[13:18:38]  Debug: AF stop old
[13:18:38]Warning: Internal error (me==null)
[13:18:38]   Info: Closing QueryConnection...
[13:18:38]  Debug: Bot disconnected. Reason: LeftServer
[13:18:38]   Info: Closing QueryConnection...

Unhandled Exception: TS3Client.Ts3CommandException: permissions_client_insufficient: the command failed to execute: insufficient client permissions (missing permission:b_client_info_view)
   at TS3Client.WaitBlock.WaitForMessage[T]() in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\WaitBlock.cs:line 48
   at TS3Client.Full.Ts3FullClient.SendCommand[T](Ts3Command com) in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\Full\Ts3FullClient.cs:line 300
   at TS3Client.Ts3BaseFunctions.Send[T](String command, List`1 parameter) in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\Ts3BaseClient.cs:line 54
   at TS3Client.Ts3BaseFunctions.ClientInfo(UInt16 clientId) in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\Ts3BaseClient.cs:line 131
   at TS3AudioBot.Ts3Full.GetSelf() in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3AudioBot\Ts3Full.cs:line 203
   at TS3AudioBot.TeamspeakControl.OnConnected(Object sender, EventArgs e) in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3AudioBot\TeamspeakControl.cs:line 94
   at TS3Client.Full.Ts3FullClient.ProcessInitServer(InitServer initServer) in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\Full\Ts3FullClient.cs:line 285
   at TS3Client.Full.Ts3FullClient.InvokeEvent(LazyNotification lazyNotification) in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\Full\Ts3FullClient.cs:line 184
   at TS3Client.ExtraThreadEventDispatcher.DispatchLoop() in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\EventDispatcher.cs:line 113
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

Idk why this is happening i gave it enough permissions just as you said in the setup tutorial.

**Comment by Splamy** [comment]
I guess you could not use the `!bot setup` command yet since the bot immediatly crashes. Can you try to add the bot to the group in the server group dialogue like that: https://i.imgur.com/5MtK32r.png

(Fo the next patch I will try to make a change which maybe helps to start more reliably)

**Comment by iiAlphaWolf01** [comment]
Hello thanks for respond @Splamy but i cant do that because when ever i try to connect the bot it isnt even for 1ms in the server so i cant know or see his ID nor him self. http://prntscr.com/g14g27
Maybe i am doing something wrong tomorrow ill try to give everything another try and write everything down maybe you see what iam doing wrong. http://prntscr.com/g14gt9

**Comment by Splamy** [comment]
Look at the screenshot again, you can search by username

**Comment by iiAlphaWolf01** [comment]
I'm sorry am i just blind or... http://prntscr.com/g14lpf Ofcourse i cant show the personal information of ht users on my server.  but the bot (AudioBot) didnt even made a client on the server its not in the All client list.

**Comment by Splamy** [comment]
Can you try to search for `AudioBot` in the top field. If he connected at even just for a few milliseconds there should be an entry

**Comment by iiAlphaWolf01** [comment]
Yes you were right i found it, but i still got a error message, i tried deleting config and re awnsering the questions ip and id ect.
`[22:00:39]   Info: [============ TS3AudioBot started =============]
[22:00:39]   Info: [=== Date:           donderdag 27 juli 2017 ===]
[22:00:39]   Info: [=== Time:                         22:00:39 ===]
[22:00:39]   Info: [==============================================]
[22:00:39]   Info: [============ Initializing Commands ===========]
[22:00:39]   Info: [============ Initializing Modules ============]
[22:00:39]   Info: [=========== Initializing Factories ===========]
[22:00:39]   Info: [=========== Registering callbacks ============]
[22:00:39]   Info: [================= Finalizing =================]
[22:00:39]   Info: [============== Connected & Done ==============]
[22:00:39]  Error: Critical program failure!. Exception:
MSG: permissions_client_insufficient: the command failed to execute: insufficient client permissions (missing permission:b_client_info_view)
TYPE:Ts3CommandException
STACK:   at TS3Client.WaitBlock.WaitForMessage[T]() in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\WaitBlock.cs:line 48
   at TS3Client.Full.Ts3FullClient.SendCommand[T](Ts3Command com) in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\Full\Ts3FullClient.cs:line 300
   at TS3Client.Ts3BaseFunctions.Send[T](String command, List`1 parameter) in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\Ts3BaseClient.cs:line 54
   at TS3Client.Ts3BaseFunctions.ClientInfo(UInt16 clientId) in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\Ts3BaseClient.cs:line 131
   at TS3AudioBot.Ts3Full.GetSelf() in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3AudioBot\Ts3Full.cs:line 203
   at TS3AudioBot.TeamspeakControl.OnConnected(Object sender, EventArgs e) in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3AudioBot\TeamspeakControl.cs:line 94
   at TS3Client.Full.Ts3FullClient.ProcessInitServer(InitServer initServer) in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\Full\Ts3FullClient.cs:line 285
   at TS3Client.Full.Ts3FullClient.InvokeEvent(LazyNotification lazyNotification) in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\Full\Ts3FullClient.cs:line 184
   at TS3Client.ExtraThreadEventDispatcher.DispatchLoop() in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\EventDispatcher.cs:line 113
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Error call Stack:
Void <Main>b__0(System.Object, System.UnhandledExceptionEventArgs)@0
System.Collections.Generic.IEnumerable`1[T] WaitForMessage[T]()@0
System.Collections.Generic.IEnumerable`1[T] SendCommand[T](TS3Client.Commands.Ts3Command)@0
System.Collections.Generic.IEnumerable`1[T] Send[T](System.String, System.Collections.Generic.List`1[TS3Client.Commands.ICommandPart])@0
TS3Client.Messages.ClientInfo ClientInfo(UInt16)@0
TS3Client.Messages.ClientData GetSelf()@0
Void OnConnected(System.Object, System.EventArgs)@0
Void ProcessInitServer(TS3Client.Messages.InitServer)@0
Void InvokeEvent(TS3Client.LazyNotification)@0
Void DispatchLoop()@0
Void ThreadStart_Context(System.Object)@0
Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)@0
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)@0
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)@0
Void ThreadStart()@0 T:TS3Query MessageLoop
[22:00:39]   Info: Exiting...
[22:00:39]   Info: Closing Mediaplayer...
[22:00:39]  Debug: AF stop old
[22:00:39]Warning: Internal error (me==null)
[22:00:39]   Info: Closing QueryConnection...
[22:00:39]  Debug: Bot disconnected. Reason: LeftServer
[22:00:39]   Info: Closing QueryConnection...

Unhandled Exception: TS3Client.Ts3CommandException: permissions_client_insufficient: the command failed to execute: insufficient client permissions (missing permission:b_client_info_view)
   at TS3Client.WaitBlock.WaitForMessage[T]() in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\WaitBlock.cs:line 48
   at TS3Client.Full.Ts3FullClient.SendCommand[T](Ts3Command com) in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\Full\Ts3FullClient.cs:line 300
   at TS3Client.Ts3BaseFunctions.Send[T](String command, List`1 parameter) in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\Ts3BaseClient.cs:line 54
   at TS3Client.Ts3BaseFunctions.ClientInfo(UInt16 clientId) in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\Ts3BaseClient.cs:line 131
   at TS3AudioBot.Ts3Full.GetSelf() in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3AudioBot\Ts3Full.cs:line 203
   at TS3AudioBot.TeamspeakControl.OnConnected(Object sender, EventArgs e) in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3AudioBot\TeamspeakControl.cs:line 94
   at TS3Client.Full.Ts3FullClient.ProcessInitServer(InitServer initServer) in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\Full\Ts3FullClient.cs:line 285
   at TS3Client.Full.Ts3FullClient.InvokeEvent(LazyNotification lazyNotification) in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\Full\Ts3FullClient.cs:line 184
   at TS3Client.ExtraThreadEventDispatcher.DispatchLoop() in C:\Users\stoop\Desktop\TS3AudioBot-master\TS3Client\EventDispatcher.cs:line 113
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()`

around the first/second line of error it says something about the permission called b_client_info_view
in the setup tutorial you said put it high enough i did 999. is there any problem with that?

**Comment by Splamy** [comment]
Have you added the unique id of the audiobot to the AudioBotAdmin Group ?

**Comment by iiAlphaWolf01** [comment]
Yes i did

**Comment by Splamy** [comment]
did you do it before you deleted to config, because if you deleted it you will have to do it again since the bot will have to generate a new id

**Comment by iiAlphaWolf01** [comment]
Dont worry fixed it. How?

When ever i restarted my server while the bot was running aswell somehow it duped. i added all AudioBots now looks funny but i haave to find out the correct one now. http://prntscr.com/g14u0a
Thanks for helping thoug. Is there a solution page where i can post this? http://prntscr.com/g14uzu

**Comment by Splamy** [comment]
When you drag and drop a client name from the chat log into the write field you will get a generated string
`[URL=client://3/b+P0CqXms5I0C+A66HZ4Sbu/PNw=~AudioBot]AudioBot[/URL]`, this `3/b+P0CqXms5I0C+A66HZ4Sbu/PNw` is the id. This way you can find out the uid of the currently connected bot

**Comment by davlast** [comment]
hi, easy fix i used was just give Guest account b_client_info_view and then setup the bot and then removed the b_client_info_view setting

**Comment by iiAlphaWolf01** [comment]
Oh yeah didnt knew that! thanks! lol so the server thought his id changed but it still was the first one weird but its solved.

**Comment by Splamy** [comment]
Haha, thats clever. I hope with the next patch that this inconvenience will be fixed, I'm still trying stuff

**Comment by iiAlphaWolf01** [comment]
Do you have to create rights.toml your self? because it isnt made by it self for me

**Comment by Splamy** [comment]
huh thats strange, usually when not rights.toml is found it should auto create it.
Can you make sure the bot has write permission in that folder?
If nothing else helps you can copy out the template from `TS3AudioBot/Rights/DefaultRights.toml`

**Comment by iiAlphaWolf01** [comment]
weird ill copy it. i ran it as admin so it really should have the rights to write but still nothing called rights.toml

**Comment by iiAlphaWolf01** [comment]
ehm rights.toml isnt in the rightfolder either maybe thats why it didnt make it? http://prntscr.com/g154a5

**Comment by Splamy** [comment]
Huh thats really strange, have you deleted it by accident?
Anyway you can download it fresh from the repo here: https://github.com/Splamy/TS3AudioBot/tree/master/TS3AudioBot/Rights

**Comment by iiAlphaWolf01** [comment]
lmao never been in that folder its not in bin i should have been on drugs and deleted it idk xD

**Comment by iiAlphaWolf01** [comment]
Would you mind if i make ainstallation video about this when mine works? maybe better for new people

**Comment by Splamy** [comment]
Uh, apart from that little problem I think the current setup tutorial is pretty straight forward. I will rather try to make te ux better by fixing common problems and automate more stuff
