### ISSUE TITLE
Couple of Suggestions.

### ISSUE THREAD

**Issue by MaDmaxwell311** [Splamy/TS3AudioBot#129]
Hey, I found this a few days ago and I really like it. However, I do have some suggestions. 

1. Either add a command to list songs in a playlist or add this function to an existing command. 
2. Add the ability to change the default folder for songs. What I mean is if I set a folder to "default" then when I play a song all I have to is `!play song.mp3` rather than `!play ./folder/song.mp3` This way I do not have to clutter up the folder with the stuff for the bot with mp3's and wav's.
3. Add a "playlist" functionality. This would build on top of suggestion 2.  Think of it like this, have a "master" folder that contains all of the random songs but in the "master" folder you can have subfolders or "playlists" where you can sort the music out. [Picture example](https://i.imgur.com/948kcEg.png)
4. Also, add the ability to just do `!play` while in the folder and the bot just start playing songs. Ideally, this would be used for playlists where you do something like `!play ./sadSongs/` and the bot will then add the songs in the folder to the queue.

**Comment by Splamy** [comment]
1. There is a command for that, `!list show (<offset>)` or `!list show <saved list> (<offset>)` should do that. See [here](https://github.com/Splamy/TS3AudioBot/wiki/Playlists) for a little playlist overview

**Comment by MaDmaxwell311** [comment]
Thanks. Also, I noticed this little quirk with the `!list` command https://i.imgur.com/zrQ6pGA.png 
Another thing to note is your sidebar for your wiki does not link to all of the actual wiki pages, [picture example](https://i.imgur.com/QrvT2Im.png)

**Comment by Splamy** [comment]
- Image one is intended behaviour, we have a fuzzy matching algorithm, and in your case the empty string matches the closest to those two commands
- Yes plugins dont have a sidebar entry since it is not a full article, i'll see if I can fit it somewhere nice
The last list is indeed strange, can you tell me what you have in your playlist folder?

**Comment by MaDmaxwell311** [comment]
Here is my [playlist folder.](https://i.imgur.com/XSXtS1Y.png) Note: the subfolders do have music in them.

Also, you may you to have a page or command or something detailing what a/v formats the bot can play.

**Comment by Splamy** [comment]
an exhaustive list of everything that is supported (see X in decoding column): https://www.ffmpeg.org/general.html#File-Formats

**Comment by MaDmaxwell311** [comment]
Oh, that would explain some things. Sorry. 

So, if I am understanding this correctly, then what I should do is 

1. `!list get <list name/link>`
2. `!list save` - If I want to save it.
3. `!list play` 

Correct?

**Comment by Splamy** [comment]
yup

**Comment by MaDmaxwell311** [comment]
I really feel stupid, and I apologize for wasting your time, but I am still having issues. I did what you said, and I got [this in response. ](https://gist.github.com/MaDmaxwell311/63d0972dd552da648c606e0ec92781ec) There is both client and bot log.

**Comment by MaDmaxwell311** [comment]
Update: I managed to save the list and now when I go to play said list I get this in the console. `[17:45:24]  Debug: MB Got message from Maxwell: !list list
[17:45:24]  Debug: SM User Maxwell created session with the bot
[17:45:33]  Debug: MB Got message from Maxwell: !list load PLzedpM8OW4ZG4NN0RPT16AjjP7cV7OewP
[17:45:36]  Debug: MB Got message from Maxwell: !list play
[17:45:36]Warning: TH Web error: [403] Forbidden
[17:45:36]  Debug: YT Ruined!
[17:45:36]  Error: MB Unexpected command error: MSG: Illegal characters in path.
TYPE:ArgumentException
STACK:   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at TS3AudioBot.ResourceFactories.YoutubeDlHelper.FindYoutubeDl(String id) in C:\Users\richa\Source\Repos\TS3AudioBot\TS3AudioBot\ResourceFactories\YoutubeDlHelper.cs:line 43
   at TS3AudioBot.ResourceFactories.YoutubeDlHelper.FindAndRunYoutubeDl(String id) in C:\Users\richa\Source\Repos\TS3AudioBot\TS3AudioBot\ResourceFactories\YoutubeDlHelper.cs:line 27
   at TS3AudioBot.ResourceFactories.YoutubeFactory.YoutubeDlWrapped(AudioResource resource) in C:\Users\richa\Source\Repos\TS3AudioBot\TS3AudioBot\ResourceFactories\YoutubeFactory.cs:line 314
   at TS3AudioBot.ResourceFactories.YoutubeFactory.GetResourceById(AudioResource resource) in C:\Users\richa\Source\Repos\TS3AudioBot\TS3AudioBot\ResourceFactories\YoutubeFactory.cs:line 146
   at TS3AudioBot.ResourceFactories.ResourceFactoryManager.Load(AudioResource resource) in C:\Users\richa\Source\Repos\TS3AudioBot\TS3AudioBot\ResourceFactories\ResourceFactoryManager.cs:line 80
   at TS3AudioBot.PlayManager.Play(InvokerData invoker, AudioResource ar, MetaData meta) in C:\Users\richa\Source\Repos\TS3AudioBot\TS3AudioBot\PlayManager.cs:line 64
   at TS3AudioBot.PlayManager.Play(InvokerData invoker, PlaylistItem item) in C:\Users\richa\Source\Repos\TS3AudioBot\TS3AudioBot\PlayManager.cs:line 116
   at TS3AudioBot.MainBot.CommandListPlay(ExecutionInformation info, Nullable`1 index) in C:\Users\richa\Source\Repos\TS3AudioBot\TS3AudioBot\MainBot.cs:line 985
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at TS3AudioBot.CommandSystem.FunctionCommand.ExecuteFunction(Object[] parameters) in C:\Users\richa\Source\Repos\TS3AudioBot\TS3AudioBot\CommandSystem\Commands\FunctionCommand.cs:line 75
   at TS3AudioBot.CommandSystem.FunctionCommand.Execute(ExecutionInformation info, IEnumerable`1 arguments, IEnumerable`1 returnTypes) in C:\Users\richa\Source\Repos\TS3AudioBot\TS3AudioBot\CommandSystem\Commands\FunctionCommand.cs:line 187
   at TS3AudioBot.CommandSystem.CommandGroup.Execute(ExecutionInformation info, IEnumerable`1 arguments, IEnumerable`1 returnTypes) in C:\Users\richa\Source\Repos\TS3AudioBot\TS3AudioBot\CommandSystem\Commands\CommandGroup.cs:line 48
   at TS3AudioBot.CommandSystem.CommandGroup.Execute(ExecutionInformation info, IEnumerable`1 arguments, IEnumerable`1 returnTypes) in C:\Users\richa\Source\Repos\TS3AudioBot\TS3AudioBot\CommandSystem\Commands\CommandGroup.cs:line 48
   at TS3AudioBot.MainBot.TextCallback(Object sender, TextMessage textMessage) in C:\Users\richa\Source\Repos\TS3AudioBot\TS3AudioBot\MainBot.cs:line 255

Error call Stack:
Void TextCallback(System.Object, TS3Client.Messages.TextMessage)@0
Void ExtendedTextMessage(System.Object, System.Collections.Generic.IEnumerable`1[TS3Client.Messages.TextMessage])@0
Void InvokeEvent(TS3Client.LazyNotification)@0
Void DispatchLoop()@0
Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)@0
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)@0
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)@0
Void ThreadStart()@0 T:TS3Query MessageLoop`

**Comment by Splamy** [comment]
Can you give me your full path to the playlist folder? (you can cut our private names etc.) i just want to see if there are some strange characters

**Comment by MaDmaxwell311** [comment]
Playlists: `C:/Users/USERNAME/Desktop/Release/Playlists/`
The location of the bot: `C:/Users/USERNAME/Desktop/Release`
Also, I moved the music file out of the Playlists folder and into a separate one.

**Comment by Splamy** [comment]
And your `YoutubeFactory::youtubedlpath` setting

**Comment by Splamy** [comment]
Oh and which bot version do you use? `TS3Audiobot.exe -V`

**Comment by MaDmaxwell311** [comment]
YouTube-DL: `C:/Users/USERNAME/bin/`
Bot version: `Version: 0.6.1
Branch: master
CommitHash: 9c9d5b376c933c9a3abadec71927c9bd9a1388d3`

**Comment by MaDmaxwell311** [comment]
Okay, I fixed it! I had the path to the youtube-dl.exe in quotes in the configTS3AudioBot.cfg file.

**Comment by Splamy** [comment]
oh, ok

**Comment by MaDmaxwell311** [comment]
And With that, I think that solves everything.  Shall I close the thread?

**Comment by Splamy** [comment]
Leave it open for 2. and 4., i will just remove the bug tag
