### ISSUE TITLE
Crash when antiflood-locked while connecting

### ISSUE THREAD

**Issue by Bluscream** [Splamy/TS3AudioBot#150]
```csharp
[00:03:39]   Info: [============ TS3AudioBot started =============]
[00:03:39]   Info: [=== Date/Time: Monday, November 6, 2017 12:03:39 AM
[00:03:39]   Info: [=== Version: 0.8.0-unstable.29/develop/aca4dd64
[00:03:39]   Info: [==============================================]
[00:03:39]   Info: [============ Initializing Commands ===========]
[00:03:39]   Info: [============ Initializing Modules ============]
[00:03:40]   Info: Using opus version: libopus 1.2.1-fixed (x64)
[00:03:40]   Info: [=========== Initializing Factories ===========]
[00:03:40]   Info: [=========== Registering callbacks ============]
[00:03:40]   Info: [================= Finalizing =================]
[00:03:40]  Debug: AutoChannelCommander: Plugin AutoChannelCommander v1 by Bluscream <admin@timo.de.vc> loaded.
[00:03:40]  Debug: ClientQuery: Plugin ClientQuery v1 by Bluscream <admin@timo.de.vc> loaded.
[00:03:40]   Info: ClientQuery: Telnet Server listening on 0.0.0.0:25639
[00:03:40]  Debug: MetaData: Plugin MetaData v1 by Bluscream <admin@timo.de.vc> loaded.
[00:03:40]  Debug: NowPlaying: Plugin NowPlaying v1 by Bluscream <admin@timo.de.vc> loaded.
[00:03:40]  Debug: Tools: Plugin Tools v1337 by Bluscream <admin@timo.de.vc> loaded.
[00:03:40]Warning: App launched without elevated rights. Only localhost will be availbale as api server.
[00:03:42]   Info: [==================== Done ====================]
[00:03:43]  Error: Critical program failure!. Exception:
                   MSG: client_is_flooding: the command failed to execute: client is flooding
                   TYPE:Ts3CommandException
                   STACK:   at TS3Client.WaitBlock.WaitForMessage[T]() in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\WaitBlock.cs:line 49
                      at TS3Client.Full.Ts3FullClient.SendCommand[T](Ts3Command com) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Full\Ts3FullClient.cs:line 319
                      at TS3Client.Ts3BaseFunctions.Send[T](String command) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Ts3BaseClient.cs:line 71
                      at TS3Client.Ts3BaseFunctions.WhoAmI() in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Ts3BaseClient.cs:line 116
                      at TS3AudioBot.Ts3Full.GetSelf() in C:\Users\blusc\source\repos\TS3AudioBot\TS3AudioBot\Ts3Full.cs:line 216
                      at TS3AudioBot.TeamspeakControl.OnConnected(Object sender, EventArgs e) in C:\Users\blusc\source\repos\TS3AudioBot\TS3AudioBot\TeamspeakControl.cs:line 96
                      at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
                      at TS3Client.Full.Ts3FullClient.ProcessInitServer(InitServer initServer) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Full\Ts3FullClient.cs:line 288
                      at TS3Client.Full.Ts3FullClient.InvokeEvent(LazyNotification lazyNotification) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Full\Ts3FullClient.cs:line 181
                      at TS3Client.DoubleThreadEventDispatcher.DispatchLoop() in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\EventDispatcher.cs:line 180
                      at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
                      at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
                      at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
                      at System.Threading.ThreadHelper.ThreadStart()

Error call Stack:
Void <Main>b__0(System.Object, System.UnhandledExceptionEventArgs)@0
System.Collections.Generic.IEnumerable`1[T] WaitForMessage[T]()@0
System.Collections.Generic.IEnumerable`1[T] SendCommand[T](TS3Client.Commands.Ts3Command)@0
System.Collections.Generic.IEnumerable`1[T] Send[T](System.String)@0
TS3Client.Messages.WhoAmI WhoAmI()@0
TS3Client.Messages.ClientData GetSelf()@0
Void OnConnected(System.Object, System.EventArgs)@0
Void Invoke(System.Object, TEventArgs)@0
Void ProcessInitServer(TS3Client.Messages.InitServer)@0
Void InvokeEvent(TS3Client.LazyNotification)@0
Void DispatchLoop()@0
Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)@0
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)@0
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)@0
Void ThreadStart()@0 T:TS3 Dispatcher
[00:03:43]   Info: Exiting...
[00:03:43]  Debug: AutoChannelCommander: Plugin AutoChannelCommander unloaded.
[00:03:43]  Debug: ClientQuery: Plugin ClientQuery unloaded.
[00:03:43]  Debug: MetaData: Plugin MetaData unloaded.
[00:03:43]  Debug: NowPlaying: Plugin NowPlaying unloaded.
[00:03:43]  Debug: Tools: Plugin Tools unloaded.
[00:03:43]Warning: Internal error (me==null)
[00:03:43]Warning: Could not save avatar: client_is_flooding: the command failed to execute: client is flooding
[00:03:43]   Info: Closing QueryConnection...
[00:03:43]  Debug: Bot disconnected. Reason: LeftServer
[00:03:43]   Info: Closing QueryConnection...

Unhandled Exception: TS3Client.Ts3CommandException: client_is_flooding: the command failed to execute: client is flooding
   at TS3Client.WaitBlock.WaitForMessage[T]() in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\WaitBlock.cs:line 49
   at TS3Client.Full.Ts3FullClient.SendCommand[T](Ts3Command com) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Full\Ts3FullClient.cs:line 319
   at TS3Client.Ts3BaseFunctions.Send[T](String command) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Ts3BaseClient.cs:line 71
   at TS3Client.Ts3BaseFunctions.WhoAmI() in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Ts3BaseClient.cs:line 116
   at TS3AudioBot.Ts3Full.GetSelf() in C:\Users\blusc\source\repos\TS3AudioBot\TS3AudioBot\Ts3Full.cs:line 216
   at TS3AudioBot.TeamspeakControl.OnConnected(Object sender, EventArgs e) in C:\Users\blusc\source\repos\TS3AudioBot\TS3AudioBot\TeamspeakControl.cs:line 96
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at TS3Client.Full.Ts3FullClient.ProcessInitServer(InitServer initServer) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Full\Ts3FullClient.cs:line 288
   at TS3Client.Full.Ts3FullClient.InvokeEvent(LazyNotification lazyNotification) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Full\Ts3FullClient.cs:line 181
   at TS3Client.DoubleThreadEventDispatcher.DispatchLoop() in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\EventDispatcher.cs:line 180
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()


Press Enter or Esc to close console...
```

**Comment by Splamy** [comment]
latest dev branch fixes this
