### ISSUE TITLE
Value was either too large or too small for an Int64

### ISSUE THREAD

**Issue by Bluscream** [Splamy/TS3AudioBot#158]
```
[21:10:39]   Info: [============ TS3AudioBot started =============]
[21:10:39]   Info: [=== Date/Time: Friday, November 10, 2017 9:10:39 PM
[21:10:39]   Info: [=== Version: 0.8.0-unstable.40/develop/93ff2371
[21:10:39]   Info: [==============================================]
[21:10:39]   Info: [============ Initializing Modules ============]
[21:10:40]   Info: [=========== Initializing Factories ===========]
[21:10:40]   Info: [================= Finalizing =================]
[21:10:40]Warning: InitlializeAssembly failed, The file "AutoChannelCommander.dll" seems to be missing some dependecies (Method 'Initialize' in type 'AutoChannelCommander.AutoChannelCommander' from assembly 'AutoChannelCommander, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.)
[21:10:40]Warning: InitlializeAssembly failed, The file "AutoFollow.dll" seems to be missing some dependecies (Method 'Initialize' in type 'AutoFollow.AutoFollow' from assembly 'AutoFollow, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.)
[21:10:40]Warning: InitlializeAssembly failed, The file "ClientQuery.dll" seems to be missing some dependecies (Method 'Initialize' in type 'ClientQuery.ClientQuery' from assembly 'ClientQuery, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.)
[21:10:40]Warning: InitlializeAssembly failed, The file "MetaData.dll" seems to be missing some dependecies (Method 'Initialize' in type 'MetaData.MetaData' from assembly 'MetaData, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.)
[21:10:40]Warning: InitlializeAssembly failed, The file "NowPlaying.dll" seems to be missing some dependecies (Method 'Initialize' in type 'NowPlaying.NowPlaying' from assembly 'NowPlaying, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.)
[21:10:40]Warning: InitlializeAssembly failed, The file "PMRedirect.dll" seems to be missing some dependecies (Method 'Initialize' in type 'PMRedirect.PMRedirect' from assembly 'PMRedirect, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.)
[21:10:40]Warning: InitlializeAssembly failed, The file "RegistriertChannel.dll" seems to be missing some dependecies (Method 'Initialize' in type 'RegistriertChannel.RegistriertChannel' from assembly 'RegistriertChannel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.)
[21:10:40]Warning: InitlializeAssembly failed, The file "TestPlugin.dll" seems to be missing some dependecies (Method 'Initialize' in type 'TestPlugin.TestPlugin' from assembly 'TestPlugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.)
[21:10:40]Warning: InitlializeAssembly failed, The file "Tools.dll" seems to be missing some dependecies (Method 'Initialize' in type 'Tools.Tools' from assembly 'Tools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.)
[21:10:40]Warning: App launched without elevated rights. Only localhost will be availbale as api server.
[21:10:40]   Info: Bot connecting...
[21:10:40]   Info: Using opus version: libopus 1.2.1-fixed (x64)
[21:10:40]  Debug: Setting badges to: overwolf=1:badges=c9e97536-5a2d-4c8e-a135-af404587a472
[21:10:41]  Error: Critical program failure!. Exception:
                   MSG: Value was either too large or too small for an Int64.
                   TYPE:OverflowException
                   STACK:   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
                      at TS3Client.Commands.CommandDeserializer.DeserializeInt64(String v) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Commands\CommandDeserializer.cs:line 106
                      at TS3Client.Messages.ClientEnterView.SetField(String name, String value) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Messages\MessageTemplates.cs:line 495
                      at TS3Client.Commands.CommandDeserializer.FillQueryMessage(IQueryMessage qm, IEnumerable`1 kvpData) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Commands\CommandDeserializer.cs:line 78
                      at TS3Client.Commands.CommandDeserializer.GenerateSingleNotification(String lineDataPart, NotificationType ntfyType) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Commands\CommandDeserializer.cs:line 43
                      at TS3Client.Commands.CommandDeserializer.<>c__DisplayClass0_0.<GenerateNotification>b__0(String msg) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Commands\CommandDeserializer.cs:line 30
                      at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
                      at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext()
                      at TS3AudioBot.TeamspeakControl.ExtendedClientEnterView(Object sender, IEnumerable`1 eventArgs) in C:\Users\blusc\source\repos\TS3AudioBot\TS3AudioBot\TeamspeakControl.cs:line 42
                      at TS3Client.Full.Ts3FullClient.InvokeEvent(LazyNotification lazyNotification) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Full\Ts3FullClient.cs:line 160
                      at TS3Client.DoubleThreadEventDispatcher.DispatchLoop() in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\EventDispatcher.cs:line 180
                      at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
                      at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
                      at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
                      at System.Threading.ThreadHelper.ThreadStart()

Error call Stack:
Void <Main>b__0(System.Object, System.UnhandledExceptionEventArgs)@0
Int64 ParseInt64(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)@0
Int64 DeserializeInt64(System.String)@0
Void SetField(System.String, System.String)@0
Void FillQueryMessage(TS3Client.Messages.IQueryMessage, System.Collections.Generic.IEnumerable`1[System.Collections.Generic.KeyValuePair`2[System.String,System.String]])@0
TS3Client.Messages.INotification GenerateSingleNotification(System.String, TS3Client.NotificationType)@0
TS3Client.Messages.INotification <GenerateNotification>b__0(System.String)@0
Boolean MoveNext()@0
Boolean MoveNext()@0
Void ExtendedClientEnterView(System.Object, System.Collections.Generic.IEnumerable`1[TS3Client.Messages.ClientEnterView])@0
Void InvokeEvent(TS3Client.LazyNotification)@0
Void DispatchLoop()@0
Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)@0
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)@0
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)@0
Void ThreadStart()@0 T:TS3 Dispatcher
[21:10:41]   Info: TS3AudioBot shutting down.
[21:10:41]   Info: Bot disconnecting.
[21:10:41]Warning: permissions_client_insufficient: the command failed to execute: insufficient client permissions (missing permission:b_client_modify_own_description)
[21:10:41]Warning: Could not save avatar: permission_invalid_size: the command failed to execute: invalid size
[21:10:41]   Info: Closing QueryConnection...

Unhandled Exception: System.OverflowException: Value was either too large or too small for an Int64.
   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at TS3Client.Commands.CommandDeserializer.DeserializeInt64(String v) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Commands\CommandDeserializer.cs:line 106
   at TS3Client.Messages.ClientEnterView.SetField(String name, String value) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Messages\MessageTemplates.cs:line 495
   at TS3Client.Commands.CommandDeserializer.FillQueryMessage(IQueryMessage qm, IEnumerable`1 kvpData) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Commands\CommandDeserializer.cs:line 78
   at TS3Client.Commands.CommandDeserializer.GenerateSingleNotification(String lineDataPart, NotificationType ntfyType) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Commands\CommandDeserializer.cs:line 43
   at TS3Client.Commands.CommandDeserializer.<>c__DisplayClass0_0.<GenerateNotification>b__0(String msg) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Commands\CommandDeserializer.cs:line 30
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext()
   at TS3AudioBot.TeamspeakControl.ExtendedClientEnterView(Object sender, IEnumerable`1 eventArgs) in C:\Users\blusc\source\repos\TS3AudioBot\TS3AudioBot\TeamspeakControl.cs:line 42
   at TS3Client.Full.Ts3FullClient.InvokeEvent(LazyNotification lazyNotification) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Full\Ts3FullClient.cs:line 160
   at TS3Client.DoubleThreadEventDispatcher.DispatchLoop() in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\EventDispatcher.cs:line 180
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()


Press Enter or Esc to close console...
```

**Comment by Bluscream** [comment]
```
ountry=TRf^V
[O] Acking: 44
[I] Type: Command       Flags: [ X _ _ _ ]      Id: 45
  Data: E7 03 49 5F 69 6E 68 FE 00 02 C2 65 41 E3 31 19 56 E7 F2 7B A4 6A 51 AF 31 92 5F 62 61 64 67 65 73 3D 6F 01 25 77 6F 6C 66 3D 30 7C 51 AF 64 3D 33 34 66 5E 01 00 00 88 30 8E 12 58 6E 4B 6E 45 6C 6F 64 59 4D 61 65 4C 76 33 4E 73 4C 74 30 67 72 70 77 67 44 A0 F5 13 38 39 6D C0 D3 F1 BE 75 72 61 74 38 39 66 5E F4 96 A4 22 27 60 6F 75 30 72 96 33 07 60 56 E7 05 49 64 3D 35 66 5E 54 25 03 49 00 E6 5A 36 27 60 22 7B 81 40 61 32 40 7A FF 6E CC 00 00 80 74 5F 5D E7 80 E3 39 36 36 66 5E 30 8E 12 51 79 31 66 45 4B 57 57 34 32 76 72 42 2B 4F 64 33 68 45 37 6A 5C 2F 20 40 B7 83 5A 39 78 73 6B F0 60 12 4C 41 4E 53 45 4C 4F 54 66 5E 69 99 73 27 60 80 22 97 33 48 73 5D E7 64 E0 A3 FF 91 19 80 F5 C0 6C 66 3D 30
  ASCI: ?♥I_inh? ☻?eA?1↓V??{?jQ?1?_badges=o☺%wolf=0|Q?d=34f^☺  ?0?↕XnKnElodYMaeLv3NsLt0grpwgD??‼89m???urat89f^??"'`ou0r?3`V?♣Id=5f^T%♥I ?Z6'`"{?@a2@z?n?  ?t_]??966f^0?↕Qy1fEKWW42vrB+Od3hE7j\/ @??Z9xsk?`↕LANSELOTf^i?s'`?"?3Hs]?d???↓???lf=0
[O] Acking: 45
[I] Type: Command       Flags: [ _ _ _ _ ]      Id: 46
  Data: 6E 6F 74 69 66 79 63 68 61 6E 6E 65 6C 73 75 62 73 63 72 69 62 65 64 20 63 69 64 3D 31 30 20 65 73 3D 32 36 33 32 32 7C 63 69 64 3D 33 39 34 37 31 7C 63 69 64 3D 37 34 35 33 33 7C 63 69 64 3D 31 32 32 32 36 30 20 65 73 3D 32 39 36 34 34 31 34 7C 63 69 64 3D 31 33 37 38 32 39 20 65 73 3D 33 35 33 31 7C 63 69 64 3D 31 35 31 39 31 31 20 65 73 3D 34 30 31 31 7C 63 69 64 3D 31 38 39 37 30 36 20 65 73 3D 32 31 31 34 7C 63 69 64 3D 32 32 32 36 30 32 20 65 73 3D 34 36 35 38 7C 63 69 64 3D 32 35 30 35 33 31 20 65 73 3D 31 38 30 30 32 32 7C 63 69 64 3D 32 38 32 32 34 30 20 65 73 3D 32 34 35 38 7C 63 69 64 3D 32 39 33 38 34 34 20 65 73 3D 34 36 35 37 7C 63 69 64 3D 32 39 33 38 34 35 20 65 73 3D 33 39 36 38 7C 63 69 64 3D 32 39 33 38 34 36 20 65 73 3D 38 35 37 37 37 7C 63 69 64 3D 32 39 33 39 36 33 20 65 73 3D 34 36 36 32 7C 63 69 64 3D 32 39 35 37 39 34 7C 63 69 64 3D 32 39 35 38 35 39 7C 63 69 64 3D 32 39 35 38 36 34 7C 63 69 64 3D 32 39 35 38 37 38 7C 63 69 64 3D 32 39 35 38 38 34 7C 63 69 64 3D 32 39 35 38 39 32 7C 63 69 64 3D 32 39 35 39 30 36
  ASCI: notifychannelsubscribed cid=10 es=26322|cid=39471|cid=74533|cid=122260 es=2964414|cid=137829 es=3531|cid=151911 es=4011|cid=189706 es=2114|cid=222602 es=4658|cid=250531 es=180022|cid=282240 es=2458|cid=293844 es=4657|cid=293845 es=3968|cid=293846 es=85777|cid=293963 es=4662|cid=295794|cid=295859|cid=295864|cid=295878|cid=295884|cid=295892|cid=295906
[O] Acking: 46
[I] Type: Command       Flags: [ _ _ _ _ ]      Id: 47
  Data: 65 72 72 6F 72 20 69 64 3D 30 20 6D 73 67 3D 6F 6B 20 72 65 74 75 72 6E 5F 63 6F 64 65 3D 31
  ASCI: error id=0 msg=ok return_code=1
[O] Acking: 47
[21:42:13]  Error: Critical program failure!. Exception:
                   MSG: Value was either too large or too small for an Int64.
                   TYPE:OverflowException
                   STACK:   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
                      at TS3Client.Commands.CommandDeserializer.DeserializeInt64(String v) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Commands\CommandDeserializer.cs:line 106
                      at TS3Client.Messages.ClientEnterView.SetField(String name, String value) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Messages\MessageTemplates.cs:line 495
                      at TS3Client.Commands.CommandDeserializer.FillQueryMessage(IQueryMessage qm, IEnumerable`1 kvpData) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Commands\CommandDeserializer.cs:line 78
                      at TS3Client.Commands.CommandDeserializer.GenerateSingleNotification(String lineDataPart, NotificationType ntfyType) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Commands\CommandDeserializer.cs:line 43
                      at TS3Client.Commands.CommandDeserializer.<>c__DisplayClass0_0.<GenerateNotification>b__0(String msg) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Commands\CommandDeserializer.cs:line 30
                      at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
                      at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext()
                      at TS3AudioBot.TeamspeakControl.ExtendedClientEnterView(Object sender, IEnumerable`1 eventArgs) in C:\Users\blusc\source\repos\TS3AudioBot\TS3AudioBot\TeamspeakControl.cs:line 42
                      at TS3Client.Full.Ts3FullClient.InvokeEvent(LazyNotification lazyNotification) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Full\Ts3FullClient.cs:line 160
                      at TS3Client.DoubleThreadEventDispatcher.DispatchLoop() in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\EventDispatcher.cs:line 180
                      at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
                      at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
                      at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
                      at System.Threading.ThreadHelper.ThreadStart()

Error call Stack:
Void <Main>b__0(System.Object, System.UnhandledExceptionEventArgs)@0
Int64 ParseInt64(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)@0
Int64 DeserializeInt64(System.String)@0
Void SetField(System.String, System.String)@0
Void FillQueryMessage(TS3Client.Messages.IQueryMessage, System.Collections.Generic.IEnumerable`1[System.Collections.Generic.KeyValuePair`2[System.String,System.String]])@0
TS3Client.Messages.INotification GenerateSingleNotification(System.String, TS3Client.NotificationType)@0
TS3Client.Messages.INotification <GenerateNotification>b__0(System.String)@0
Boolean MoveNext()@0
Boolean MoveNext()@0
Void ExtendedClientEnterView(System.Object, System.Collections.Generic.IEnumerable`1[TS3Client.Messages.ClientEnterView])@0
Void InvokeEvent(TS3Client.LazyNotification)@0
Void DispatchLoop()@0
Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)@0
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)@0
Void Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)@0
Void ThreadStart()@0 T:TS3 Dispatcher
[21:42:13]   Info: TS3AudioBot shutting down.
[21:42:13]   Info: Bot disconnecting.
[O] Type: Command       Flags: [ _ X _ _ ]      Id: 3
  Data: 77 68 6F 61 6D 69 20 72 65 74 75 72 6E 5F 63 6F 64 65 3D 32
  ASCI: whoami return_code=2
[I] Acking: 3
[I] Type: Command       Flags: [ _ _ _ _ ]      Id: 48
  Data: 76 69 72 74 75 61 6C 73 65 72 76 65 72 5F 73 74 61 74 75 73 3D 6F 6E 6C 69 6E 65 20 76 69 72 74 75 61 6C 73 65 72 76 65 72 5F 69 64 3D 31 20 76 69 72 74 75 61 6C 73 65 72 76 65 72 5F 75 6E 69 71 75 65 5F 69 64 65 6E 74 69 66 69 65 72 3D 38 42 4D 77 64 33 55 6D 31 67 43 76 54 74 78 31 37 72 6C 62 32 41 31 4F 6B 36 4D 3D 20 76 69 72 74 75 61 6C 73 65 72 76 65 72 5F 70 6F 72 74 3D 39 39 38 37 20 63 6C 69 65 6E 74 5F 69 64 3D 39 31 20 63 6C 69 65 6E 74 5F 63 68 61 6E 6E 65 6C 5F 69 64 3D 31 20 63 6C 69 65 6E 74 5F 6E 69 63 6B 6E 61 6D 65 3D 4E 65 77 42 65 61 6E 20 63 6C 69 65 6E 74 5F 64 61 74 61 62 61 73 65 5F 69 64 3D 30 20 63 6C 69 65 6E 74 5F 6C 6F 67 69 6E 5F 6E 61 6D 65 20 63 6C 69 65 6E 74 5F 75 6E 69 71 75 65 5F 69 64 65 6E 74 69 66 69 65 72 20 63 6C 69 65 6E 74 5F 6F 72 69 67 69 6E 5F 73 65 72 76 65 72 5F 69 64 3D 30
  ASCI: virtualserver_status=online virtualserver_id=1 virtualserver_unique_identifier=8BMwd3Um1gCvTtx17rlb2A1Ok6M= virtualserver_port=9987 client_id=91 client_channel_id=1 client_nickname=NewBean client_database_id=0 client_login_name client_unique_identifier client_origin_server_id=0
[O] Acking: 48
[I] Type: Command       Flags: [ _ _ _ _ ]      Id: 49
  Data: 65 72 72 6F 72 20 69 64 3D 30 20 6D 73 67 3D 6F 6B 20 72 65 74 75 72 6E 5F 63 6F 64 65 3D 32
  ASCI: error id=0 msg=ok return_code=2
[O] Acking: 49
[O] Type: Command       Flags: [ _ X _ _ ]      Id: 4
  Data: 63 6C 69 65 6E 74 67 65 74 64 62 69 64 66 72 6F 6D 75 69 64 20 63 6C 75 69 64 3D 48 4A 75 78 65 62 6A 6B 37 45 4E 74 32 62 30 57 67 57 4C 4A 70 48 4C 6A 54 42 73 3D 20 72 65 74 75 72 6E 5F 63 6F 64 65 3D 33
  ASCI: clientgetdbidfromuid cluid=HJuxebjk7ENt2b0WgWLJpHLjTBs= return_code=3
[I] Acking: 4
[I] Type: Command       Flags: [ _ _ _ _ ]      Id: 50
  Data: 6E 6F 74 69 66 79 63 6C 69 65 6E 74 64 62 69 64 66 72 6F 6D 75 69 64 20 63 6C 75 69 64 3D 48 4A 75 78 65 62 6A 6B 37 45 4E 74 32 62 30 57 67 57 4C 4A 70 48 4C 6A 54 42 73 3D 20 63 6C 64 62 69 64 3D 31 36 33 36 30 37
  ASCI: notifyclientdbidfromuid cluid=HJuxebjk7ENt2b0WgWLJpHLjTBs= cldbid=163607
[O] Acking: 50
[I] Type: Command       Flags: [ _ _ _ _ ]      Id: 51
  Data: 65 72 72 6F 72 20 69 64 3D 30 20 6D 73 67 3D 6F 6B 20 72 65 74 75 72 6E 5F 63 6F 64 65 3D 33
  ASCI: error id=0 msg=ok return_code=3
[O] Acking: 51
[O] Type: Command       Flags: [ _ X _ _ ]      Id: 5
  Data: 63 6C 69 65 6E 74 65 64 69 74 20 63 6C 69 64 3D 39 31 20 63 6C 69 65 6E 74 5F 64 65 73 63 72 69 70 74 69 6F 6E 3D 3C 53 6C 65 65 70 69 6E 67 3E 20 72 65 74 75 72 6E 5F 63 6F 64 65 3D 34
  ASCI: clientedit clid=91 client_description=<Sleeping> return_code=4
[I] Acking: 5
[I] Type: Command       Flags: [ _ _ _ _ ]      Id: 52
  Data: 65 72 72 6F 72 20 69 64 3D 32 35 36 38 20 6D 73 67 3D 69 6E 73 75 66 66 69 63 69 65 6E 74 5C 73 63 6C 69 65 6E 74 5C 73 70 65 72 6D 69 73 73 69 6F 6E 73 20 72 65 74 75 72 6E 5F 63 6F 64 65 3D 34 20 66 61 69 6C 65 64 5F 70 65 72 6D 69 64 3D 32 32 37
  ASCI: error id=2568 msg=insufficient\sclient\spermissions return_code=4 failed_permid=227
[O] Acking: 52
[21:42:13]Warning: permissions_client_insufficient: the command failed to execute: insufficient client permissions (missing permission:b_client_modify_own_description)
[O] Type: Command       Flags: [ _ X _ _ ]      Id: 6
  Data: 66 74 69 6E 69 74 75 70 6C 6F 61 64 20 63 69 64 3D 30 20 6E 61 6D 65 3D 5C 2F 61 76 61 74 61 72 20 63 70 77 3D 20 63 6C 69 65 6E 74 66 74 66 69 64 3D 31 20 73 69 7A 65 3D 31 32 35 36 34 20 6F 76 65 72 77 72 69 74 65 3D 31 20 72 65 73 75 6D 65 3D 30 20 72 65 74 75 72 6E 5F 63 6F 64 65 3D 35
  ASCI: ftinitupload cid=0 name=\/avatar cpw= clientftfid=1 size=12564 overwrite=1 resume=0 return_code=5
[I] Acking: 6
[I] Type: Command       Flags: [ _ _ _ _ ]      Id: 53
  Data: 65 72 72 6F 72 20 69 64 3D 30 20 6D 73 67 3D 6F 6B 20 72 65 74 75 72 6E 5F 63 6F 64 65 3D 35
  ASCI: error id=0 msg=ok return_code=5
[O] Acking: 53
[I] Type: Command       Flags: [ _ _ _ _ ]      Id: 54
  Data: 6E 6F 74 69 66 79 73 74 61 72 74 75 70 6C 6F 61 64 20 63 6C 69 65 6E 74 66 74 66 69 64 3D 31 20 73 65 72 76 65 72 66 74 66 69 64 3D 36 35 20 66 74 6B 65 79 3D 2B 66 42 67 52 76 71 4B 61 6F 34 45 4A 5A 56 37 45 73 49 57 47 44 54 57 66 49 7A 52 76 50 63 76 20 70 6F 72 74 3D 33 30 30 33 33 20 73 65 65 6B 70 6F 73 3D 30 20 70 72 6F 74 6F 3D 30
  ASCI: notifystartupload clientftfid=1 serverftfid=65 ftkey=+fBgRvqKao4EJZV7EsIWGDTWfIzRvPcv port=30033 seekpos=0 proto=0
[O] Acking: 54
[O] Type: Command       Flags: [ _ X _ _ ]      Id: 7
  Data: 63 6C 69 65 6E 74 75 70 64 61 74 65 20 63 6C 69 65 6E 74 5F 66 6C 61 67 5F 61 76 61 74 61 72 3D 61 39 63 34 35 34 65 65 65 35 64 30 31 32 33 34 36 32 63 38 65 35 64 65 33 34 63 33 35 38 66 61 20 72 65 74 75 72 6E 5F 63 6F 64 65 3D 36
  ASCI: clientupdate client_flag_avatar=a9c454eee5d0123462c8e5de34c358fa return_code=6
[I] Acking: 7
[I] Type: Command       Flags: [ _ _ _ _ ]      Id: 55
  Data: 6E 6F 74 69 66 79 63 6C 69 65 6E 74 75 70 64 61 74 65 64 20 63 6C 69 64 3D 39 31 20 63 6C 69 65 6E 74 5F 66 6C 61 67 5F 61 76 61 74 61 72 3D 61 39 63 34 35 34 65 65 65 35 64 30 31 32 33 34 36 32 63 38 65 35 64 65 33 34 63 33 35 38 66 61
  ASCI: notifyclientupdated clid=91 client_flag_avatar=a9c454eee5d0123462c8e5de34c358fa
[O] Acking: 55
[I] Type: Command       Flags: [ _ _ _ _ ]      Id: 56
  Data: 65 72 72 6F 72 20 69 64 3D 30 20 6D 73 67 3D 6F 6B 20 72 65 74 75 72 6E 5F 63 6F 64 65 3D 36
  ASCI: error id=0 msg=ok return_code=6
[O] Acking: 56
[21:42:13]   Info: Closing QueryConnection...
[O] Type: Command       Flags: [ _ X _ _ ]      Id: 8
  Data: 63 6C 69 65 6E 74 64 69 73 63 6F 6E 6E 65 63 74 20 72 65 61 73 6F 6E 69 64 3D 38 20 72 65 61 73 6F 6E 6D 73 67 3D 64 69 73 63 6F 6E 6E 65 63 74 65 64
  ASCI: clientdisconnect reasonid=8 reasonmsg=disconnected
[I] Acking: 8
[I] Type: Command       Flags: [ _ _ _ _ ]      Id: 57
  Data: 6E 6F 74 69 66 79 63 6C 69 65 6E 74 6C 65 66 74 76 69 65 77 20 63 66 69 64 3D 31 20 63 74 69 64 3D 30 20 72 65 61 73 6F 6E 69 64 3D 38 20 72 65 61 73 6F 6E 6D 73 67 3D 64 69 73 63 6F 6E 6E 65 63 74 65 64 20 63 6C 69 64 3D 39 31
  ASCI: notifyclientleftview cfid=1 ctid=0 reasonid=8 reasonmsg=disconnected clid=91
[O] Acking: 57
[21:42:13]  Debug: Bot disconnected. Reason: LeftServer
[21:42:13]   Info: Closing QueryConnection...

Unhandled Exception: System.OverflowException: Value was either too large or too small for an Int64.
   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at TS3Client.Commands.CommandDeserializer.DeserializeInt64(String v) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Commands\CommandDeserializer.cs:line 106
   at TS3Client.Messages.ClientEnterView.SetField(String name, String value) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Messages\MessageTemplates.cs:line 495
   at TS3Client.Commands.CommandDeserializer.FillQueryMessage(IQueryMessage qm, IEnumerable`1 kvpData) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Commands\CommandDeserializer.cs:line 78
   at TS3Client.Commands.CommandDeserializer.GenerateSingleNotification(String lineDataPart, NotificationType ntfyType) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Commands\CommandDeserializer.cs:line 43
   at TS3Client.Commands.CommandDeserializer.<>c__DisplayClass0_0.<GenerateNotification>b__0(String msg) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Commands\CommandDeserializer.cs:line 30
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext()
   at TS3AudioBot.TeamspeakControl.ExtendedClientEnterView(Object sender, IEnumerable`1 eventArgs) in C:\Users\blusc\source\repos\TS3AudioBot\TS3AudioBot\TeamspeakControl.cs:line 42
   at TS3Client.Full.Ts3FullClient.InvokeEvent(LazyNotification lazyNotification) in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\Full\Ts3FullClient.cs:line 160
   at TS3Client.DoubleThreadEventDispatcher.DispatchLoop() in C:\Users\blusc\source\repos\TS3AudioBot\TS3Client\EventDispatcher.cs:line 180
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()


Press Enter or Esc to close console...
```
