### ISSUE TITLE
i cant complie the new version !

### ISSUE THREAD

**Issue by lima12** [Splamy/TS3AudioBot#167]
so im using visual C studio to complie and it encounter IDE0006 , CS1617 and bunch of error 
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning		WARN [11/22/17 1:05:12:31] Could not determine assembly version: System.IO.DirectoryNotFoundException: Can't find the .git directory in E:\TS3AudioBot-master
   at GitVersion.GitPreparer.GetDotGitDirectory()
   at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig)
   at GitVersion.ExecuteCore.TryGetVersion(String directory, VersionVariables& versionVariables, Boolean noFetch, Authentication authentication)	TS3AudioBot			
```
BTW what is nightly build ? i can get it to connect but nothing work

**Comment by Splamy** [comment]
Hmm gitversion uses the git history to generate a version string, can you try to download the git repo via clone instead of zip download.

The nightly versions always provide the latest commit as a compiled version. Which might not always be stable or recommended. It's just immediately available.

**Comment by Splamy** [comment]
Since this issue is over a month old I will close it now. If you still have any problems feel free to reopen this or open a new issue.
