### ISSUE TITLE
Can't Start in Windows Server

### ISSUE THREAD

**Issue by georgeinw** [Splamy/TS3AudioBot#211]
Bot can't running in windows server 2008

and logs is 

2018-03-19 12:00:05.2635| INFO|Core.InitializeCore [============ TS3AudioBot started =============]
2018-03-19 12:00:05.4025| INFO|Core.InitializeCore [=== Date/Time: 19 March 2561 12:00:05
2018-03-19 12:00:05.4025| INFO|Core.InitializeCore [=== Version: 0.9.0-unstable.15/develop/9f7f228b
2018-03-19 12:00:05.4025| INFO|Core.InitializeCore [=== Platform: Windows 6.1.7601.65536 (64bit)
2018-03-19 12:00:05.4025| INFO|Core.InitializeCore [=== Runtime: .NET Framework 4.0.30319.18331
2018-03-19 12:00:05.4225| INFO|Core.InitializeCore [=== Opus: libopus 1.2.1-fixed (x64)
2018-03-19 12:00:05.4225| INFO|Core.InitializeCore [==============================================]
2018-03-19 12:00:05.4225| INFO|Core.InitializeCore [============ Initializing Modules ============]
2018-03-19 12:00:05.5285|FATAL|Core.ExceptionHandler Critical program failure!.
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at TS3AudioBot.CommandSystem.BotCommand..ctor(CommandBuildInfo buildInfo)
   at TS3AudioBot.CommandSystem.CommandManager.<GetBotCommands>d__19.MoveNext()
   at TS3AudioBot.CommandSystem.CommandManager.RegisterMain()
   at TS3AudioBot.Core.<>c.<InitializeCore>b__34_1(CommandManager x)
   at TS3AudioBot.Dependency.Module.SetInitalized()
   at TS3AudioBot.Dependency.DependencyRealm.DoQueueInitialize(Boolean force)
   at TS3AudioBot.Core.InitializeCore()
   at TS3AudioBot.Core.Main(String[] args)

**Comment by Flakebi** [comment]
You probably need to upgrade your .NET Framework version to something newer (4.6 or above).
Also @Splamy should increase the minimum needed framework version in the project config.
(see https://stackoverflow.com/questions/31253747/method-not-found-0-system-array-empty-asapp-bundleconfig-registerbundl for some more information)

**Comment by georgeinw** [comment]
oh, yea thanks you @Flakebi it's fixed my problem
