### ISSUE TITLE
Bot is not playing Music (Stream/Youtube)

### ISSUE THREAD

**Issue by DiBaDu** [Splamy/TS3AudioBot#252]
Hello,

I have the Bot in Windows 64Bit.
The Youtube-dll.exe and ffmpeg.exe are in the foulder of the Bot.
If I try to play a youtube Song the Bot change the Description and the avatar to the Video thumbnail
(!play https://www.youtube.com/watch?v=m6NHkHrvWCI)
than 1 wait 10 minutes but I cant hear music  I get this Info:

`| INFO|PlayManager.StopInternal Song queue ended: No next song could be played`

But i cant hear any music but i see no errors. The bot hase Talk-Power

With Radio-Streams the Same Problem. Here is the Complet log:

On Pastebin: https://pastebin.com/aRR900n5

Its the same:

```
2018-05-10 10:03:58.4520| INFO|Core.InitializeCore [============ TS3AudioBot started =============]
2018-05-10 10:03:58.5090| INFO|Core.InitializeCore [=== Date/Time: Donnerstag, 10. Mai 2018 10:03:58
2018-05-10 10:03:58.5090| INFO|Core.InitializeCore [=== Version: 0.9.0-unstable.35/develop/b529f8eb
2018-05-10 10:03:58.5090| INFO|Core.InitializeCore [=== Platform: Windows 6.1.7601.65536 (64bit)
2018-05-10 10:03:58.5200| INFO|Core.InitializeCore [=== Runtime: .NET Framework 4.0.30319.42000
2018-05-10 10:03:58.5200| INFO|Core.InitializeCore [=== Opus: libopus 1.2.1-fixed (x64)
2018-05-10 10:03:58.5200| INFO|Core.InitializeCore [==============================================]
2018-05-10 10:03:58.5200| INFO|Core.InitializeCore [============ Initializing Modules ============]
2018-05-10 10:03:58.8460| INFO|Core.InitializeCore [==================== Done ====================]
2018-05-10 10:03:58.8540| INFO|Bot.InitializeBot Bot connecting...
2018-05-10 10:03:59.8861| INFO|Bot.OnBotConnected Bot connected.
2018-05-10 10:04:13.9859|DEBUG|Bot.TextCallback Got message from Max: !play [URL]https://www.youtube.com/watch?v=tivH0uZCxTU[/URL]
2018-05-10 10:04:14.0699|DEBUG|SessionManager.CreateSession User Max created session with the bot
2018-05-10 10:04:14.4889|DEBUG|YoutubeFactory.YoutubeDlWrapped Falling back to youtube-dl!
2018-05-10 10:04:19.4842|DEBUG|YoutubeFactory.YoutubeDlWrapped youtube-dl succeeded!
2018-05-10 10:04:19.5012|DEBUG|PlayManager.StartResource AudioResource start: youtube ID:tivH0uZCxTU
2018-05-10 10:04:58.4364| INFO|PlayManager.StopInternal Song queue ended: No next song could be played.
2018-05-10 10:05:52.3435|DEBUG|Bot.TextCallback Got message from Max: !vol 100
2018-05-10 10:05:52.4695|DEBUG|Bot.CallScript Command Error (Careful you are requesting a very high volume! Do you want to apply this? !(yes|no))
TS3AudioBot.CommandSystem.CommandException: Careful you are requesting a very high volume! Do you want to apply this? !(yes|no)
   at TS3AudioBot.MainCommands.CommandVolume(ExecutionInformation info, IPlayerConnection playerConnection, CallerInfo caller, UserSession session, String parameter)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.ExecuteFunction(Object[] parameters)
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes)
   at TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes)
   at TS3AudioBot.Bot.CallScript(ExecutionInformation info, String command, Boolean answer, Boolean skipRights)
2018-05-10 10:06:00.9840|DEBUG|Bot.TextCallback Got message from Max: !yes
2018-05-10 10:06:04.9592|DEBUG|Bot.TextCallback Got message from Max: !link [URL]https://www.youtube.com/watch?v=m6NHkHrvWCI[/URL]
2018-05-10 10:06:05.0762|DEBUG|Bot.CallScript Command Error (There is nothing on right now...)
TS3AudioBot.CommandSystem.CommandException: There is nothing on right now...
   at TS3AudioBot.MainCommands.CommandLink(ResourceFactoryManager factoryManager, PlayManager playManager, Bot bot, CallerInfo caller, InvokerData invoker)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.ExecuteFunction(Object[] parameters)
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes)
   at TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes)
   at TS3AudioBot.Bot.CallScript(ExecutionInformation info, String command, Boolean answer, Boolean skipRights)
2018-05-10 10:06:10.9336|DEBUG|Bot.TextCallback Got message from Max: !play [URL]https://www.youtube.com/watch?v=m6NHkHrvWCI[/URL]
2018-05-10 10:06:11.1936|DEBUG|YoutubeFactory.YoutubeDlWrapped Falling back to youtube-dl!
2018-05-10 10:06:14.9598|DEBUG|YoutubeFactory.YoutubeDlWrapped youtube-dl succeeded!
2018-05-10 10:06:14.9598|DEBUG|PlayManager.StartResource AudioResource start: youtube ID:m6NHkHrvWCI
2018-05-10 10:06:45.0475| INFO|PlayManager.StopInternal Song queue ended: No next song could be played.
2018-05-10 10:06:57.5492|DEBUG|Bot.TextCallback Got message from Max: !play [URL]http://stream01.iloveradio.de/iloveradio1.mp3[/URL]
2018-05-10 10:06:58.3363|DEBUG|PlayManager.StartResource AudioResource start: media ID:http://stream01.iloveradio.de/iloveradio1.mp3
```

It would be very nice if anybody can help me

**Comment by Splamy** [comment]
Can you start a song and then call `!whisper off`

If that fixed the problem then you can permanently change that with `!settings AudioFramework::AudioMode voice`

If not, write back and I'll see if i can find something else.

**Comment by seirex1234** [comment]
Ohh thank you soo much, Its working. After setup !whisper off and it works

**Comment by Splamy** [comment]
Nice! (don't forget to change it permanently with the settings call)
