### ISSUE TITLE
developh geht nicht

### ISSUE THREAD

**Issue by preterive** [Splamy/TS3AudioBot#289]
Hi,
die developh Version läuft bei mir nicht.
Ubuntu 16.04
Error: 
`System.TypeInitializationException: The type initializer for 'TS3Client.Audio.Opus.NativeMethods' threw an exception. ---> System.DllNotFoundException: libdl.so
`

**Comment by preterive** [comment]
fehler gefunden, ich schick n request

**Comment by Bluscream** [comment]
develop nightly build startet bei mir nichma 

![grafik](https://user-images.githubusercontent.com/3318223/41389736-fc16486a-6f81-11e8-825f-96027fd94756.png)

```
2018-06-14 05:19:36.4621|FATAL|Core.ExceptionHandler Critical program failure!.
System.IO.IOException: No process is on the other end of the pipe.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__ConsoleStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadLine()
   at System.IO.TextReader.SyncTextReader.ReadLine()
   at System.Console.ReadLine()
   at TS3AudioBot.Helper.ConfigFile.GetDataStruct[T](String associatedClass, Boolean defaultIfPossible)
   at TS3AudioBot.Core.InitializeCore()
   at TS3AudioBot.Core.Main(String[] args)
2018-06-14 05:19:36.6001| INFO|Core.Dispose TS3AudioBot shutting down.
2018-06-14 05:19:52.1167|FATAL|Core.ExceptionHandler Critical program failure!.
System.IO.IOException: No process is on the other end of the pipe.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__ConsoleStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadLine()
   at System.IO.TextReader.SyncTextReader.ReadLine()
   at System.Console.ReadLine()
   at TS3AudioBot.Helper.ConfigFile.GetDataStruct[T](String associatedClass, Boolean defaultIfPossible)
   at TS3AudioBot.Core.InitializeCore()
   at TS3AudioBot.Core.Main(String[] args)
2018-06-14 05:19:52.1947| INFO|Core.Dispose TS3AudioBot shutting down.
```

**Comment by Splamy** [comment]
Uhm, your files seem a bit outdated, this can't be the current develop branch.
Neither `Core.InitializeCore()` nor `TS3AudioBot.Helper.ConfigFile` do exist in the current build.
