### ISSUE TITLE
!bot avatar set ... not working

### ISSUE THREAD

**Issue by akizzed** [Splamy/TS3AudioBot#498]
Hi, 
i just tried to set the avatar of the bot, but he throws an error.

The command: `!bot avatar set C:\Users\Administrator\Desktop\TS3AudioBot_node1\avatar.png`

```
2019-02-06 14:51:12.3086| WARN|WebWrapper.ToLoggedError Unknown request error
System.TypeInitializationException: The type initializer for 'SixLabors.ImageSharp.Configuration' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at SixLabors.Memory.ArrayPoolMemoryAllocator.InitArrayPools()
   at SixLabors.Memory.ArrayPoolMemoryAllocator.CreateDefault()
   at SixLabors.ImageSharp.Configuration..ctor(IConfigurationModule[] configurationModules)
   at SixLabors.ImageSharp.Configuration.CreateDefaultInstance()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at SixLabors.ImageSharp.Configuration..cctor()
   --- End of inner exception stack trace ---
   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)
   at TS3AudioBot.Helper.ImageUtil.ResizeImage(Stream imgStream, Int32 resizeMaxWidth)
   at TS3AudioBot.MainCommands.<>c__DisplayClass10_0.<CommandBotAvatarSet>b__0(WebResponse x)
   at TS3AudioBot.Helper.WebWrapper.GetResponse(Uri link, Action`1 body, TimeSpan timeout)
```

**Comment by Splamy** [comment]
- update your mono or dontnet core.
- run `nuget restore`.
- And if that doesnt help add a binding redirect file called `TS3AudioBot.exe.config` near the `TS3AudioBot.exe`
and add this in it:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Buffers" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.3.0"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```
