### ISSUE TITLE
TS3AudioBot webapi stops and freeze bot's

### ISSUE THREAD

**Issue by WrightBlue** [Splamy/TS3AudioBot#508]
**Describe the bug**
The bug happens when my webinterface is making a request to the TS3AudioBot api.

**Version**
Version: 0.10.0-alpha.74
Branch: develop
CommitHash: b549556504a85775b685d2f1d4c20614a5958472

**Platform**
Platform: Debian GNU/Linux 9 (stretch) (64bit)
Runtime: Mono (5.18.0.240 (tarball Wed Jan 16 09:10:58 UTC 2019))

**Log**
```
12:45:55| INFO|WebServer.EnterWebLoop 127.0.0.1 Requested: /api/bot/list
12:45:55|ERROR|WebApi.ProcessApiV1Call Unexpected command error
System.IO.IOException: Unable to write data to the transport connection: The socket has been shut down. ---> System.Net.Sockets.SocketException: The socket has been shut down
  at System.Net.Sockets.Socket.Send (System.Byte[] buffer, System.Int32 offset, System.Int32 size, System.Net.Sockets.SocketFlags socketFlags) [0x00016] in <5bf358e735be486487282a37cb3bce80>:0 
  at System.Net.Sockets.NetworkStream.Write (System.Byte[] buffer, System.Int32 offset, System.Int32 size) [0x0009b] in <5bf358e735be486487282a37cb3bce80>:0 
   --- End of inner exception stack trace ---
  at System.Net.Sockets.NetworkStream.Write (System.Byte[] buffer, System.Int32 offset, System.Int32 size) [0x000e2] in <5bf358e735be486487282a37cb3bce80>:0 
  at System.Net.ResponseStream.InternalWrite (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x0001b] in <5bf358e735be486487282a37cb3bce80>:0 
  at System.Net.ResponseStream.Write (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x000db] in <5bf358e735be486487282a37cb3bce80>:0 
  at System.IO.StreamWriter.Flush (System.Boolean flushStream, System.Boolean flushEncoder) [0x0007e] in <04750267503a43e5929c1d1ba19daf3e>:0 
  at System.IO.StreamWriter.Dispose (System.Boolean disposing) [0x00022] in <04750267503a43e5929c1d1ba19daf3e>:0 
  at System.IO.TextWriter.Dispose () [0x00000] in <04750267503a43e5929c1d1ba19daf3e>:0 
  at TS3AudioBot.Web.Api.WebApi.ProcessApiV1Call (System.Uri uri, System.Net.HttpListenerResponse response, TS3AudioBot.InvokerData invoker) [0x000ef] in <1faf753cb58a44638b3bad64139d28b2>:0 
12:45:55|ERROR|WebApi.ProcessApiV1Call Failed to respond to HTTP request.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListenerResponse'.
  at System.Net.HttpListenerResponse.set_StatusCode (System.Int32 value) [0x00013] in <5bf358e735be486487282a37cb3bce80>:0 
  at TS3AudioBot.Web.Api.WebApi.ProcessApiV1Call (System.Uri uri, System.Net.HttpListenerResponse response, TS3AudioBot.InvokerData invoker) [0x0014b] in <1faf753cb58a44638b3bad64139d28b2>:0 
12:45:55| INFO|WebServer.EnterWebLoop 127.0.0.1 Requested: /api/bot/list
12:45:55|ERROR|WebApi.ProcessApiV1Call Unexpected command error
System.IO.IOException: Unable to write data to the transport connection: The socket has been shut down. ---> System.Net.Sockets.SocketException: The socket has been shut down
  at System.Net.Sockets.Socket.Send (System.Byte[] buffer, System.Int32 offset, System.Int32 size, System.Net.Sockets.SocketFlags socketFlags) [0x00016] in <5bf358e735be486487282a37cb3bce80>:0 
  at System.Net.Sockets.NetworkStream.Write (System.Byte[] buffer, System.Int32 offset, System.Int32 size) [0x0009b] in <5bf358e735be486487282a37cb3bce80>:0 
   --- End of inner exception stack trace ---
  at System.Net.Sockets.NetworkStream.Write (System.Byte[] buffer, System.Int32 offset, System.Int32 size) [0x000e2] in <5bf358e735be486487282a37cb3bce80>:0 
  at System.Net.ResponseStream.InternalWrite (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x0001b] in <5bf358e735be486487282a37cb3bce80>:0 
  at System.Net.ResponseStream.Write (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x000db] in <5bf358e735be486487282a37cb3bce80>:0 
  at System.IO.StreamWriter.Flush (System.Boolean flushStream, System.Boolean flushEncoder) [0x0007e] in <04750267503a43e5929c1d1ba19daf3e>:0 
  at System.IO.StreamWriter.Dispose (System.Boolean disposing) [0x00022] in <04750267503a43e5929c1d1ba19daf3e>:0 
  at System.IO.TextWriter.Dispose () [0x00000] in <04750267503a43e5929c1d1ba19daf3e>:0 
  at TS3AudioBot.Web.Api.WebApi.ProcessApiV1Call (System.Uri uri, System.Net.HttpListenerResponse response, TS3AudioBot.InvokerData invoker) [0x000ef] in <1faf753cb58a44638b3bad64139d28b2>:0 
12:45:55|ERROR|WebApi.ProcessApiV1Call Failed to respond to HTTP request.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListenerResponse'.
  at System.Net.HttpListenerResponse.set_StatusCode (System.Int32 value) [0x00013] in <5bf358e735be486487282a37cb3bce80>:0 
  at TS3AudioBot.Web.Api.WebApi.ProcessApiV1Call (System.Uri uri, System.Net.HttpListenerResponse response, TS3AudioBot.InvokerData invoker) [0x0014b] in <1faf753cb58a44638b3bad64139d28b2>:0 
12:45:55| INFO|WebServer.EnterWebLoop 127.0.0.1 Requested: /api/bot/list
```

**Comment by Splamy** [comment]
Those errors indicate that the caller (in this case your webinterface) closes the connection before the entire response could be sent.
Usually you can safely ignore those errors as they mostly only occour rarely in case of faulty connections. However if this happens consistently I would need more information in how to reproduce this locally to test it.

**Comment by ruymb** [comment]
Hate to admit it but this to is happening to me even without the WEBAPI it's when you run multiple radio stations and then you run youtube the whole program just crashes and it's not good when you run a community TeamSpeak and this happens 24/7

**Comment by ruymb** [comment]
It happens when you have around 3-4 bots connected you play radio stations on 3 of them and you play youtube on the 4th one or even without youtube it just crashes can't keep up with it.

**Comment by Flakebi** [comment]
@ruymb What does happen even without the webapi? The bot freezes and times out?
Then this might be (just guessing) the same issue as #492, too much load on your cpu.

Otherwise I am not sure what you mean, the exceptions are related to the webapi and I can hardly think of a case where a HttpListenerResponse throws an exception somewhere else.

**Comment by ruymb** [comment]
Not to much load at all! I've tried 1 core 2gb ram running 6 bots, 2 core 4gb ram still 6 bots and 4 core and 8gb ram still 6 bots all result in the same

**Comment by ruymb** [comment]
The bots do not drop at all they freeze

**Comment by ruymb** [comment]
18:22:58.7645| WARN Bot is not correctly set up. Some commands might not work or are slower (clientlist:Unknown Teamspeak Error. (Connection closed), clientinfo:No client found. (Unknown Teamspeak Error. (Connection closed))).
18:22:58.7720| WARN Could not write message: Unknown Teamspeak Error. (Connection closed)
18:22:58.7731| INFO User Toxic requested: !yes
18:22:58.7731| WARN Bot is not correctly set up. Some commands might not work or are slower (clientlist:Unknown Teamspeak Error. (Connection closed), clientinfo:No client found. (Unknown Teamspeak Error. (Connection closed))).
18:22:58.7778| WARN Could not write message: Unknown Teamspeak Error. (Connection closed)


Here is the error I get permissions are aleady set and subscribe power is 999 so I know it can see all I ran external tests all works fine on 3-4 bots on the 5th one it just freeze leave it for 10 minutes go back to screen disconnect the screen and this is the error message I get.

**Comment by ruymb** [comment]
I am using the master version by the way.

**Comment by Splamy** [comment]
I assume you are using mono; can you get the bot hanging and then with another terminal execute `kill -QUIT $PID` where `$PID` is the process id of mono running the bot.
This should print a threaddump of all threads on the terminal where the bot is running.
Maybe I can see some problems in the threaddump.

**Comment by ruymb** [comment]
I can do one better than that if you have steam etc I can give you access to the VPS.

**Comment by ruymb** [comment]
Also I just worked out something new if you kill one FFPMEG process then the other will carry on so there must be a bug here.

**Comment by WrightBlue** [comment]
Updated ts3audiobot to the latest version and now I have a new error.

Version: 0.10.0-alpha.80
Branch: develop
CommitHash: 5c37f4228b90c88a1bb898bb27f1ba9688232451

```
14:52:57| INFO|WebServer.EnterWebLoop 127.0.0.1 Requested: /api/bot/list
14:52:58| WARN|WebServer.EnterWebLoop WebListener exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at TS3AudioBot.Web.Api.WebApi.ProcessApiV1Call(Uri uri, HttpListenerResponse response, InvokerData invoker)
   at TS3AudioBot.Web.Api.WebApi.DispatchCall(HttpListenerContext context)
   at TS3AudioBot.Web.WebServer.EnterWebLoop()
```

**Comment by Splamy** [comment]
As this seems like a mono bug from a talk with an other user, the current solution is to change from mono to dotnet core. The nightly page https://splamy.de/Nightly now also has dotnet core builds.
