### ISSUE TITLE
System.InvalidOperationException: Compressed packet is too large

### ISSUE THREAD

**Issue by JABirchall** [Splamy/TS3AudioBot#51]
```
Unhandled Exception: System.InvalidOperationException: Compressed packet is too large
   at TS3Client.Full.PacketHandler.ReceiveCommand(IncomingPacket packet) in C:\Projects\TS3AudioBot-master\TS3Client\Full\PacketHandler.cs:line 337
   at TS3Client.Full.PacketHandler.FetchPacket() in C:\Projects\TS3AudioBot-master\TS3Client\Full\PacketHandler.cs:line 229
   at TS3Client.Full.Ts3FullClient.NetworkLoop() in C:\Projects\TS3AudioBot-master\TS3Client\Full\Ts3FullClient.cs:line 109
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

This is possibly thrown on large TeamSpeak's with high user traffic and alot of channels. Since I was instantiating a new client for each bot to ensure no of the bots were affecting each other. After 150~ bots this crash would be encountered.

**Comment by JABirchall** [comment]
Small update on this, i increased ```MaxDecompressedSize``` to 512000 and increased ```PacketBufferSize``` to 128, I also replaced ```throw new InvalidOperationException("Compressed packet is too large");``` with ```return false;```
After 1 hour and 150 active connections = 0 crashes.

Defo not a fix, but it works for me atm.

**Comment by JABirchall** [comment]
This problem is solved, But where 1 must close, another one must open.
