### ISSUE TITLE
TS3AudioBot shutting down

### ISSUE THREAD

**Issue by WrightBlue** [Splamy/TS3AudioBot#592]
**Describe the bug**
Switching off bots after a certain time.

**Version**
Version: 0.10.0-alpha.141
Branch: develop
CommitHash: 5fff90a87969ad54558da98997b9016ecc021cb9

**Platform**
.NET Core (2.2.6) / Ubuntu 16.04.6 LTS (Xenial Xerus) (64bit)

**Log**
```
01:49:01| INFO| |WebApi.ProcessApiV1Call ::ffff:127.0.0.1 Requested: /api/bot/use/0/(/rights/reload
01:49:13|FATAL|5|Core.ExceptionHandler Critical program failure!
System.NullReferenceException: Object reference not set to an instance of an object.
   at TS3AudioBot.ResourceFactories.YoutubeFactory.ResolveResourceInternal(AudioResource resource)
   at TS3AudioBot.ResourceFactories.YoutubeFactory.GetResourceById(AudioResource resource)
   at TS3AudioBot.ResourceFactories.ResourceFactoryManager.Load(AudioResource resource)
   at TS3AudioBot.Audio.PlayManager.Play(InvokerData invoker, AudioResource ar, MetaData meta)
   at TS3AudioBot.Audio.PlayManager.Play(InvokerData invoker, PlaylistItem item)
   at TS3AudioBot.Audio.PlayManager.Next(InvokerData invoker, Boolean manually)
   at TS3AudioBot.Audio.PlayManager.StopInternal(Boolean songEndedByCallback)
   at TS3AudioBot.Audio.FfmpegProducer.Read(Byte[] buffer, Int32 offset, Int32 length, Meta& meta)
   at TS3Client.Audio.PassiveMergePipe.Read(Byte[] buffer, Int32 offset, Int32 length, Meta& meta)
   at TS3Client.Audio.PreciseTimedPipe.ReadTick()
   at TS3Client.Audio.PreciseTimedPipe.ReadLoop()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
01:49:13| INFO|5|Core.Dispose TS3AudioBot shutting down.
01:49:13| INFO|5|Bot.Dispose Bot "1" (0) disconnecting.
01:49:13| INFO|5|Bot.Dispose Bot "7" (1) disconnecting.
01:49:13| WARN| |FfmpegInstance.ReadStreamLoop Stream read/write error
System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ConnectionCloseReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.HttpContentReadStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at TS3AudioBot.Audio.FfmpegProducer.FfmpegInstance.ReadStreamLoop()
01:49:13| INFO|5|Bot.Dispose Bot "9" (2) disconnecting.
01:49:13| INFO|5|Bot.Dispose Bot "5" (3) disconnecting.
01:49:13| WARN| |FfmpegInstance.ReadStreamLoop Stream read/write error
System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ConnectionCloseReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.HttpContentReadStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at TS3AudioBot.Audio.FfmpegProducer.FfmpegInstance.ReadStreamLoop()
01:49:13| INFO|5|Bot.Dispose Bot "6" (4) disconnecting.
01:49:13| INFO|5|Bot.Dispose Bot "8" (5) disconnecting.
01:50:01| INFO| |WebApi.ProcessApiV1Call ::ffff:127.0.0.1 Requested: /api/bot/use/0/(/rights/reload
01:51:01| INFO| |WebApi.ProcessApiV1Call ::ffff:127.0.0.1 Requested: /api/bot/use/0/(/rights/reload
01:52:01| INFO| |WebApi.ProcessApiV1Call ::ffff:127.0.0.1 Requested: /api/bot/use/0/(/rights/reload
01:53:01| INFO| |WebApi.ProcessApiV1Call ::ffff:127.0.0.1 Requested: /api/bot/use/0/(/rights/reload
01:54:01| INFO| |WebApi.ProcessApiV1Call ::ffff:127.0.0.1 Requested: /api/bot/use/0/(/rights/reload
01:55:01| INFO| |WebApi.ProcessApiV1Call ::ffff:127.0.0.1 Requested: /api/bot/use/0/(/rights/reload
01:56:01| INFO| |WebApi.ProcessApiV1Call ::ffff:127.0.0.1 Requested: /api/bot/use/0/(/rights/reload
01:57:02| INFO| |WebApi.ProcessApiV1Call ::ffff:127.0.0.1 Requested: /api/bot/use/0/(/rights/reload
```

**Comment by Splamy** [comment]
Was already fixed in 8d7e1282ff87e98f615746ada90a6dd4464b8941
> Fixed openapi error, fixed null in youtube facotory
