### ISSUE TITLE
[help] the INSTANTLY rage quit bot 

### ISSUE THREAD

**Issue by lima12** [Splamy/TS3AudioBot#61]
sorry for being a noob ! but after i config the bot and run it , it connect to my ts3 server and INSTANTLY disconnect ! im using window 10 to config it and soon will put on vps using win server 2008 .

**Comment by lima12** [comment]
`[03:32:42]   Info: [============ TS3AudioBot started =============]
[03:32:42]   Info: [=== Date:           Sunday, April 02, 2017 ===]
[03:32:42]   Info: [=== Time:                       3:32:42 AM ===]
[03:32:42]   Info: [==============================================]
[03:32:42]   Info: [============ Initializing Commands ===========]
[03:32:42]   Info: [============ Initializing Modules ============]
[03:32:42]Warning: App launched without elevated rights. Only localhost will be availbale as api server.
[03:32:42]   Info: [=========== Initializing Factories ===========]
[03:32:42]   Info: [=========== Registering callbacks ============]
[03:32:42]   Info: [================= Finalizing =================]
[03:32:42]   Info: [============== Connected & Done ==============]
[03:32:42]  Error: There is either a problem with your connection configuration, or the query has not all permissions it needs. (TS3Client.Ts3CommandException: 2568: the command failed to execute: insufficient client permissions (missing permission:189)
   at TS3Client.WaitBlock.WaitForMessage() in C:\Users\williamle\Desktop\TS3AudioBot-master\TS3AudioBot-master\TS3Client\WaitBlock.cs:line 41
   at TS3Client.Full.Ts3FullClient.SendCommand(Ts3Command com, Type targetType) in C:\Users\williamle\Desktop\TS3AudioBot-master\TS3AudioBot-master\TS3Client\Full\Ts3FullClient.cs:line 202
   at TS3Client.Ts3BaseClient.Send[T](String command, List`1 parameter) in C:\Users\williamle\Desktop\TS3AudioBot-master\TS3AudioBot-master\TS3Client\Ts3BaseClient.cs:line 250
   at TS3Client.Ts3BaseClient.ClientInfo(UInt16 clientId) in C:\Users\williamle\Desktop\TS3AudioBot-master\TS3AudioBot-master\TS3Client\Ts3BaseClient.cs:line 316
   at TS3AudioBot.Ts3Full.GetSelf() in C:\Users\williamle\Desktop\TS3AudioBot-master\TS3AudioBot-master\TS3AudioBot\Ts3Full.cs:line 133
   at TS3AudioBot.TeamspeakControl.OnConnected(Object sender, EventArgs e) in C:\Users\williamle\Desktop\TS3AudioBot-master\TS3AudioBot-master\TS3AudioBot\TeamspeakControl.cs:line 93
   at TS3Client.Ts3BaseClient.<ConnectDone>b__36_0() in C:\Users\williamle\Desktop\TS3AudioBot-master\TS3AudioBot-master\TS3Client\Ts3BaseClient.cs:line 100
   at TS3Client.ExtraThreadEventDispatcher.EnterEventLoop() in C:\Users\williamle\Desktop\TS3AudioBot-master\TS3AudioBot-master\TS3Client\EventDispatcher.cs:line 71
   at TS3Client.Ts3BaseClient.Connect(ConnectionData conData) in C:\Users\williamle\Desktop\TS3AudioBot-master\TS3AudioBot-master\TS3Client\Ts3BaseClient.cs:line 93
   at TS3AudioBot.Ts3Full.Connect() in C:\Users\williamle\Desktop\TS3AudioBot-master\TS3AudioBot-master\TS3AudioBot\Ts3Full.cs:line 107
   at TS3AudioBot.MainBot.Run() in C:\Users\williamle\Desktop\TS3AudioBot-master\TS3AudioBot-master\TS3AudioBot\MainBot.cs:line 208)
[03:32:42]   Info: Exiting...
[03:32:42]   Info: Closing Mediaplayer...
[03:32:42]  Debug: AF stop old
[03:32:42]Warning: Internal error (me==null)
[03:32:42]   Info: Closing QueryConnection...
[03:32:42]   Info: Closing QueryConnection...`

here what i get from log file

**Comment by lima12** [comment]
> [03:32:42]   Info: [============ TS3AudioBot started =============]
[03:32:42]   Info: [=== Date:           Sunday, April 02, 2017 ===]
[03:32:42]   Info: [=== Time:                       3:32:42 AM ===]
[03:32:42]   Info: [==============================================]
[03:32:42]   Info: [============ Initializing Commands ===========]
[03:32:42]   Info: [============ Initializing Modules ============]
[03:32:42]Warning: App launched without elevated rights. Only localhost will be availbale as api server.
[03:32:42]   Info: [=========== Initializing Factories ===========]
[03:32:42]   Info: [=========== Registering callbacks ============]
[03:32:42]   Info: [================= Finalizing =================]
[03:32:42]   Info: [============== Connected & Done ==============]
[03:32:42]  Error: There is either a problem with your connection configuration, or the query has not all permissions it needs. (TS3Client.Ts3CommandException: 2568: the command failed to execute: insufficient client permissions (missing permission:189)
   at TS3Client.WaitBlock.WaitForMessage() in C:\Users\williamle\Desktop\TS3AudioBot-master\TS3AudioBot-master\TS3Client\WaitBlock.cs:line 41
   at TS3Client.Full.Ts3FullClient.SendCommand(Ts3Command com, Type targetType) in C:\Users\williamle\Desktop\TS3AudioBot-master\TS3AudioBot-master\TS3Client\Full\Ts3FullClient.cs:line 202
   at TS3Client.Ts3BaseClient.Send[T](String command, List`1 parameter) in C:\Users\williamle\Desktop\TS3AudioBot-master\TS3AudioBot-master\TS3Client\Ts3BaseClient.cs:line 250
   at TS3Client.Ts3BaseClient.ClientInfo(UInt16 clientId) in C:\Users\williamle\Desktop\TS3AudioBot-master\TS3AudioBot-master\TS3Client\Ts3BaseClient.cs:line 316
   at TS3AudioBot.Ts3Full.GetSelf() in C:\Users\williamle\Desktop\TS3AudioBot-master\TS3AudioBot-master\TS3AudioBot\Ts3Full.cs:line 133
   at TS3AudioBot.TeamspeakControl.OnConnected(Object sender, EventArgs e) in C:\Users\williamle\Desktop\TS3AudioBot-master\TS3AudioBot-master\TS3AudioBot\TeamspeakControl.cs:line 93
   at TS3Client.Ts3BaseClient.<ConnectDone>b__36_0() in C:\Users\williamle\Desktop\TS3AudioBot-master\TS3AudioBot-master\TS3Client\Ts3BaseClient.cs:line 100
   at TS3Client.ExtraThreadEventDispatcher.EnterEventLoop() in C:\Users\williamle\Desktop\TS3AudioBot-master\TS3AudioBot-master\TS3Client\EventDispatcher.cs:line 71
   at TS3Client.Ts3BaseClient.Connect(ConnectionData conData) in C:\Users\williamle\Desktop\TS3AudioBot-master\TS3AudioBot-master\TS3Client\Ts3BaseClient.cs:line 93
   at TS3AudioBot.Ts3Full.Connect() in C:\Users\williamle\Desktop\TS3AudioBot-master\TS3AudioBot-master\TS3AudioBot\Ts3Full.cs:line 107
   at TS3AudioBot.MainBot.Run() in C:\Users\williamle\Desktop\TS3AudioBot-master\TS3AudioBot-master\TS3AudioBot\MainBot.cs:line 208)
[03:32:42]   Info: Exiting...
[03:32:42]   Info: Closing Mediaplayer...
[03:32:42]  Debug: AF stop old
[03:32:42]Warning: Internal error (me==null)
[03:32:42]   Info: Closing QueryConnection...
[03:32:42]   Info: Closing QueryConnection...<
here the log

**Comment by lima12** [comment]
ok i fixed it by pausing it and gave it acess !
but i came to next problem . it have no sound at all ... 
>[03:48:14]   Info: [============ TS3AudioBot started =============]
[03:48:14]   Info: [=== Date:           Sunday, April 02, 2017 ===]
[03:48:14]   Info: [=== Time:                       3:48:14 AM ===]
[03:48:14]   Info: [==============================================]
[03:48:14]   Info: [============ Initializing Commands ===========]
[03:48:14]   Info: [============ Initializing Modules ============]
[03:48:14]Warning: App launched without elevated rights. Only localhost will be availbale as api server.
[03:48:14]   Info: [=========== Initializing Factories ===========]
[03:48:14]   Info: [=========== Registering callbacks ============]
[03:48:14]   Info: [================= Finalizing =================]
[03:48:14]   Info: [============== Connected & Done ==============]
[03:48:27]  Debug: MB Got message from williamle12: !play [URL]https://www.youtube.com/watch?v=cQl79AxfDs4[/URL]
[03:48:27]  Debug: SM User williamle12 created session with the bot
[03:48:27]  Debug: AdminCheck called!
[03:48:27]  Debug: QC GetClientServerGroups called
[03:48:28]  Debug: AF stop old
[03:48:28]  Debug: AF ar start: Youtube ID:cQl79AxfDs4
[03:48:28]  Debug: AF set volume: 10
[03:52:28]Warning: SongStoppedHook could not play Next: No next song could be played

**Comment by Splamy** [comment]
This is strange, this seems to happen more frequently in the last time with different users.
At the moment I'm trying to rework the client backend since despite all my effords the code got a bit spaghettie. I really hope this will fix some of the problems users have at the moment, but I cant guarantee anything. If it persists afterwards I'll have to expand the bugfinder branch and/or get in contact with soemone to debug on the remote server.

**Comment by lima12** [comment]
nvm i have re-build it and it work but now i face the biggest problem 
how to install youtube-dl ...

**Comment by lima12** [comment]
btw is bot play music to every one or he just whisper to the one who command he play the song ?

**Comment by Splamy** [comment]
he whispers to the channel where the one was who wrote him

**Comment by Splamy** [comment]
regarding youtube-dl, install python, download the ytdl repo from github and set the path in the config

**Comment by lima12** [comment]
OK :D got it working ! thank you very much <3 you da real mvp

**Comment by Splamy** [comment]
nice, please close the issue when you have no questions or open an other one if something else doesent work
