### ISSUE TITLE
Error upon starting audiobot

### ISSUE THREAD

**Issue by Camando** [Splamy/TS3AudioBot#63]
[23:53:52]   Info: [============ TS3AudioBot started =============]
[23:53:52]   Info: [=== Date:           Monday, April 10, 2017 ===]
[23:53:52]   Info: [=== Time:                      11:53:52 PM ===]
[23:53:52]   Info: [==============================================]
[23:53:52]   Info: [============ Initializing Commands ===========]
[23:53:52]   Info: [============ Initializing Modules ============]
[23:53:52]   Info: [=========== Initializing Factories ===========]
[23:53:52]   Info: [=========== Registering callbacks ============]
[23:53:52]   Info: [================= Finalizing =================]
[23:53:52]   Info: [============== Connected & Done ==============]
[23:53:52]  Error: Critical program failure!. Exception:
 MSG: DEF length 44 object truncated by 16
TYPE:Asn1ParsingException
STACK:   at Org.BouncyCastle.Asn1.BerTaggedObjectParser.ToAsn1Object()
   at Org.BouncyCastle.Asn1.Asn1StreamParser.ReadVector()
   at Org.BouncyCastle.Asn1.Asn1StreamParser.ReadTaggedObject(Boolean constructed, Int32 tag)
   at Org.BouncyCastle.Asn1.Asn1InputStream.BuildObject(Int32 tag, Int32 tagNo, Int32 length)
   at Org.BouncyCastle.Asn1.Asn1InputStream.ReadObject()
   at Org.BouncyCastle.Asn1.Asn1Object.FromByteArray(Byte[] data)
   at TS3Client.Full.Ts3Crypt.ImportPrivateKey(Byte[] asnByteArray) in C:\Users\Administrator.GREENROOMGAMING\Downloads\TS3AudioBot-master\TS3AudioBot-master\TS3Client\Full\Ts3Crypt.cs:line 113
   at TS3Client.Full.Ts3Crypt.LoadIdentity(String key, UInt64 keyOffset, UInt64 lastCheckedKeyOffset) in C:\Users\Administrator.GREENROOMGAMING\Downloads\TS3AudioBot-master\TS3AudioBot-master\TS3Client\Full\Ts3Crypt.cs:line 82
   at TS3AudioBot.Ts3Full.Connect() in C:\Users\Administrator.GREENROOMGAMING\Downloads\TS3AudioBot-master\TS3AudioBot-master\TS3AudioBot\Ts3Full.cs:line 93
   at TS3AudioBot.MainBot.Run() in C:\Users\Administrator.GREENROOMGAMING\Downloads\TS3AudioBot-master\TS3AudioBot-master\TS3AudioBot\MainBot.cs:line 210
   at TS3AudioBot.MainBot.Main(String[] args) in C:\Users\Administrator.GREENROOMGAMING\Downloads\TS3AudioBot-master\TS3AudioBot-master\TS3AudioBot\MainBot.cs:line 54

[23:53:52]   Info: Exiting...
[23:53:52]   Info: Closing Mediaplayer...
[23:53:52]  Debug: AF stop old
[23:53:52]Warning: Internal error (me==null)
[23:53:52]   Info: Closing QueryConnection...
[23:53:52]   Info: Closing QueryConnection...

Any help would be appreciated

**Comment by Camando** [comment]
Any help would be appreciated
