### ISSUE TITLE
Events doesnt work anymore?

### ISSUE THREAD

**Issue by marv-th** [Splamy/TS3AudioBot#635]
Hello. I upgraded to the newest Version of the TS3AB. On Visual Studio and in the log of the Bot they could not use my selfwrite plugin anymore. 
Where is the OnClientConnect Event? It doesn't work anymore and i cant find it in the Ts3FullEvents.cs file. Is there a new syntax or new name? Than can you tell it?

Log (if needed):
```
2019-09-14 18:16:45.2689| INFO|1|Bot.OnMessageReceived User Marvin requested: !plugin load 2
2019-09-14 18:16:45.2689|ERROR|1|Plugin.StartInternal Plugins and Factories needs a parameterless constructor.
System.MissingMethodException: Method not found: 'Void TS3AudioBot.Ts3Client.add_OnClientConnect(System.EventHandler`1<TS3Client.Messages.ClientEnterView>)'.
   at ClassLibrary3.WelcomeMessage_Bot.Initialize()
   at TS3AudioBot.Plugins.Plugin.StartInternal(Bot bot) in C:\projects\ts3audiobot\TS3AudioBot\Plugins\Plugin.cs:line 384
2019-09-14 18:16:45.2689| WARN|1|Plugin.SaveDisposePlugin Plugin 'WelcomeMessage_Bot (BotPlugin)' threw an exception while disposing
System.MissingMethodException: Method not found: 'Void TS3AudioBot.Ts3Client.remove_OnClientConnect(System.EventHandler`1<TS3Client.Messages.ClientEnterView>)'.
   at ClassLibrary3.WelcomeMessage_Bot.Dispose()
   at TS3AudioBot.Plugins.Plugin.SaveDisposePlugin(ICorePlugin plugin) in C:\projects\ts3audiobot\TS3AudioBot\Plugins\Plugin.cs:line 501
2019-09-14 18:16:45.3164| INFO||WebApi.ProcessApiV1Call ::ffff:51.89.27.57 Requested: /api/bot/use/1/(/song/info)
2019-09-14 18:16:46.2521| INFO||WebApi.ProcessApiV1Call ::ffff:51.89.27.57 Requested: /api/bot/use/1/(/song/info)
```

**Comment by Splamy** [comment]
Use the `OnEachClientEnterView` event (or `OnClientEnterView` if you want the events grouped in a single message for any reason) in the `Ts3FullClient` class instead.
You can check out all available events here: https://github.com/Splamy/TS3AudioBot/blob/develop/TS3Client/Generated/Ts3FullEvents.cs#L35-L178 which gets autogenerated from our declaration file.

**Comment by marv-th** [comment]
Thanks. it works 😊
