### ISSUE TITLE
System.InvalidOperationException (develop_dotnet_core 0.10.0-alpha.170)

### ISSUE THREAD

**Issue by Vafin84** [Splamy/TS3AudioBot#640]
**Describe the bug**
This error often appears

**To Reproduce**
Appears mostly when using the command !play

**Version**
develop_dotnet_core 0.10.0-alpha.170

**Platform**
.NET Core SDK (reflecting any global.json):
 Version:   2.2.401
 Commit:    729b316c13

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         debian.9-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.401/

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.401 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
**Log**
```
2019-09-18 21:47:58.1453| INFO|2|PlayManager.StopInternal Song queue ended: No next song could be played.
2019-09-18 21:48:28.4033| WARN||FfmpegInstance.ReadStreamLoop Waiting for ffmpeg
System.InvalidOperationException: StandardIn has not been redirected.
   at System.Diagnostics.Process.get_StandardInput()
   at TS3AudioBot.Audio.FfmpegProducer.FfmpegInstance.ReadStreamLoop() in C:\projects\ts3audiobot\TS3AudioBot\Audio\FfmpegProducer.cs:line 415
2019-09-18 21:49:21.7134| INFO|2|Bot.OnMessageReceived User Support requested: !search from youtube сектор газа
2019-09-18 21:49:38.6825| INFO|2|Bot.OnMessageReceived User Support requested: !select  all
2019-09-18 21:50:04.7607| INFO|2|Bot.OnMessageReceived User Support requested: !select 0
2019-09-18 21:50:13.4153| WARN||FfmpegInstance.ReadStreamLoop Stream read/write error
System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ConnectionCloseReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.HttpContentReadStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at TS3AudioBot.Audio.FfmpegProducer.FfmpegInstance.ReadStreamLoop() in C:\projects\ts3audiobot\TS3AudioBot\Audio\FfmpegProducer.cs:line 399
2019-09-18 21:50:14.0636| INFO|2|PlayManager.StopInternal Song queue ended: No next song could be played.
2019-09-18 21:50:44.3393| WARN||FfmpegInstance.ReadStreamLoop Waiting for ffmpeg
System.InvalidOperationException: StandardIn has not been redirected.
   at System.Diagnostics.Process.get_StandardInput()
   at TS3AudioBot.Audio.FfmpegProducer.FfmpegInstance.ReadStreamLoop() in C:\projects\ts3audiobot\TS3AudioBot\Audio\FfmpegProducer.cs:line 415
2019-09-18 21:53:31.7436| INFO|2|Bot.OnMessageReceived User Support requested: !search from youtube Король и Шут
2019-09-18 21:53:49.1364| INFO|2|Bot.OnMessageReceived User Support requested: !select 0
2019-09-18 21:53:49.6650| WARN|2|WebWrapper.ToLoggedError Web error: [403] Forbidden
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.GetResponse()
   at TS3AudioBot.Helper.WebWrapper.GetResponse(Uri link, Action`1 body, TimeSpan timeout) in C:\projects\ts3audiobot\TS3AudioBot\Helper\WebWrapper.cs:line 68
2019-09-18 21:53:54.1712| WARN||FfmpegInstance.ReadStreamLoop Stream read/write error
System.IO.IOException: Unable to read data from the transport connection: Operation canceled. ---> System.Net.Sockets.SocketException: Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ConnectionCloseReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.HttpContentReadStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at TS3AudioBot.Audio.FfmpegProducer.FfmpegInstance.ReadStreamLoop() in C:\projects\ts3audiobot\TS3AudioBot\Audio\FfmpegProducer.cs:line 399
```

**Comment by Splamy** [comment]
This only comes up because ffmpeg sometimes is a bit slow to respond when starting. I added it as a warning to see if anything bad is happening; but since everything seems fine I'll move to to the debug logs to not cause unecessary log
