### ISSUE TITLE
Can not find any url [Windows]

### ISSUE THREAD

**Issue by marv-th** [Splamy/TS3AudioBot#646]
I try something on Windows but it could not play any url like an stream url. Can u tell me what to do or link an issue with this problem?

**Version**
Version: 0.10.0-alpha.172
Branch: develop
CommitHash: 6e729ec0ae5c3440cf1af67414dc63f0b13d8653

**Platform**
Windows 10

**Console**
```
22:11:30.7194| INFO|| ::ffff:51.89.27.57 Requested: /api/bot/use/1/(/song/info)
22:11:30.7836| INFO|1| User Marvin requested: !play [URL]http://streams.bigfm.de/nitroxedmilr-128-mp3[/URL]
22:11:31.4046| WARN|1| Ffmpeg could not be found (Das System kann die angegebene Datei nicht finden)
22:11:31.4455|ERROR|1| Error return from player: Ffmpeg could not be found (Das System kann die angegebene Datei nicht finden)
22:11:31.4455| WARN|| Stream read/write error
22:11:31.7056| INFO|| ::ffff:51.89.27.57 Requested: /api/bot/use/1/(/song/info)
```

**Log**
```
2019-09-20 22:11:29.6992| INFO||WebApi.ProcessApiV1Call ::ffff:51.89.27.57 Requested: /api/bot/use/1/(/song/info)
2019-09-20 22:11:30.7194| INFO||WebApi.ProcessApiV1Call ::ffff:51.89.27.57 Requested: /api/bot/use/1/(/song/info)
2019-09-20 22:11:30.7836| INFO|1|Bot.OnMessageReceived User Marvin requested: !play [URL]http://streams.bigfm.de/nitroxedmilr-128-mp3[/URL]
2019-09-20 22:11:31.4046| WARN|1|FfmpegProducer.StartFfmpegProcessInternal Ffmpeg could not be found (Das System kann die angegebene Datei nicht finden)
System.ComponentModel.Win32Exception (0x80004005): Das System kann die angegebene Datei nicht finden
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at TS3AudioBot.Audio.FfmpegProducer.StartFfmpegProcessInternal(FfmpegInstance instance, String arguments)
2019-09-20 22:11:31.4455|ERROR|1|PlayManager.StartResource Error return from player: Ffmpeg could not be found (Das System kann die angegebene Datei nicht finden)
2019-09-20 22:11:31.4455| WARN||FfmpegInstance.ReadStreamLoop Stream read/write error
System.IO.IOException: Unable to read data from the transport connection: Ein Blockierungsvorgang wurde durch einen Aufruf von WSACancelBlockingCall unterbrochen. ---> System.Net.Sockets.SocketException: Ein Blockierungsvorgang wurde durch einen Aufruf von WSACancelBlockingCall unterbrochen
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at TS3AudioBot.Audio.FfmpegProducer.FfmpegInstance.ReadStreamLoop()
2019-09-20 22:11:31.7056| INFO||WebApi.ProcessApiV1Call ::ffff:51.89.27.57 Requested: /api/bot/use/1/(/song/info)
2019-09-20 22:11:32.7046| INFO||WebApi.ProcessApiV1Call ::ffff:51.89.27.57 Requested: /api/bot/use/1/(/song/info)
2019-09-20 22:11:33.7155| INFO||WebApi.ProcessApiV1Call ::ffff:51.89.27.57 Requested: /api/bot/use/1/(/song/info)
```

**Comment by Splamy** [comment]
> Ffmpeg could not be found

you havn't downloaded the ffmpeg.exe or didn't properly specify the path to it

**Comment by marv-th** [comment]
```
13:06:13.7292| INFO|| ::ffff:51.89.27.57 Requested: /api/bot/use/1/(/song/info)
13:06:14.6824| INFO|| ::ffff:51.89.27.57 Requested: /api/bot/use/1/(/volume/10/)
13:06:14.8023| INFO|| ::ffff:51.89.27.57 Requested: /api/bot/use/1/(/song/info)
13:06:14.9353| WARN|1| Ffmpeg could not be found (Das System kann die angegebene Datei nicht finden)
13:06:14.9613| WARN|| Stream read/write error
13:06:14.9613|ERROR|1| Error return from player: Ffmpeg could not be found (Das System kann die angegebene Datei nicht finden)
13:06:15.0965| INFO|| ::ffff:51.89.27.57 Requested: /api/bot/use/1/(/clean)
13:06:15.1625| INFO|| ::ffff:51.89.27.57 Requested: /api/bot/use/1/(/song/info)
13:06:15.5243| INFO|| ::ffff:51.89.27.57 Requested: /api/bot/use/1/(/song/info)
13:06:15.7156| INFO|| ::ffff:51.89.27.57 Requested: /api/bot/use/1/(/song/info)
```

i tried all.. i had already specific the path to the ffmpeg.exe and the console prints out an error

**Comment by marv-th** [comment]
to specify the path doesnt work but placing the exe in the ts3ab folder works

**Comment by Splamy** [comment]
I'm pretty sure specifying the path also works, because that's how it's currently running on my windows pc here.

**Comment by marv-th** [comment]
Maybe i had a mistake in writing slash or backslashes in the path.. i will try again in the future.
