### ISSUE TITLE
Cant play streams

### ISSUE THREAD

**Issue by Onyxzium** [Splamy/TS3AudioBot#676]
Hey I bins again I can not play any more streams, whether ILoveRadio or anything else is what is YouTube.
Error: Could not load. (media: Unknown request error.)

**Comment by Splamy** [comment]
Some more information (Use our issue template), like ts3ab version, log, etc

**Comment by KD148** [comment]
Same issue.

Version: 0.10.0-alpha.168/develop/e1457917

log:
`TS3AudioBot.CommandSystem.CommandException: Load failed. (media: Unknown request error.)
   at TS3AudioBot.Helper.Util.UnwrapThrow(E`1 r) in D:\TS3AB\TS3AudioBot\Helper\Util.cs:line 110
   at TS3AudioBot.MainCommands.CommandPlay(PlayManager playManager, InvokerData invoker, String url) in D:\TS3AB\TS3AudioBot\MainCommands.cs:line 1097
--- End of stack trace from previous location where exception was thrown ---
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.ExecuteFunction(Object[] parameters) in D:\TS3AB\TS3AudioBot\CommandSystem\Commands\FunctionCommand.cs:line 70
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes) in D:\TS3AB\TS3AudioBot\CommandSystem\Commands\FunctionCommand.cs:line 197
   at TS3AudioBot.CommandSystem.BotCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes) in D:\TS3AB\TS3AudioBot\CommandSystem\BotCommand.cs:line 119
   at TS3AudioBot.CommandSystem.Commands.OverloadedFunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes) in D:\TS3AB\TS3AudioBot\CommandSystem\Commands\OverloadedFunctionCommand.cs:line 88
   at TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes) in D:\TS3AB\TS3AudioBot\CommandSystem\Commands\CommandGroup.cs:line 70
   at TS3AudioBot.CommandSystem.Commands.RootCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes) in D:\TS3AB\TS3AudioBot\CommandSystem\Commands\RootCommand.cs:line 33
   at TS3AudioBot.CommandSystem.Commands.AppliedCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes) in D:\TS3AB\TS3AudioBot\CommandSystem\Commands\AppliedCommand.cs:line 31
   at TS3AudioBot.CommandSystem.Commands.LazyCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes) in D:\TS3AB\TS3AudioBot\CommandSystem\Commands\LazyCommand.cs:line 33
   at TS3AudioBot.MainCommands.CommandXecute(ExecutionInformation info, IReadOnlyList`1 arguments) in D:\TS3AB\TS3AudioBot\MainCommands.cs:line 1733
--- End of stack trace from previous location where exception was thrown ---
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.ExecuteFunction(Object[] parameters) in D:\TS3AB\TS3AudioBot\CommandSystem\Commands\FunctionCommand.cs:line 70
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes) in D:\TS3AB\TS3AudioBot\CommandSystem\Commands\FunctionCommand.cs:line 202
   at TS3AudioBot.CommandSystem.BotCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes) in D:\TS3AB\TS3AudioBot\CommandSystem\BotCommand.cs:line 119
   at TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes) in D:\TS3AB\TS3AudioBot\CommandSystem\Commands\CommandGroup.cs:line 70
   at TS3AudioBot.CommandSystem.Commands.RootCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes) in D:\TS3AB\TS3AudioBot\CommandSystem\Commands\RootCommand.cs:line 33
   at TS3AudioBot.CommandSystem.Commands.AppliedCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes) in D:\TS3AB\TS3AudioBot\CommandSystem\Commands\AppliedCommand.cs:line 31
   at TS3AudioBot.CommandSystem.XCommandSystem.Execute(ExecutionInformation info, String command, IReadOnlyList`1 returnTypes) in D:\TS3AB\TS3AudioBot\CommandSystem\XCommandSystem.cs:line 88
   at TS3AudioBot.CommandSystem.XCommandSystem.Execute(ExecutionInformation info, String command) in D:\TS3AB\TS3AudioBot\CommandSystem\XCommandSystem.cs:line 81
   at TS3AudioBot.Bot.<>c__DisplayClass40_0.<CallScript>b__0() in D:\TS3AB\TS3AudioBot\Bot.cs:line 426
   at TS3AudioBot.Bot.TryCatchCommand(ExecutionInformation info, Boolean answer, Action action) in D:\TS3AB\TS3AudioBot\Bot.cs:line 498`

**Comment by Splamy** [comment]
Any example?
