### ISSUE TITLE
Branch: develop eba64d4c - The playlist error.

### ISSUE THREAD

**Issue by xpiREC** [Splamy/TS3AudioBot#683]
**Describe the bug**
The playlist is inserted but playback is not possible receives the following result.

**To Reproduce**
```
!list import 1 <url>
!list play 1
```

**Version**

- Debian and Windows  - `0.11.0-alpha.34/develop/eba64d4c`

**Runtime**

- Debian - `.NET Core (3.0.0) ServerGC:False GC:Batch`
- Windows - `.NET Framework 4.0.30319.42000 ServerGC:False GC:SustainedLowLatency`

**Platform**

- Debian GNU/Linux 9 (stretch) (64bit)
- Windows 10 Home (last)

**Log**

```
04:53:46.1592|ERROR|0| Unexpected command error: MSG: Object reference not set to an instance of an object.
TYPE:NullReferenceException
STACK:   at TS3AudioBot.Audio.PlayManager.UpdateItem(InvokerData invoker, PlaylistItem item)
   at TS3AudioBot.Audio.PlayManager.<>c__DisplayClass35_0.<Play>b__0(PlaylistItem x)
   at System.Linq.Enumerable.SelectListPartitionIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at TS3AudioBot.Playlists.Playlist.AddRange(IEnumerable`1 songs)
   at TS3AudioBot.Playlists.PlaylistManager.<>c__DisplayClass31_0.<Queue>b__0(Playlist mix)
   at TS3AudioBot.Playlists.PlaylistManager.ModifyPlaylist(String listId, Action`1 action)
   at TS3AudioBot.Playlists.PlaylistManager.Queue(IEnumerable`1 items)
   at TS3AudioBot.Audio.PlayManager.Play(InvokerData invoker, IEnumerable`1 items, Int32 index)
   at TS3AudioBot.MainCommands.CommandListPlayInternal(PlaylistManager playlistManager, PlayManager playManager, InvokerData invoker, String listId, Nullable`1 index)
--- End of stack trace from previous location where exception was thrown ---
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.ExecuteFunction(Object[] parameters)
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes)
   at TS3AudioBot.CommandSystem.BotCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes)
   at TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes)
   at TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes)
   at TS3AudioBot.CommandSystem.Commands.RootCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes)
   at TS3AudioBot.CommandSystem.Commands.AppliedCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes)
   at TS3AudioBot.CommandSystem.XCommandSystem.Execute(ExecutionInformation info, String command, IReadOnlyList`1 returnTypes)
   at TS3AudioBot.CommandSystem.XCommandSystem.ExecuteCommand(ExecutionInformation info, String command)
   at TS3AudioBot.Bot.<>c__DisplayClass43_0.<CallScript>b__0()
   at TS3AudioBot.Bot.TryCatchCommand(ExecutionInformation info, Boolean answer, Action action)

**Comment by Splamy** [comment]
Thanks for the notify; it's fixed.
