### ISSUE TITLE
Unhandled Exception while starting the audiobot.

### ISSUE THREAD

**Issue by BSzmiszke** [Splamy/TS3AudioBot#699]
**Describe the problem**
When I start the audiobot for the first time I get this error. I've tried running the master build as well, doesn't work as well. This is a screen shot of the alpha build.
![](https://i.imgur.com/CXN0NHk.png)

**To Reproduce**
1. wget https://splamy.de/api/nightly/ts3ab/develop_dotnet_core/download -O TS3AudioBot.zip
2. unzip TS3AudioBot.zip -d TS3AudioBot
3. cd TS3AudioBot/
4. dotnet TS3AudioBot.dll

**System Information**
- **Platform**: Ubuntu 18.04
  
- **.NET version**: 2.2.402

- **Which commit did you download**: (or on prebuilt: `dotnet TS3AudioBot.exe -V`)  
Version: 0.11.0-alpha.38
Branch: develop
CommitHash: b6a68d48cce4fce3e087fe1cb430e525152212db

**Additional Logs, Exceptions, etc**
When applicable try to add relevant log excerpts here.

```14:49:44.0341| INFO|| [============ TS3AudioBot started =============]

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Globalization.CalendarData.NormalizeDatePattern(String input)
   at System.Globalization.CalendarData.LoadCalendarDataFromSystem(String localeName, CalendarId calendarId)
   at System.Globalization.CalendarData..ctor(String localeName, CalendarId calendarId, Boolean bUseUserOverrides)
   at System.Globalization.CultureData.GetCalendar(CalendarId calendarId)
   at System.Globalization.CultureData.DateSeparator(CalendarId calendarId)
   at System.Globalization.DateTimeFormatInfo.InitializeOverridableProperties(CultureData cultureData, CalendarId calendarId)
   at System.Globalization.CultureInfo.get_DateTimeFormat()
   at System.Globalization.DateTimeFormatInfo.get_CurrentInfo()
   at System.DateTimeFormat.Format(DateTime dateTime, String format, IFormatProvider provider, TimeSpan offset)   at System.DateTimeFormat.Format(DateTime dateTime, String format, IFormatProvider provider)
   at TS3AudioBot.Setup.LogHeader() in C:\projects\ts3audiobot\TS3AudioBot\Setup.cs:line 164
   at TS3AudioBot.Core.Main(String[] args) in C:\projects\ts3audiobot\TS3AudioBot\Core.cs:line 49
Aborted (core dumped)

**Comment by LosTigeros** [comment]
I'm pretty sure it's caused by invalid wrong locale on the system.
Sometimes they're just set to `C.UTF-8` which may cause null while normalizing the date.

Try using:
```
sudo update-locale LANG="en_US.UTF-8"
sudo dpkg-reconfigure locales
```
to set your locale to proper `UTF-8` `en_US` format.

This should solve your problem.

To dev:
I think you should check for locale first and just throw out an info to users so they can reconfigure them properly.

**Comment by BSzmiszke** [comment]
> Try using:
> 
> ```
> sudo update-locale LANG="en_US.UTF-8"
> sudo dpkg-reconfigure locales
> ```

Thanks man, I wasn't expecting such fast reply, wow.
