### ISSUE TITLE
Tickworker

### ISSUE THREAD

**Issue by MoroseCorpse** [Splamy/TS3AudioBot#716]
Well, I have always worked with a timer in my plugin. However, there was a problem there that it somehow hangs. Example:

```cs
        public void SetTimer()
        {            
            aTimer = new System.Timers.Timer(10000);
            aTimer.Elapsed += OnTimedEvent;
            aTimer.AutoReset = true;
            aTimer.Enabled = true;
        }
        public void OnTimedEvent()
        {
        ...
        }

```
Now I found the tick worker and wanted to use it instead. But there I get the following problem again and again:
```2020-01-16 17:20:31.3131|FATAL||Core.ExceptionHandler Critical program failure!
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at SupportBot.SupportBot.OnTimedEvent()
   at TS3AudioBot.Helper.TickPool.Tick() in C:\projects\ts3audiobot\TS3AudioBot\Helper\TickPool.cs:line 82
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

My code:

```cs
        public void Initialize()
        {
            TickPool.RegisterTick(OnTimedEvent, TimeSpan.FromSeconds(10), true);
        }

        public void OnTimedEvent()
        {
                string BotID = ConfBot.Name;

                foreach (Dictionary<String, String> channelinfos in finalArray[BotID].Values)
                {
                    var stopWatch2 = new Stopwatch();
                    stopWatch2.Start();

                    if (setupArray[BotID]["flood_system"].Equals("1"))
                    {
                        if (!string.IsNullOrEmpty(setupArray[BotID]["flood_points_per_10_sec"]))
                        {
                            foreach (var user in floodArray[BotID])
                            {
                                if (floodArray[BotID][user.Key] > 0)
                                {
                                    int flootpoints = (user.Value - int.Parse(setupArray[BotID]["flood_points_per_10_sec"]));
                                    if (flootpoints < 0)
                                    {
                                        floodArray[BotID][user.Key] = 0;
                                    }
                                    else
                                    {
                                        floodArray[BotID][user.Key] = flootpoints;
                                    }
                                }
                            }
                        }
                    }
               }
        }
```

How can I fix this or is there maybe a better way to run a timer or something that permanently decreases a value in a dictionary?

My goal is, as you can see in the code, that every 10 seconds the flootpoints are reduced by the configured number of users.

**Comment by Splamy** [comment]
The exception is thrown when two threads simultaneously try to modify a dictionary.
The default `Dictionary` class from C# is not threadsafe; instead you should use `ConcurrentDictionary` (in `System.Collections.Concurrent`).

**Comment by MoroseCorpse** [comment]
Ok thanks :)
