### ISSUE TITLE
Output line number in plugin on error

### ISSUE THREAD

**Issue by MoroseCorpse** [Splamy/TS3AudioBot#739]
I would like to have the line number printed out if an error occurs in my plugin.

I have already tried to display this in ``NLog.config`` with ``${callsite-linenumber}``. But unfortunately it only prints a 0 for plugins. For internal TS3Audiobot stuff it did output lines.

Is there a way to do this without inserting try/catch methods everywhere? So that it always prints a line number on every error

**Comment by Splamy** [comment]
I think that should be possible with the roslyn c# compiler. I'll mark this as an enhancement and try when I get to.

**Comment by MoroseCorpse** [comment]
Ok, is there a way I can get the line number already printed without having to wait for an update?

**Comment by Splamy** [comment]
https://github.com/Splamy/TS3AudioBot/blob/develop/TS3AudioBot/Plugins/Plugin.cs#L204-L211

Replace this lines with that and recompile:

```cs
				using (var ms_assembly = new MemoryStream())
				using (var ms_pdb = new MemoryStream())
				{
					var result = compilation.Emit(ms_assembly, ms_pdb,
						options: new Microsoft.CodeAnalysis.Emit.EmitOptions()
							.WithDebugInformationFormat(Microsoft.CodeAnalysis.Emit.DebugInformationFormat.PortablePdb)
						);

					if (result.Success)
					{
						ms_assembly.Seek(0, SeekOrigin.Begin);
						ms_pdb.Seek(0, SeekOrigin.Begin);
						var assembly = Assembly.Load(ms_assembly.ToArray(), ms_pdb.ToArray());
```

**Comment by MoroseCorpse** [comment]
I have tried that now and still no line is output when I provoke an error. Is there anything else I need to consider?
I'm not necessarily sure if I recompiled the bot correctly

**Comment by Splamy** [comment]
That's all I changed and it worked for me. Check that your build finishes without errors
```
System.Exception: Exception of type 'System.Exception' was thrown.
   at Example1.Example1.QueryConnection_OnClientConnect(Object sender, ClientEnterView e) in :line 15
   at TSLib.Full.TsFullClient.InvokeEvent(LazyNotification lazyNotification) in E:\_Projects\git\TS3AudioBot\TSLib\Full\TsFullClient.gen.cs:line 544
```

**Comment by MoroseCorpse** [comment]
Ok so there were no real mistakes. Here's my log:
```
1>------ Neues Erstellen gestartet: Projekt: TS3Client, Konfiguration: Debug Any CPU ------
1>TS3Client -> D:\Users\Moritz\Desktop\Development\TS3AudioBot-master\TS3AudioBot-master\TS3Client\bin\Debug\net472\TS3Client.dll
1>TS3Client -> D:\Users\Moritz\Desktop\Development\TS3AudioBot-master\TS3AudioBot-master\TS3Client\bin\Debug\netcoreapp2.2\TS3Client.dll
1>TS3Client -> D:\Users\Moritz\Desktop\Development\TS3AudioBot-master\TS3AudioBot-master\TS3Client\bin\Debug\netcoreapp3.0\TS3Client.dll
1>TS3Client -> D:\Users\Moritz\Desktop\Development\TS3AudioBot-master\TS3AudioBot-master\TS3Client\bin\Debug\netstandard2.0\TS3Client.dll
2>------ Neues Erstellen gestartet: Projekt: TS3AudioBot, Konfiguration: Debug Any CPU ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3277: Es wurden Konflikte zwischen verschiedenen Versionen von "System.Security.Cryptography.Cng" gefunden, die nicht gelöst werden konnten. Diese Verweiskonflikte werden im Buildprotokoll aufgelistet, wenn die Protokollausführlichkeit auf "Ausführlich" festgelegt ist.
2>TS3AudioBot -> D:\Users\Moritz\Desktop\Development\TS3AudioBot-master\TS3AudioBot-master\TS3AudioBot\bin\Debug\net472\TS3AudioBot.exe
2>TS3AudioBot -> D:\Users\Moritz\Desktop\Development\TS3AudioBot-master\TS3AudioBot-master\TS3AudioBot\bin\Debug\netcoreapp3.0\TS3AudioBot.dll
2>Erstellen des Projekts TS3AudioBot.csproj beendet.
2>TS3AudioBot -> D:\Users\Moritz\Desktop\Development\TS3AudioBot-master\TS3AudioBot-master\TS3AudioBot\bin\Debug\netcoreapp2.2\TS3AudioBot.dll
2>TS3AudioBot -> D:\Users\Moritz\Desktop\Development\TS3AudioBot-master\TS3AudioBot-master\TS3AudioBot\bin\Debug\netstandard2.0\TS3AudioBot.dll
3>------ Neues Erstellen gestartet: Projekt: TS3ABotUnitTests, Konfiguration: Debug Any CPU ------
3>TS3ABotUnitTests -> D:\Users\Moritz\Desktop\Development\TS3AudioBot-master\TS3AudioBot-master\TS3ABotUnitTests\bin\Debug\netcoreapp2.2\TS3ABotUnitTests.dll
3>TS3ABotUnitTests -> D:\Users\Moritz\Desktop\Development\TS3AudioBot-master\TS3AudioBot-master\TS3ABotUnitTests\bin\Debug\net472\TS3ABotUnitTests.dll
========== Alles neu erstellen: 3 erfolgreich, 0 fehlerhaft, 0 übersprungen ==========
```

I was also not quite sure which file to use now, because so many TS3Clients.dll and TS3Audiobot.exe/TS3Audiobot.dll files were created. 

Finally, new files are created in the following folder paths and this confuses me quite a bit:
```
TS3AudioBot-master\TS3Client\bin\Debug\net472
TS3AudioBot-master\TS3Client\bin\Debug\netcoreapp2.2
TS3AudioBot-master\TS3Client\bin\Debug\netcoreapp3.0
TS3AudioBot-master\TS3Client\bin\Debug\netstandard2.0
TS3AudioBot-master\TS3AudioBot\bin\Debug\net472
TS3AudioBot-master\TS3AudioBot\bin\Debug\netcoreapp2.2
TS3AudioBot-master\TS3AudioBot\bin\Debug\netcoreapp3.0
TS3AudioBot-master\TS3AudioBot\bin\Debug\netstandard2.0
```

Which of these paths should I choose if I use the ``master_dotnet_core`` version?

Does it also play a role which file type I use? So I let the plugins compile in dll files

I have also already seen that you have already put it into the latest developer version, but unfortunately you have renamed the TS3Client to TSLib and changed all variable types. So I can't use this version for now, because our users are still on the master version

**Comment by Splamy** [comment]
`TS3Client/*` is only the library. You want the binary of the TS3AudioBot
Which of those frameworks you have to pick depends on what framework you installed/are using.
Since you are using `master_dotnet_core` from our nighly then pick netcoreapp2.2.
(If you are using mono pick net472. If you use dotnet core 2.X / 3.X pick netcoreapp2.2 / netcoreapp3.0 respectively.)

> Does it also play a role which file type I use? So I let the plugins compile in dll files

dll is the correct build format. You just have to make sure that you also target the correct framework with your plugin.
The easiest is to target `netstandard2.0` this makes the library compatible for all framworks net47/netcore2/3

> I have also already seen that you have already put it into the latest developer version, but unfortunately you have renamed the TS3Client to TSLib and changed all variable types. So I can't use this version for now, because our users are still on the master version

Yeah, that's one of the drawback with raw plugins, internal changes can easily break them. I'm planning on adding a js plugin interface in the far future which should be more stable and don't change evey second commit; but I'm not announcing nor promising anything right now to not create any expectations or hype for that feature

**Comment by MoroseCorpse** [comment]
Ok now I have this error:
```
2020-03-03 18:28:34.9989|ERROR|0|Plugin.InitializeAssembly InitializeAssembly failed: Could not load file or assembly 'TS3AudioBot, Version=0.10.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

System.IO.FileNotFoundException: Could not load file or assembly 'TS3AudioBot, Version=0.10.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'TS3AudioBot, Version=0.10.0.0, Culture=neutral, PublicKeyToken=null'
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken caCtorToken, MetadataImport& scope, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.RuntimeType.GetCustomAttributes(Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
   at System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](MemberInfo element)
   at TS3AudioBot.Plugins.Plugin.<>c.<InitializeAssembly>b__47_2(Type t)
   at System.Linq.Enumerable.WhereArrayIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at TS3AudioBot.Plugins.Plugin.InitializeAssembly(Assembly assembly)


2020-03-03 18:28:35.0096|ERROR|0|Plugin.InitializeAssembly InitializeAssembly failed: Could not load file or assembly 'TS3AudioBot, Version=0.10.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

System.IO.FileNotFoundException: Could not load file or assembly 'TS3AudioBot, Version=0.10.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'TS3AudioBot, Version=0.10.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at TS3AudioBot.Plugins.Plugin.InitializeAssembly(Assembly assembly)


2020-03-03 18:28:35.0096|ERROR|0|Plugin.InitializeAssembly InitializeAssembly failed: Could not load file or assembly 'TS3AudioBot, Version=0.10.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

System.IO.FileNotFoundException: Could not load file or assembly 'TS3AudioBot, Version=0.10.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'TS3AudioBot, Version=0.10.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at TS3AudioBot.Plugins.Plugin.InitializeAssembly(Assembly assembly)


```

**Comment by Splamy** [comment]
If you have any dependencies, you'll have to add them into the plugins folder.
Did you reference to `netstandard2.0\TS3AudioBot.dll` in your plugin?

**Comment by MoroseCorpse** [comment]
Okay, I found the mistake. I removed the other plugins that do not use the new TS3Audiobot.dll and TS3Client.dll from the plugins folder.

But now there are no more errors and I still don't get any lines. The following log shows a provoked error:

```
2020-03-05 16:37:35.9015|ERROR|0|Plugin.StartInternal Plugin 'SupportBot (BotPlugin)' failed to load: The given key 'test' was not present in the dictionary..
System.Collections.Generic.KeyNotFoundException: The given key 'test' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at SupportBot.SupportBot.Initialize()
   at TS3AudioBot.Plugins.Plugin.StartInternal(Bot bot) in D:\Users\Moritz\Desktop\Development\TS3AudioBot-master (1)\TS3AudioBot-master\TS3AudioBot\Plugins\Plugin.cs:line 389
2020-03-05 16:37:35.9097| WARN|0|Plugin.SaveDisposePlugin Plugin 'SupportBot (BotPlugin)' threw an exception while disposing
System.NullReferenceException: Object reference not set to an instance of an object.
   at SupportBot.SupportBot.Dispose()
   at TS3AudioBot.Plugins.Plugin.SaveDisposePlugin(ICorePlugin plugin) in D:\Users\Moritz\Desktop\Development\TS3AudioBot-master (1)\TS3AudioBot-master\TS3AudioBot\Plugins\Plugin.cs:line 506
```
My goal is to get exactly the same line information as this line says, but for my plugins:
```
at TS3AudioBot.Plugins.Plugin.StartInternal(Bot bot) in D:\Users\Moritz\Desktop\Development\TS3AudioBot-master (1)\TS3AudioBot-master\TS3AudioBot\Plugins\Plugin.cs:line 389
```


The only thing I'm not sure if this has changed anything is that instead of selecting a class library with the .Net Framework in Visual Studio, I now do this with a console program with .Net Core.

I had to do this because I had problems with the framework, as it uses an older System.Runtime.dll that the TS3Client in the TS3Audiobot refers to. Since I didn't know how to update this, I found this possibility and this error doesn't occur anymore

**Comment by Splamy** [comment]
I released a new master version, with this feature baked in.
This however also includes all changes to the ts3client->tslib namespace; so you will have to update your 'using' directives.
Hope this helps.

**Comment by MoroseCorpse** [comment]
Good afternoon,

i have finally updated my plugin to the new master version. Now I have provoked another error for testing:

```
public void Initialize()
{
string test = "";
int test2 = int.Parse(test);
}
```

The output:

```
2020-04-17 14:07:32.2789|ERROR|0|Plugin.StartInternal Plugin 'SupportBot (BotPlugin)' failed to load: Input string was not in a correct format..
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at SupportBot.SupportBot.Initialize()
   at TS3AudioBot.Plugins.Plugin.StartInternal(Bot bot) in C:\projects\ts3audiobot\TS3AudioBot\Plugins\Plugin.cs:line 365
```

As you can see, still no lines are output. I do not understand what I am doing wrong. 

Would it be possible that you could give me a project folder with a plugin that prints lines if there are errors, because maybe I do something different when I create the project folder

**Comment by Splamy** [comment]
Thats my entire plugin file:
```cs
using System;
using TS3AudioBot.Plugins;

public class StackTrace : IBotPlugin
{
	public void Initialize()
	{
		string test = "";
		int test2 = int.Parse(test);
	}

	public void Dispose() {}
}
```

On both linux and windows i'm getting
```
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at StackTrace.Initialize() in :line 10
   at TS3AudioBot.Plugins.Plugin.StartInternal(Bot bot)
```
```
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at StackTrace.Initialize() in :line 10
   at TS3AudioBot.Plugins.Plugin.StartInternal(Bot bot) in E:\_Projects\git\TS3AudioBot\TS3AudioBot\Plugins\Plugin.cs:line 363
```

Two things:
- which dotnet core version are you using. I'm currently using 3.1 on both (you can download the 3.1 version of the master branch from here: https://splamy.de/TSAudioBot/Home)
- are you using the plugin as a `.cs` file or precompiling and as a `.dll` file ?

**Comment by MoroseCorpse** [comment]
I'm currently still using Dotnet 3.0 on Linux, which I would like to continue using for the time being

I compile the file into a dll file in Visual Studio 2019 as a class library with the .NET Framework 4.7.2

**Comment by Splamy** [comment]
Ah, I only added pdb loading for cs files currently. I'll see if i can push a patch. Otherwise if you just want the code to patch it yourself i can send it tomorrow.

> as a class library with the .NET Framework 4.7.2

that shoudn't work, if you are running dotnet you'll most linkely compiled them as netstandard or netcoreapp

**Comment by MoroseCorpse** [comment]
Okay, well, you can send me the code if you want.  But I would be happy if you could release a patch for the current 0.11 Master version, because I had such big problems to recompile the complete TS3AudioBot last time and I'm not sure if it would have worked properly

**Comment by Splamy** [comment]
So uhm, I pushed a fix to master a while a ago but appeyor didn't built it because gitversiontask hates me...
You can try to build it, otherwise you'll have to wait unit i fix the appveyor build for master

**Comment by MoroseCorpse** [comment]
I was wondering if there was any new information on this? 

I also wanted to ask if this thing is already included in the current develop version, since my colleague apparently doesn't want to use the master version after all, but rather the develop for which you don't need dotnet. 
Is there anything to consider when programming the plugin, because the new version does not run over dotnet anymore?

**Comment by MoroseCorpse** [comment]
Ok and do you already know when you will release the patch function for the current Dotnet Master version?
(And just in case we do use it, would it be possible to make this patch into the current develop version as well?)

**Comment by Splamy** [comment]
the patch is already on master, as said, the nighly server just had a hiccup and didn't build the `master_dotnet_core` and `master_dotnet_core_3_1_preview` versions

> (And just in case we do use it, would it be possible to make this patch into the current develop version as well?)

Sure

**Comment by MoroseCorpse** [comment]
Ok can you still hand out the dotnet master versions?

**Comment by Splamy** [comment]
Alright , I fixed the build; patch is now out on both branches

**Comment by MoroseCorpse** [comment]
Okay, thanks. It seems to work :)

**Comment by MoroseCorpse** [comment]
A quick question in passing. Do you already know when the 0.12 version will be stable?

**Comment by Splamy** [comment]
When #651 is done, so 4-6+ weeks maybe
