### ISSUE TITLE
Youtube-DL not work

### ISSUE THREAD

**Issue by Tentoxa** [Splamy/TS3AudioBot#754]
**Describe the problem**
I have installed youtube-dl but it does not play.

**To Reproduce**
I have a online web panel and i click there on youtube and then i must search for the Video and then came the error. The creator of these panel say that it is not due to the panel but to the bot.

**System Information**
- Debian 9  
  
- *I use dotnet... Version: 3.1.1
  
- I downloadet it from your post.  
  
(If all fields in the TS3AudioBot log header are correctly filled you can
alternatively just post the header here.)

**Additional Logs, Exceptions, etc**
When applicable try to add relevant log excerpts here.

```
2020-02-18 02:54:21.7267| WARN||Bot.TryCatchCommand Command Error (Could not load. (youtube: youtube-dl failed to load the resource.))
TS3AudioBot.CommandSystem.CommandException: Could not load. (youtube: youtube-dl failed to load the resource.)
   at TS3AudioBot.Helper.Util.UnwrapThrow(E`1 r) in C:\projects\ts3audiobot\TS3AudioBot\Helper\Util.cs:line 92
   at TS3AudioBot.MainCommands.CommandPlay(PlayManager playManager, InvokerData invoker, String url, String[] attributes) in C:\projects\ts3audiobot\TS3AudioBot\MainCommands.cs:line 1146
--- End of stack trace from previous location where exception was thrown ---
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.ExecuteFunction(Object[] parameters) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\FunctionCommand.cs:line 75
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\FunctionCommand.cs:line 204
   at TS3AudioBot.CommandSystem.Commands.OverloadedFunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\OverloadedFunctionCommand.cs:line 85
   at TS3AudioBot.CommandSystem.Commands.RootCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\RootCommand.cs:line 37
   at TS3AudioBot.Bot.<>c__DisplayClass42_0.<CallScript>b__0() in C:\projects\ts3audiobot\TS3AudioBot\Bot.cs:line 475
   at TS3AudioBot.Bot.TryCatchCommand(ExecutionInformation info, Boolean answer, Action action) in C:\projects\ts3audiobot\TS3AudioBot\Bot.cs:line 547
2020-02-18 02:54:36.9541| WARN||WebWrapper.ToLoggedError Web error: [429] TooManyRequests
System.Net.WebException: The remote server returned an error: (429) Too Many Requests.
   at System.Net.HttpWebRequest.GetResponse()
   at TS3AudioBot.Helper.WebWrapper.DownloadString(String& site, Uri link, ValueTuple`2[] headers) in C:\projects\ts3audiobot\TS3AudioBot\Helper\WebWrapper.cs:line 39
2020-02-18 02:54:39.1794|ERROR||YoutubeDlHelper.RunYoutubeDl youtube-dl failed to load the resource:
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by zmechu** [comment]
HTTP Error 429: Too Many Requests.

Youtube blocking "softly" your IP address because of overuse: https://github.com/ytdl-org/youtube-dl#http-error-429-too-many-requests-or-402-payment-required
Just wait few hours or use proxy.

**Comment by Tentoxa** [comment]
How can i use proxys with youtube-dl?

**Comment by zmechu** [comment]
` cat /etc/youtube-dl.conf | grep proxy
--proxy aa.bb.cc.dd:proxy_port`

**Comment by Tentoxa** [comment]
What do you mean? I executed the cat command, but I don't understand the -proxy command. Where do I enter it and do I have to add each proxy separately, or can I also specify a file? 
Best Regards
zTentox

**Comment by zmechu** [comment]
just create/edit " /etc/youtube-dl.conf" file

"--proxy " option allows to use proxy for youtube-dl connection (=workaround of IP blocking)
