### ISSUE TITLE
Lite DB Error

### ISSUE THREAD

**Issue by marv-th** [Splamy/TS3AudioBot#796]
I found a bug in the current develop. More details in the log
```
2020-05-16 15:28:57.0888| INFO||Setup.LogHeader [============ TS3AudioBot started =============]
2020-05-16 15:28:57.1587| INFO||Setup.LogHeader [ Date: Saturday, 16 May 2020 15:28:57
2020-05-16 15:28:57.2981| INFO||Setup.LogHeader [ Version: 0.12.0-alpha.34/develop/889d8de6
2020-05-16 15:28:57.2981| INFO||Setup.LogHeader [ Build: Release
2020-05-16 15:28:57.2981| INFO||Setup.LogHeader [ Platform: Ubuntu 18.04.4 LTS (Bionic Beaver) (64bit)
2020-05-16 15:28:57.2981| INFO||Setup.LogHeader [ Runtime: .NET Framework 3.1.3 ServerGC:False GC:SustainedLowLatency
2020-05-16 15:28:57.2981| INFO||Setup.LogHeader [ Opus: libopus 1.1.2 (x64)
2020-05-16 15:28:57.2981| INFO||Setup.LogHeader [==============================================]
2020-05-16 15:28:57.9281| INFO||WebServer.StartWebServerInternal Starting Webserver on port 513
2020-05-16 15:28:58.4954|FATAL||Core.UnhandledExceptionHandler Critical program failure!
LiteDB.LiteException: Cannot insert duplicate key in unique index '_id'. The duplicate value is '10144'.
   at LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, Byte level, IndexNode last)
   at LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, IndexNode last)
   at LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc, BsonType autoId)
   at LiteDB.LiteEngine.<>c__DisplayClass33_0.<Upsert>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Upsert(String collection, IEnumerable`1 docs, BsonType autoId)
   at LiteDB.LiteCollection`1.Upsert(IEnumerable`1 documents)
   at LiteDB.LiteCollection`1.Upsert(T document)
   at TS3AudioBot.Environment.Stats.TrackPoint()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
2020-05-16 15:28:58.5326| INFO||Core.StopAsync TS3AudioBot shutting down.
2020-05-16 15:28:58.5352| INFO||WebServer.Dispose WebServer is closing
2020-05-16 15:28:58.5369| INFO||WebServer.OnShutdown WebServer has closed
2020-05-16 15:28:58.5856| INFO||Core.StopAsync Bye
```

**Comment by marv-th** [comment]
I was able to fix this to rename the ts3audiobot.db. When you want to have this file, i can send it to you per email.
I dont know if this db file storage some user informations

**Comment by Splamy** [comment]
the db does not have user information, but it stores authentication tokens, so please send it via email

**Comment by marv-th** [comment]
Hey. I send you an email

**Comment by Splamy** [comment]
Kay, should be fixed on dev
