### ISSUE TITLE
Songs stopped to play

### ISSUE THREAD

**Issue by marv-th** [Splamy/TS3AudioBot#799]
**Describe the bug**
Songs stoped worked to play.
First I thought, that error could be something to do with the plugins but it looks more like a ts3ab error.
Log:
```
2020-05-21 09:00:02.6768| INFO||WebApi.ProcessApiV1Call ::ffff:51.178.6.114 Requested: /api/bot/use/0/(/play/%22a576ecedcc4ddc7f811df941bb11242cd1384d22.mp3%22)
2020-05-21 09:00:02.7609| INFO|0|NowPlaying.Ask_For_Song_Info AFSI:986699389
2020-05-21 09:00:02.7609|ERROR||WebApi.ProcessApiV1Call Unexpected command error
System.NullReferenceException: Object reference not set to an instance of an object.
   at GOSPlugin_IBot.NowPlaying.Ask_For_Song_Info()
   at GOSPlugin_IBot.NowPlaying.AfterStart(Object sender, EventArgs e)
   at TS3AudioBot.Audio.PlayManager.StartResource(InvokerData invoker, PlayResource play, MetaData meta) in C:\projects\ts3audiobot\TS3AudioBot\Audio\PlayManager.cs:line 182
   at TS3AudioBot.MainCommands.CommandPlay(PlayManager playManager, InvokerData invoker, String url) in C:\projects\ts3audiobot\TS3AudioBot\MainCommands.cs:line 1077
--- End of stack trace from previous location where exception was thrown ---
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.ExecuteFunction(Object[] parameters) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\FunctionCommand.cs:line 71
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\FunctionCommand.cs:line 212
   at TS3AudioBot.CommandSystem.Commands.OverloadedFunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\OverloadedFunctionCommand.cs:line 88
   at TS3AudioBot.CommandSystem.Commands.LazyCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\LazyCommand.cs:line 33
   at TS3AudioBot.MainCommands.CommandBotUseInternal(ExecutionInformation info, IReadOnlyList`1 returnTypes, BotLock botLock, ICommand cmd) in C:\projects\ts3audiobot\TS3AudioBot\MainCommands.cs:line 296
   at TS3AudioBot.MainCommands.CommandBotUse(ExecutionInformation info, IReadOnlyList`1 returnTypes, BotManager bots, Int32 botId, ICommand cmd) in C:\projects\ts3audiobot\TS3AudioBot\MainCommands.cs:line 286
--- End of stack trace from previous location where exception was thrown ---
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.ExecuteFunction(Object[] parameters) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\FunctionCommand.cs:line 71
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\FunctionCommand.cs:line 181
   at TS3AudioBot.Web.Api.WebApi.ProcessApiV1Call(HttpContext context) in C:\projects\ts3audiobot\TS3AudioBot\Web\Api\WebApi.cs:line 105
2020-05-21 09:00:02.7629|ERROR||WebApi.ReturnError Unexpected command error
System.NullReferenceException: Object reference not set to an instance of an object.
   at GOSPlugin_IBot.NowPlaying.Ask_For_Song_Info()
   at GOSPlugin_IBot.NowPlaying.AfterStart(Object sender, EventArgs e)
   at TS3AudioBot.Audio.PlayManager.StartResource(InvokerData invoker, PlayResource play, MetaData meta) in C:\projects\ts3audiobot\TS3AudioBot\Audio\PlayManager.cs:line 182
   at TS3AudioBot.MainCommands.CommandPlay(PlayManager playManager, InvokerData invoker, String url) in C:\projects\ts3audiobot\TS3AudioBot\MainCommands.cs:line 1077
--- End of stack trace from previous location where exception was thrown ---
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.ExecuteFunction(Object[] parameters) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\FunctionCommand.cs:line 71
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\FunctionCommand.cs:line 212
   at TS3AudioBot.CommandSystem.Commands.OverloadedFunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\OverloadedFunctionCommand.cs:line 88
   at TS3AudioBot.CommandSystem.Commands.LazyCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\LazyCommand.cs:line 33
   at TS3AudioBot.MainCommands.CommandBotUseInternal(ExecutionInformation info, IReadOnlyList`1 returnTypes, BotLock botLock, ICommand cmd) in C:\projects\ts3audiobot\TS3AudioBot\MainCommands.cs:line 296
   at TS3AudioBot.MainCommands.CommandBotUse(ExecutionInformation info, IReadOnlyList`1 returnTypes, BotManager bots, Int32 botId, ICommand cmd) in C:\projects\ts3audiobot\TS3AudioBot\MainCommands.cs:line 286
--- End of stack trace from previous location where exception was thrown ---
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.ExecuteFunction(Object[] parameters) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\FunctionCommand.cs:line 71
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments, IReadOnlyList`1 returnTypes) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\FunctionCommand.cs:line 181
   at TS3AudioBot.Web.Api.WebApi.ProcessApiV1Call(HttpContext context) in C:\projects\ts3audiobot\TS3AudioBot\Web\Api\WebApi.cs:line 105
2020-05-21 09:00:02.7629| INFO||WebApi.ProcessApiV1Call ::ffff:51.178.6.114 Requested: /api/bot/use/0/(/volume/4/)
```

**Version**
0.10.1+7/master/65aa9a18

Why this time Master? Because the develop is only our alpha version and master our build.

**Platform**
Debian GNU/Linux 9 (stretch) (64bit)

**Comment by marv-th** [comment]
The error result if i want to change the song very often.

**Comment by Splamy** [comment]
The error is thrown in your plugin code as seen here:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GOSPlugin_IBot.NowPlaying.Ask_For_Song_Info()
   at GOSPlugin_IBot.NowPlaying.AfterStart(Object sender, EventArgs e)
```
