### ISSUE TITLE
ServerGroupClientList and how to get the standard ServerGroup

### ISSUE THREAD

**Issue by MoroseCorpse** [Splamy/TS3AudioBot#823]
I wanted to ask if there is already a direct function for the ServerGroupClientList request in the current developer version. 

My second question is, how do I get the default ServerGroup of the server

**Comment by Splamy** [comment]
You can request ServerGroupClientList with:
```cs
var res =  await SendHybrid<ClientIds>(new TsCommand("servergroupclientlist") {
	{ "sgid", groupId}
}, NotificationType.ServerGroupClientList);
```

You can get the default server group from the book in `ts3Client.Book.DefaultServerGroup`

**Comment by MoroseCorpse** [comment]
When I execute the function you have shown above the following error occurs:

```
2020-07-03 15:09:47.4675|FATAL||Core.UnhandledExceptionHandler Critical program failure!
System.InvalidCastException: Unable to cast object of type 'TSLib.Messages.ServerGroupClientList[]' to type 'TSLib.Messages.ClientIds[]'.
   at TSLib.Messages.CommandErrorExtensions.UnwrapNotification[T](R`2& result) in D:\Users\Moritz\Desktop\TS3AudioBot-develop\TSLib\Helper\CommandErrorExtensions.cs:line 71
   at TSLib.Full.TsFullClient.SendHybrid[T](TsCommand com, NotificationType type) in D:\Users\Moritz\Desktop\TS3AudioBot-develop\TSLib\Full\TsFullClient.cs:line 423
   at UserDisplay.UserDisplay.user_list(String only_groups, String ignore_groups, String only_channels, String ignore_channels, String away, String querys, String online, String offline, String afk, String afk_groups, String afk_channel, String afk_away) in D:\Users\Moritz\Desktop\Development\UserDisplay\UserDisplay\UserDisplay.cs:line 1254
   at UserDisplay.UserDisplay.user_display() in D:\Users\Moritz\Desktop\Development\UserDisplay\UserDisplay\UserDisplay.cs:line 739
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

And in ts3Client.Book.DefaultServerGroup no book exists at all. For me there is only a book in the FullClient, but there is not the option DefaultServerGroup

**Comment by Splamy** [comment]
Ops two copy and paste mistakes:
The first one should be:
```cs
var res =  await SendHybrid<ServerGroupClientList>(new TsCommand("servergroupclientlist") {
	{ "sgid", groupId}
}, NotificationType.ServerGroupClientList);
```

And it should have been `ts3Client.Book.Server.DefaultServerGroup` for the second. And with `ts3Client` i meant the `TsFullClient`

**Comment by MoroseCorpse** [comment]
Ok, thanks now ServerGroupClientList works, but I noticed that the name is always empty on the clients. 

And I have another question, how can I check if the Clients in the group are online or offline. I have already tried the ClientDbInfo function and then use the ClientId to check if he has one or not, but the ClientId is always 0. 

Then I tried with the function getClientIds, but there is this error message every time: `database empty result set`

These problems always occur. Whether the client is online or offline

**Comment by Splamy** [comment]
I'd recommend you to read the ts3 query documentation. If you want names set in the field you have to add the `-names` option in the request:
```cs
var res =  await SendHybrid<ServerGroupClientList>(new TsCommand("servergroupclientlist") {
	{ "sgid", groupId},
	{ new CommandOption("names") }
}, NotificationType.ServerGroupClientList);
```

and to check which af on/offline, my approach would be to create a hashset<clientdbid> with all the dbid's you got from the servergroupclientlist and then call 'clientlist' ang go through all clients to check whether they are included in the hashset or not

**Comment by Bluscream** [comment]
GetClientIds is the correct funtion, and empty result means the person is not online. Teamspeak invokes that command if you click on someones name in the chat to show the correct menu entries for example. It does not work correctly on teaspeak servers though.

**Comment by Splamy** [comment]
Yeah but you will need to call `GetClientIds` for every single client, whereas the clientlist+hashset approach requires two call and the rest can be calculated clientside
