### ISSUE TITLE
Occurs at once

### ISSUE THREAD

**Issue by LabyException** [Splamy/TS3AudioBot#825]
```
2020-07-03 08:36:17.4750| INFO|Api|Bot.Run Bot "5009_aZJi1Qr2Bq2MMJtzoMWyy3uAR" connecting to "****.de" 
2020-07-03 08:36:17.5321| INFO|Api|WebApi.ProcessApiV1Call ::ffff:**.***.**.*** Requested: /api/bot/use/2/(/bot/disconnect
2020-07-03 08:36:17.5321| INFO|Api|Bot.Stop Bot (2) disconnecting.
2020-07-03 08:36:17.5478|FATAL|2|Core.UnhandledExceptionHandler Critical program failure!
 System.InvalidOperationException: context should be set
 at TSLib.Full.TsFullClient.<ProcessEachInitIvExpand2>d__610.MoveNext() in C:\projects\ts3audiobot\TSLib\Full\TsFullClient.cs:line 276
 at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
 at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
 at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
 at System.Threading.QueueUserWorkItemCallback.Execute()
 at System.Threading.ThreadPoolWorkQueue.Dispatch()
2020-07-03 08:36:17.5652| INFO|2|Core.StopAsync TS3AudioBot shutting down.
2020-07-03 08:36:17.5689| INFO|2|Bot.Stop Bot (1) disconnecting. 2020-07-03 08:36:17.5689| INFO|2|Bot.Stop Bot (0) disconnecting.
```

**Comment by Splamy** [comment]
I've pushed a fix on develop, also next time please format your log better and provide more information like which version you have and describe the problem

**Comment by LabyException** [comment]
Version: 0.12.0-alpha.43
Branch: develop
CommitHash: 49c22b48cc6af746a4e0d6cd2e470d088ae84cec
