### ISSUE TITLE
Unknown Issue

### ISSUE THREAD

**Issue by MoroseCorpse** [Splamy/TS3AudioBot#828]
**Describe the bug**
When I try to create a bot, I get an error message that I do not understand:

**Version**
0.10.1+7/master/65aa9a18

**Platform**
Ubuntu 18.04.4 LTS (Bionic Beaver) (64bit)
.NET Core (3.0.0) ServerGC:True GC:SustainedLowLatency

**Log**
```
2020-07-09 15:34:58.6515| WARN|0|PacketHandler`2.SendRaw Failed to deliver packet (Err:AccessDenied)
System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at TS3Client.Full.PacketHandler`2.SendRaw(Packet`1& packet) in C:\projects\ts3audiobot\TS3Client\Full\PacketHandler.cs:line 758
```

**Comment by Flakebi** [comment]
It seems like the issue is that the source ip of a packet is unusual (i.e. a broadcast or multicast ip address as in [this issue](https://github.com/dotnet/core/issues/2020)).
What is the ip address that you are trying to connect to?

Running `strace -f -s 20 -e trace=%network dotnet ts3audiobot.dll` should show the error with more details.

Also, it seems like you changed some code there, maybe it’s related to that?

**Comment by MoroseCorpse** [comment]
I entered the above command without the % sign, because it didn't work with that character.
When it worked without the character, he gave me the following:

```
strace: Process 120747 attached
strace: Process 120748 attached
[pid 120748] socket(AF_UNIX, SOCK_STREAM, 0) = 5
[pid 120748] setsockopt(5, SOL_SOCKET, SO_SNDTIMEO, "\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0
[pid 120748] connect(5, {sa_family=AF_UNIX, sun_path="/root/.lttng/lttng-ust-sock-7"}, 110) = -1 ENOENT (No such file or directory)
[pid 120747] socket(AF_UNIX, SOCK_STREAM, 0) = 5
[pid 120747] setsockopt(5, SOL_SOCKET, SO_SNDTIMEO, "\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16) = 0
[pid 120747] connect(5, {sa_family=AF_UNIX, sun_path="/var/run/lttng/lttng-ust-sock-7"}, 110) = -1 ENOENT (No such file or directory)
strace: Process 120749 attached
strace: Process 120750 attached
strace: Process 120751 attached
strace: Process 120752 attached
strace: Process 120753 attached
strace: Process 120754 attached
strace: Process 120755 attached
strace: Process 120756 attached
strace: Process 120757 attached
[pid 120754] +++ exited with 0 +++
strace: Process 120758 attached
No executable found matching command "dotnet-ts3audiobot.dll"
[pid 120758] +++ exited with 1 +++
[pid 120756] +++ exited with 1 +++
[pid 120757] +++ exited with 1 +++
[pid 120755] +++ exited with 1 +++
[pid 120753] +++ exited with 1 +++
[pid 120752] +++ exited with 1 +++
[pid 120751] +++ exited with 1 +++
[pid 120750] +++ exited with 1 +++
[pid 120749] +++ exited with 1 +++
[pid 120748] +++ exited with 1 +++
[pid 120747] +++ exited with 1 +++
+++ exited with 1 +++```

**Comment by Flakebi** [comment]
Interesting, it works for me with the % sign. I think you need to replace `dotnet-ts3audiobot.dll` in your command line with whatever command you use to start the audiobot.

**Comment by MoroseCorpse** [comment]
Here is a small extract from the infinite log:

```
[pid 124884] sendmsg(170, {msg_name={sa_family=AF_INET, sin_port=htons(9987), sin_addr=inet_addr("51.178.6.113")}, msg_namelen=16, msg_iov=[{iov_base="ww\374\244\327\222\344@\0C\0\20\205\0C", iov_len=15}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_OOB}, 0) = 15
[pid 124884] recvmsg(170, {msg_namelen=16}, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 124884] sendmsg(172, {msg_name={sa_family=AF_INET, sin_port=htons(9987), sin_addr=inet_addr("51.178.6.124")}, msg_namelen=16, msg_iov=[{iov_base="xT\222C\315\301\276\326\0C\1\213\204", iov_len=13}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0 <unfinished ...>
[pid 124885] sendmsg(170, {msg_name={sa_family=AF_INET, sin_port=htons(9987), sin_addr=inet_addr("51.178.6.113")}, msg_namelen=16, msg_iov=[{iov_base="ww\374\244\327\222\344@\0C\0\20\204", iov_len=13}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0 <unfinished ...>
[pid 124884] <... sendmsg resumed> )    = 13
[pid 124885] <... sendmsg resumed> )    = 13
[pid 124885] recvmsg(170, {msg_name={sa_family=AF_INET, sin_port=htons(9987), sin_addr=inet_addr("51.178.6.113")}, msg_namelen=16, msg_iov=[{iov_base="ww\374\244\327\222\344@\0C\205\0C", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 13
[pid 124885] recvmsg(170, {msg_namelen=16}, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 124885] recvmsg(172, {msg_name={sa_family=AF_INET, sin_port=htons(9987), sin_addr=inet_addr("51.178.6.124")}, msg_namelen=16, msg_iov=[{iov_base="xT\222C\315\301\276\326\0C\205\0C", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 13
[pid 124885] recvmsg(172, {msg_namelen=16}, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 124861] socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC, IPPROTO_UDP) = 171
[pid 124861] bind(171, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
[pid 124861] recvmsg(171, {msg_namelen=16}, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 124861] sendmsg(171, {msg_name={sa_family=AF_INET, sin_port=htons(9989), sin_addr=inet_addr("51.178.6.127")}, msg_namelen=16, msg_iov=[{iov_base="TS3INIT1\0e\0\0\210]e60\0_\t"..., iov_len=34}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_OOB|MSG_PEEK|MSG_DONTROUTE}, 0) = -1 EACCES (Permission denied)
```

The 51.178.6.124 IP is the IP that causes problems

**Comment by Flakebi** [comment]
Thanks for the log. It looks like it fails in this line:
```
[pid 124861] recvmsg(171, {msg_namelen=16}, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid 124861] sendmsg(171, {msg_name={sa_family=AF_INET, sin_port=htons(9989), sin_addr=inet_addr("51.178.6.127")}, msg_namelen=16, msg_iov=[{iov_base="TS3INIT1\0e\0\0\210]e60\0_\t"..., iov_len=34}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_OOB|MSG_PEEK|MSG_DONTROUTE}, 0) = -1 EACCES (Permission denied)
```

So 51.178.6.127 seems to be an ip that makes problems.
Can you try `ping 51.178.6.127`?
And can you paste the output of `ip route`? Maybe something in there is special for this ip.

On a sidenote, the `EAGAIN (Resource temporarily unavailable)` errors are harmless, they just means that no data is currently available to read.
