### ISSUE TITLE
An extractor error has occurred.

### ISSUE THREAD

**Issue by hazzeee** [Splamy/TS3AudioBot#840]
**Describe the problem**

Youtube started to block much of ip-s and now a lot of music bot can't work, i fixed that error with my own cookies in the youtube-dl config, but now !search from youtube can't work, play works perfect, but search can't work. I need config to auto search youtube link or title e.g. youtube-dl my song or youtube-dl https://youtu.be/my-song. That will fix the youtube search feature, or if you have some other solve please tell me, but i need to use own cookies in config becouse without that youtube-dl showing error 429 Too many requests. Thanks!

**System Information**
- **Platform**: Debian 9 64bit 
  
- **Mono version**: Using latest version of Dotnet
  
- **Which commit did you download**: Latest

**YOUTUBE-DL VERBOSE LOG**

```
root@vps-30748f4f:~# youtube-dl test test -v
[debug] System config: [u'--cookies', u'/usr/local/bin/cookies.txt', u'-x', u'--                                                                                        default-search', u'auto', u'--playlist-items', u'1']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'test', u'test', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-5-cloud-amd64-x86_64-with                                                                                        -debian-10.0
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1
[debug] Proxy map: {}
[youtube:search] query "test": Downloading page 1
ERROR: An extractor error has occurred. (caused by KeyError(1,)); please report                                                                                         this issue on https://yt-dl.org/bug . Make sure you are using the latest version                                                                                        ; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose                                                                                         flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in                                                                                         extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 2995, in                                                                                         _real_extract
    return self._get_n_results(query, 1)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 3183, i                                                                                        n _get_n_results
    html_content = data[1]['body']['content']
KeyError: 1
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract                                                                                        _info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 543, in                                                                                         extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(1,)); pleas                                                                                        e report this issue on https://yt-dl.org/bug . Make sure you are using the lates                                                                                        t version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the -                                                                                        -verbose flag and include its complete output.
```

**MY YOUTUBE-DL CONFIG**
![image](https://user-images.githubusercontent.com/60288878/89102609-55f3ef00-d40b-11ea-9a46-df283920c59e.png)

**TS3AudioBot Log**
Dont need, it does not showing any error.

**FEEL FREE TO HELP AND COMMENT :)** 👍

**Comment by hazzeee** [comment]
I fixed it!
