### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Heisz0205** [Splamy/TS3AudioBot#843]
Version: 0.12.0-alpha.46
Platform: ubuntu 18.04
Dotnet: Version:   3.1.302

**Log**

2020-08-04 11:53:40.0482| INFO|0|Bot.OnMessageReceived User CZ requested: !yt everest
2020-08-04 11:53:40.2452|ERROR|0|Bot.TryCatchCommand Unexpected command error: Could not load type 'System.Text.Json.JsonException' from assembly 'Microsoft.AspNetCore.Server.Kestrel, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
System.TypeLoadException: Could not load type 'System.Text.Json.JsonException' from assembly 'Microsoft.AspNetCore.Server.Kestrel, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at TS3AudioBot.Helper.WebWrapper.AsJson[T](HttpRequestMessage request)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at TS3AudioBot.Helper.WebWrapper.AsJson[T](HttpRequestMessage request)
   at TS3AudioBot.ResourceFactories.Youtube.YoutubeResolver.SearchYoutubeApi(String keyword)
   at TS3AudioBot.ResourceFactories.Youtube.YoutubeResolver.Search(ResolveContext _, String keyword)
   at TS3AudioBot.ResourceFactories.ResourceResolver.Search(ResolveContext ctx, String resolverName, String query)
   at TS3AudioBot.MainCommands.PropagiateSearch(UserSession session, CallerInfo callerInfo, ResolveContext resolver, String resolverName, String query)
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.ExecuteFunction(Object[] parameters)
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at TS3AudioBot.CommandSystem.BotCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at TS3AudioBot.CommandSystem.Commands.RootCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at TS3AudioBot.MainCommands.CommandXecute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.ExecuteFunction(Object[] parameters)
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at TS3AudioBot.CommandSystem.BotCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at TS3AudioBot.CommandSystem.Commands.RootCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at TS3AudioBot.CommandSystem.Commands.AliasCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at TS3AudioBot.CommandSystem.Commands.RootCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at TS3AudioBot.CommandSystem.CommandManager.Execute(ExecutionInformation info, String command)
   at TS3AudioBot.Bot.<>c__DisplayClass41_0.<<CallScript>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at TS3AudioBot.Bot.TryCatchCommand(ExecutionInformation info, Boolean answer, Func`1 action)

**Comment by Splamy** [comment]
Hey, sorry for the late response, I was a bit busy.
This issue seems the same as the newly opend one #845 so I'll close this one to keep the discussions grouped. Please check the question/suggestion in the other issue
