### ISSUE TITLE
Critical program failure with dotnet core

### ISSUE THREAD

**Issue by ShadowFM** [Splamy/TS3AudioBot#855]
**Describe the bug**
Restarted the ts3audiobot and after crashed after a minute with the message from the subject

**Version**
Version: 0.12.0-alpha.18
Branch: develop

**Platform**
OS: Ubuntu 16.04
.Net Core: Version: 3.1.6

**Log**
```
Aug 25 19:25:51 musicbot dotnet[3678]: 19:25:51.2904| INFO|| [============ TS3AudioBot started =============]
Aug 25 19:25:51 musicbot dotnet[3678]: 19:25:51.3106| INFO|| [ Date: Tuesday, 25 August 2020 19:25:51
Aug 25 19:25:51 musicbot dotnet[3678]: 19:25:51.3280| INFO|| [ Version: 0.12.0-alpha.18/develop/a9dea044
Aug 25 19:25:51 musicbot dotnet[3678]: 19:25:51.3280| INFO|| [ Build: Release
Aug 25 19:25:51 musicbot dotnet[3678]: 19:25:51.3280| INFO|| [ Platform: Ubuntu 16.04.7 LTS (Xenial Xerus) (64bit)
Aug 25 19:25:51 musicbot dotnet[3678]: 19:25:51.3280| INFO|| [ Runtime: .NET Core (3.1.6) ServerGC:True GC:SustainedLowLatency
Aug 25 19:25:51 musicbot dotnet[3678]: 19:25:51.3280| INFO|| [ Opus: libopus 1.1.2 (x64)
Aug 25 19:25:51 musicbot dotnet[3678]: 19:25:51.3280| INFO|| [==============================================]
...
2020-08-25 19:25:55.7203| WARN||Util.UnwrapToLog Unknown Teamspeak Error. (invalid file path) ()
2020-08-25 19:25:56.0447| WARN||Util.UnwrapToLog Unknown Teamspeak Error. (invalid file path) ()
2020-08-25 19:26:52.5567|FATAL||Core.ExceptionHandler Critical program failure!
System.InvalidCastException: Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.HeaderPage'.
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.PageService.NewPage[T](BasePage prevPage)
   at LiteDB.PageService.GetFreePage[T](UInt32 startPageID, Int32 size)
   at LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, Byte level, IndexNode last)
   at LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, IndexNode last)
   at LiteDB.LiteEngine.UpdateDocument(CollectionPage col, BsonDocument doc)
   at LiteDB.LiteEngine.<>c__DisplayClass33_0.<Upsert>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at LiteDB.LiteEngine.Upsert(String collection, IEnumerable`1 docs, BsonType autoId)
   at LiteDB.LiteCollection`1.Upsert(IEnumerable`1 documents)
   at LiteDB.LiteCollection`1.Upsert(T document)
   at TS3AudioBot.Environment.Stats.TrackPoint() in C:\projects\ts3audiobot\TS3AudioBot\Environment\Stats.cs:line 159
   at TS3AudioBot.Environment.Stats.<StartTimer>b__23_0() in C:\projects\ts3audiobot\TS3AudioBot\Environment\Stats.cs:line 103
   at TS3AudioBot.Helper.TickPool.Tick() in C:\projects\ts3audiobot\TS3AudioBot\Helper\TickPool.cs:line 85
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
2020-08-25 19:26:52.5617| INFO||Core.Dispose TS3AudioBot shutting down.
2020-08-25 19:26:52.5627| INFO||Bot.Dispose Bot (0) disconnecting.
2020-08-25 19:26:52.5698| INFO||Bot.Dispose Bot (1) disconnecting.
2020-08-25 19:26:52.5759| INFO||Bot.Dispose Bot (2) disconnecting.
2020-08-25 19:26:52.5830| INFO||Bot.Dispose Bot (3) disconnecting.
2020-08-25 19:26:52.5877| INFO||Bot.Dispose Bot (4) disconnecting.
2020-08-25 19:26:52.5930| INFO||Bot.Dispose Bot (5) disconnecting.
2020-08-25 19:26:52.5963| INFO||Bot.Dispose Bot (6) disconnecting.
2020-08-25 19:26:52.5989| INFO||Bot.Dispose Bot (7) disconnecting.
2020-08-25 19:26:52.6036| INFO||WebServer.Dispose WebServer is closing

```

**Comment by Splamy** [comment]
Delete your ts3audiobot.db, it's a stupid bug of the db library. I haven't upgraded yet to the latest version since it has a few breaking changes, i'll do it when i'm back home
