### ISSUE TITLE
Error play song youtube or radio

### ISSUE THREAD

**Issue by x-Scripts** [Splamy/TS3AudioBot#858]
**Describe the bug**
An unexpected error occurred: The type initializer for 'TS3AudioBot.Helper.WebWrapper' threw an exception.

**Version**
0.12.0-alpha51

**Platform**
ubuntu 19.04

**Log**
20:14:57.415|ERROR||Bot.TryCatchCommand Unexpected command error: The type initializer for 'TS3AudioBot.Helper.WebWrapper' threw an exception.
 System.TypeInitializationException: The type initializer for 'TS3AudioBot.Helper.WebWrapper' threw an exception.
  ---> System.FormatException: The format of value '' is invalid.
    at System.Net.Http.Headers.HeaderUtilities.CheckValidToken(String value, String parameterName)
    at System.Net.Http.Headers.ProductHeaderValue..ctor(String name, String version)
    at System.Net.Http.Headers.ProductInfoHeaderValue..ctor(String productName, String productVersion)
    at TS3AudioBot.Helper.WebWrapper..cctor() in /home/TS3AudioBot/TS3AudioBot/Helper/WebWrapper.cs:line 36
    --- End of inner exception stack trace ---
    at TS3AudioBot.Helper.WebWrapper.Request(String link) in /home/TS3AudioBot/TS3AudioBot/Helper/WebWrapper.cs:line 41
    at TS3AudioBot.ResourceFactories.Youtube.YoutubeResolver.ResolveResourceInternal(AudioResource resource) in /home/TS3AudioBot/TS3AudioBot/ResourceFactories/Youtube/YoutubeResolver.cs:line 88
    at TS3AudioBot.ResourceFactories.Youtube.YoutubeResolver.GetResourceById(ResolveContext _, AudioResource resource) in /home/TS3AudioBot/TS3AudioBot/ResourceFactories/Youtube/YoutubeResolver.cs:line 75
    at TS3AudioBot.ResourceFactories.Youtube.YoutubeResolver.GetResource(ResolveContext _, String uri) in /home/TS3AudioBot/TS3AudioBot/ResourceFactories/Youtube/YoutubeResolver.cs:line 59
    at TS3AudioBot.ResourceFactories.ResourceResolver.Load(ResolveContext ctx, String message, String audioType) in /home/TS3AudioBot/TS3AudioBot/ResourceFactories/ResourceResolver.cs:line 141
    at TS3AudioBot.Audio.PlayManager.Play(InvokerData invoker, String link, String audioType, PlayInfo meta) in /home/TS3AudioBot/TS3AudioBot/Audio/PlayManager.cs:line 122
    at TS3AudioBot.MainCommands.CommandPlay(PlayManager playManager, InvokerData invoker, String url, String[] attributes) in /home/TS3AudioBot/TS3AudioBot/MainCommands.cs:line 1195
    at TS3AudioBot.CommandSystem.Commands.FunctionCommand.ExecuteFunction(Object[] parameters) in /home/TS3AudioBot/TS3AudioBot/CommandSystem/Commands/FunctionCommand.cs:line 81
    at TS3AudioBot.CommandSystem.Commands.FunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in /home/TS3AudioBot/TS3AudioBot/CommandSystem/Commands/FunctionCommand.cs:line 203
    at TS3AudioBot.CommandSystem.BotCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in /home/TS3AudioBot/TS3AudioBot/CommandSystem/BotCommand.cs:line 131
    at TS3AudioBot.CommandSystem.Commands.OverloadedFunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in /home/TS3AudioBot/TS3AudioBot/CommandSystem/Commands/OverloadedFunctionCommand.cs:line 84
    at TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in /home/TS3AudioBot/TS3AudioBot/CommandSystem/Commands/CommandGroup.cs:line 63
    at TS3AudioBot.CommandSystem.Commands.RootCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in /home/TS3AudioBot/TS3AudioBot/CommandSystem/Commands/RootCommand.cs:line 41
    at TS3AudioBot.CommandSystem.CommandManager.Execute(ExecutionInformation info, String command) in /home/TS3AudioBot/TS3AudioBot/CommandSystem/CommandManager.cs:line 401
    at TS3AudioBot.Bot.<>c__DisplayClass42_0.<b__0>d.MoveNext() in /home/TS3AudioBot/TS3AudioBot/Bot.cs:line 503
 --- End of stack trace from previous location where exception was thrown ---
    at TS3AudioBot.Bot.TryCatchCommand(ExecutionInformation info, Boolean answer, Func`1 action) in /home/TS3AudioBot/TS3AudioBot/Bot.cs:line 530

**Comment by szogun1910** [comment]
@Splamy hey, can you tell how to fix it?

**Comment by ShadowFM** [comment]
Is it a self-compiled version?
For me it looks like something is missing.
Maybe you could try to use a new pre-compiled version

**Comment by x-Scripts** [comment]
It is a compiled application on the server, the ready compilation works from the splamy.de server

**Comment by szogun1910** [comment]
bump

**Comment by Splamy** [comment]
Sorry for the sparse responses recently, I'm a bit stressed.
Regarding your problem, seems like the automatic version generator did something weird on your machine.
Simple fix on the fly would be to replace this line here:
https://github.com/Splamy/TS3AudioBot/blob/2cae181932344a20def9d691f35627b98915d715/TS3AudioBot/Helper/WebWrapper.cs#L36
with something like
`httpClient.DefaultRequestHeaders.UserAgent.Add(new ProductInfoHeaderValue("TS3AudioBot", "1.2.3.4"));`
Removing the line entirely might have a negative effect since there are some servers which outright block the default .NET user agent for some reason

**Comment by szogun1910** [comment]
@Splamy Thanks for the help

**Comment by Flakebi** [comment]
Fixed on the develop branch
