### ISSUE TITLE
Error 403 Forbidden

### ISSUE THREAD

**Issue by xEzitx** [Splamy/TS3AudioBot#86]
So basically told it to add a link, it said Web Error: [403] Forbidden and then I told it to add a crappy video of something random, it replied with the codecs, asked it to show me the list then told it to do !play, and it crashed, so I'm stuff at the minute with this issue, any ideas?

```
[01:44:37]   Info: [============ TS3AudioBot started =============]
[01:44:37]   Info: [=== Date:                     17 June 2017 ===]
[01:44:37]   Info: [=== Time:                         01:44:37 ===]
[01:44:37]   Info: [==============================================]
[01:44:37]   Info: [============ Initializing Commands ===========]
[01:44:37]   Info: [============ Initializing Modules ============]
[01:44:37]   Info: [=========== Initializing Factories ===========]
[01:44:37]   Info: [=========== Registering callbacks ============]
[01:44:37]   Info: [================= Finalizing =================]
[01:44:37]   Info: [============== Connected & Done ==============]
[01:44:43]  Debug: MB Got message from Luke: !play [URL]https://www.youtube.com/watch?v=lgQprNvmsRQ[/URL]
[01:44:43]  Debug: SM User Luke created session with the bot
[01:44:43]  Debug: YT avail codecs: hd720 @ MP4, medium @ WEBM, medium @ MP4, small @ ThreeGP, small @ ThreeGP, audio/mp4; codecs="mp4a.40.2" @ M4A, audio/webm; codecs="vorbis" @ WEBM, audio/webm; codecs="opus" @ WEBM, audio/webm; codecs="opus" @ WEBM, audio/webm; codecs="opus" @ WEBM, 
[01:44:43]  Debug: AF stop old
[01:44:43]  Debug: AF ar start: Youtube ID:lgQprNvmsRQ
[01:44:43]  Error: Error return from player: Unable to create stream (Access is denied)
[01:44:54]  Debug: MB Got message from Luke: !add [URL]https://www.youtube.com/watch?v=dtCxmbFgnrc[/URL]
[01:44:54]  Debug: YT avail codecs: hd720 @ MP4, medium @ WEBM, medium @ MP4, small @ ThreeGP, small @ ThreeGP, audio/mp4; codecs="mp4a.40.2" @ M4A, audio/webm; codecs="vorbis" @ WEBM, audio/webm; codecs="opus" @ WEBM, audio/webm; codecs="opus" @ WEBM, audio/webm; codecs="opus" @ WEBM, 
[01:44:54]Warning: TH Web error: [403] Forbidden
[01:44:54]  Debug: YT Ruined!
[01:44:57]  Debug: YT Saved!
[01:45:05]  Debug: MB Got message from Luke: !add [URL]https://www.youtube.com/watch?v=lgQprNvmsRQ[/URL]
[01:45:05]  Debug: YT avail codecs: hd720 @ MP4, medium @ WEBM, medium @ MP4, small @ ThreeGP, small @ ThreeGP, audio/mp4; codecs="mp4a.40.2" @ M4A, audio/webm; codecs="vorbis" @ WEBM, audio/webm; codecs="opus" @ WEBM, audio/webm; codecs="opus" @ WEBM, audio/webm; codecs="opus" @ WEBM, 
[01:45:11]  Debug: MB Got message from Luke: !list show
[01:45:16]  Debug: MB Got message from Luke: !list get
[01:45:20]  Debug: MB Got message from Luke: !play
[01:45:21]  Error: Critical program failure!. Exception:
MSG: StandardOut has not been redirected or the process hasn't started yet.
TYPE:InvalidOperationException
STACK:   at System.Diagnostics.Process.get_StandardOutput()
   at TS3AudioBot.Ts3Full.AudioSend() in C:\Users\Ezit\Desktop\TS3AudioBot-master\TS3AudioBot\Ts3Full.cs:line 229
   at TS3AudioBot.Helper.TickPool.Tick() in C:\Users\Ezit\Desktop\TS3AudioBot-master\TS3AudioBot\Helper\TickPool.cs:line 96
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

[01:45:21]   Info: Exiting...
[01:45:21]   Info: Closing Mediaplayer...
[01:45:21]  Debug: AF stop old
[01:45:21]   Info: Closing QueryConnection...
[01:45:21]   Info: Closing QueryConnection...
[01:45:21]  Debug: Bot disconnected. Reason: LeftServer
```

**Comment by Splamy** [comment]
Ok some clarification, if you want the current global playlist you have to write
`!list show .queue`
What you get with `!list show` is your private playlist. You can add stuff to your private list with `!list add <link>`, and play it with `!list play`, you can save your own playlist with `!list save <name>` and later load it with `!list load <name>` or directly play it with `!list play <name>`

Nontheless it shouldn't crash the play command, I will look into it.

**Comment by xEzitx** [comment]
And as for this ? `[01:44:43]  Debug: MB Got message from Luke: !play [URL]https://www.youtube.com/watch?v=lgQprNvmsRQ[/URL]
[01:44:43]  Debug: SM User Luke created session with the bot
[01:44:43]  Debug: YT avail codecs: hd720 @ MP4, medium @ WEBM, medium @ MP4, small @ ThreeGP, small @ ThreeGP, audio/mp4; codecs="mp4a.40.2" @ M4A, audio/webm; codecs="vorbis" @ WEBM, audio/webm; codecs="opus" @ WEBM, audio/webm; codecs="opus" @ WEBM, audio/webm; codecs="opus" @ WEBM, 
[01:44:43]  Debug: AF stop old
[01:44:43]  Debug: AF ar start: Youtube ID:lgQprNvmsRQ
[01:44:43]  Error: Error return from player: Unable to create stream (Access is denied)
[01:44:54]  Debug: MB Got message from Luke: !add [URL]https://www.youtube.com/watch?v=dtCxmbFgnrc[/URL]
[01:44:54]  Debug: YT avail codecs: hd720 @ MP4, medium @ WEBM, medium @ MP4, small @ ThreeGP, small @ ThreeGP, audio/mp4; codecs="mp4a.40.2" @ M4A, audio/webm; codecs="vorbis" @ WEBM, audio/webm; codecs="opus" @ WEBM, audio/webm; codecs="opus" @ WEBM, audio/webm; codecs="opus" @ WEBM, 
[01:44:54]Warning: TH Web error: [403] Forbidden
[01:44:54]  Debug: YT Ruined!
[01:44:57]  Debug: YT Saved!`

**Comment by xEzitx** [comment]
This part is starting to annoy me,

 [18:37:35]Warning: TH Web error: [403] Forbidden

[18:37:46]  Error: Error return from player: Unable to create stream (The system cannot find the file specified)

`[18:37:19]   Info: [============ TS3AudioBot started =============]
[18:37:19]   Info: [=== Date:                     17 June 2017 ===]
[18:37:19]   Info: [=== Time:                         18:37:19 ===]
[18:37:19]   Info: [==============================================]
[18:37:19]   Info: [============ Initializing Commands ===========]
[18:37:19]   Info: [============ Initializing Modules ============]
[18:37:19]   Info: [=========== Initializing Factories ===========]
[18:37:19]   Info: [=========== Registering callbacks ============]
[18:37:19]   Info: [================= Finalizing =================]
[18:37:19]   Info: [============== Connected & Done ==============]
[18:37:34]  Debug: MB Got message from Luke: !add [URL]https://www.youtube.com/watch?v=1wYNFfgrXTI[/URL]
[18:37:34]  Debug: SM User Luke created session with the bot
[18:37:34]  Debug: AdminCheck called!
[18:37:34]  Debug: QC GetClientServerGroups called
[18:37:35]  Debug: YT avail codecs: medium @ WEBM, medium @ MP4, small @ ThreeGP, small @ ThreeGP, audio/mp4; codecs="mp4a.40.2" @ M4A, audio/webm; codecs="vorbis" @ WEBM, audio/webm; codecs="opus" @ WEBM, audio/webm; codecs="opus" @ WEBM, audio/webm; codecs="opus" @ WEBM, 
[18:37:35]Warning: TH Web error: [403] Forbidden
[18:37:35]  Debug: YT Ruined!
[18:37:38]  Debug: YT Saved!
[18:37:43]  Debug: MB Got message from Luke: !play [URL]https://www.youtube.com/watch?v=1wYNFfgrXTI[/URL]
[18:37:43]  Debug: AdminCheck called!
[18:37:43]  Debug: QC GetClientServerGroups called
[18:37:43]  Debug: YT avail codecs: medium @ WEBM, medium @ MP4, small @ ThreeGP, small @ ThreeGP, audio/mp4; codecs="mp4a.40.2" @ M4A, audio/webm; codecs="vorbis" @ WEBM, audio/webm; codecs="opus" @ WEBM, audio/webm; codecs="opus" @ WEBM, audio/webm; codecs="opus" @ WEBM, 
[18:37:43]Warning: TH Web error: [403] Forbidden
[18:37:43]  Debug: YT Ruined!
[18:37:46]  Debug: YT Saved!
[18:37:46]  Debug: AF stop old
[18:37:46]  Debug: AF ar start: Youtube ID:1wYNFfgrXTI
[18:37:46]  Error: Error return from player: Unable to create stream (The system cannot find the file specified)
`

**Comment by Splamy** [comment]
The `TH Web error: [403] Forbidden` error is normal and there is nothing I can do about that, this is some blocking youtube does.
And i guess the second one also has to do with youtube, the problem is it works fine for me, so it's really difficult for me to find out whats going wrong

**Comment by xEzitx** [comment]
Works fine now, no idea what I did to fix it, but my next query is regarding adding a full youtube playlist?

**Comment by Splamy** [comment]
`!list get <playlist>` to get and `!list play` to play. Consider `!list save` and `!list load` to prevent loading the entire playlist metadata (Loading locally is way faster, you should only need to get it again if the playlist changed)

**Comment by GiliceJani** [comment]
youtube-dl --rm-cache-dir works too
