### ISSUE TITLE
Decoding failed - DecoderPipe

### ISSUE THREAD

**Issue by blacktoby** [Splamy/TS3AudioBot#903]
Hello!
I'm trying to get the audio from the other clients speaking at the server.
For this I have written something very simple to test it:
```
 public class RecordAudioPlugin : IBotPlugin
    {
        private readonly TsFullClient client;
        
        public RecordAudioPlugin(TsFullClient client)
        {
            this.client = client;
        }
        
        public void Initialize()
        {
            client
                .Chain<AudioPacketReader>()
                .Chain<DecoderPipe>()
                .Chain<ClientMixdown>();
        }
        
        public void Dispose()
        {

        }
    }
```

Unfortunately the bot will crash after a few seconds of getting new packages, with following messages:
```
2021-02-17 20:26:13.2720|FATAL||Core.ExceptionHandler Critical program failure!
System.Exception: Decoding failed - InvalidPacket
   at TSLib.Audio.Opus.OpusDecoder.Decode(Span`1 inputOpusData, Span`1 outputDecodedBuffer) in C:\projects\ts3audiobot\TSLib\Audio\Opus\OpusDecoder.cs:line 74
   at TSLib.Audio.DecoderPipe.Write(Span`1 data, Meta meta) in C:\projects\ts3audiobot\TSLib\Audio\DecoderPipe.cs:line 40
   at TSLib.Audio.AudioPacketReader.Write(Span`1 data, Meta meta) in C:\projects\ts3audiobot\TSLib\Audio\AudioPacketReader.cs:line 22
   at TSLib.Full.TsFullClient.PacketEvent(ConnectionContext ctx, Packet`1& packet) in C:\projects\ts3audiobot\TSLib\Full\TsFullClient.cs:line 206
   at TSLib.Full.PacketHandler`2.FetchPackets(Span`1 buffer) in C:\projects\ts3audiobot\TSLib\Full\PacketHandler.cs:line 367
   at TSLib.Full.PacketHandler`2.FetchPacketEvent(Object selfObj, SocketAsyncEventArgs args) in C:\projects\ts3audiobot\TSLib\Full\PacketHandler.cs:line 353
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2021-02-17 20:26:13.2765| INFO||Core.Dispose TS3AudioBot shutting down.
```

Is there a bug or is there something wrong with my code?

Thanks!

PS: Great job with all you did! I love this project. <3

**Comment by Flakebi** [comment]
Hi,
the stacktrace refers to a `Write` call from `TSLib\Audio\AudioPacketReader.cs:line 22`, which is a couple lines further down in the source version I have. Could it be that you have an older version? Can you try the `develop` branch and see if it works there?

**Comment by blacktoby** [comment]
Thanks for the quick response!
Since I wrote the question I figured out, that taking out `ClientMixdown` makes it work without crashing. Unfortunately I need the separation between the clients.

I have to build the development branch myself? Could need some time to get this to work...

**Comment by Flakebi** [comment]
There are binaries available here: https://splamy.de/TSAudioBot/Home
The “experimental” ones are the `delevlop` branch, “stable” is the `master` branch.

**Comment by blacktoby** [comment]
The same thing with:  0.12.0-alpha.52
```
Unhandled exception. System.Exception: Decoding failed - InvalidPacket
   at TSLib.Audio.Opus.OpusDecoder.Decode(Span`1 inputOpusData, Span`1 outputDecodedBuffer) in C:\projects\ts3audiobot\TSLib\Audio\Opus\OpusDecoder.cs:line 91
   at TSLib.Audio.DecoderPipe.Write(Span`1 data, Meta meta) in C:\projects\ts3audiobot\TSLib\Audio\DecoderPipe.cs:line 47
   at TSLib.Audio.AudioPacketReader.Write(Span`1 data, Meta meta) in C:\projects\ts3audiobot\TSLib\Audio\AudioPacketReader.cs:line 34
   at TSLib.Full.TsFullClient.PacketEvent(ConnectionContext ctx, Packet`1& packet)
   at TSLib.Full.PacketHandler`2.FetchPackets(Span`1 buffer) in C:\projects\ts3audiobot\TSLib\Full\PacketHandler.cs:line 373
   at TSLib.Full.PacketHandler`2.FetchPacketEvent(Object selfObj, SocketAsyncEventArgs args) in C:\projects\ts3audiobot\TSLib\Full\PacketHandler.cs:line 358
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   ```

**Comment by blacktoby** [comment]
Could the issue be a stalling of the pipe?
See here:
```
lock (this.rwLock)
        {
          int length = Math.Min(data.Length, this.Buffer.Length - this.Length);
          data.Slice(0, length).CopyTo(this.Buffer.AsSpan<byte>(this.Length));
          this.Length += length;
          this.LastMeta = meta;
        }
```
What happens if the `Buffer` is full? Will it still unlock the `rwLock`?

**Comment by blacktoby** [comment]
Ok, so after making sure I have updated to the development build, nothing is happening anymore. My Test Pipe I wrote to just print out what will be chained through, has always null ``IAudioPassiveConsumer OutStream``:
```
 public class TestPipe : IAudioPipe
    {
        public void Write(Span<byte> data, Meta meta)
        {
            if (OutStream == null)
            {
                Console.WriteLine("OutputStreamIsNull!");
                return;
            }
                
            Console.WriteLine($"{meta.In.Sender}: {data.Length}");
            OutStream?.Write(data, meta);
        }

        public bool Active
        {
            get
            {
                IAudioPassiveConsumer outStream = OutStream;
                return outStream != null && outStream.Active;
            }
        }

        public IAudioPassiveConsumer? OutStream { get; set; }
    }
```
I will return to the master version. The error is still created at the same line with the new version (see above). 

I've downloaded the dotnet 3.1 Version and compiled against the dlls shipped with that package. Am I doing this the right way?
Maybe the error lies there?

**Comment by blacktoby** [comment]
I found a fix or workaround, I have no idea.
In ``DecoderPipe`` Line 40, I did a change to:
``if (OutStream is null || !meta.Codec.HasValue || data.Length < 2)``
Reason:
The last byte of a client before it stops sending audio is only a simple "1". This value will crash the decoding.

This fix won't be the best and maybe it has to be fixed somewhere else. But for now this is working for me!

**Comment by Flakebi** [comment]
Right, small packets signal the end of a stream (when a client stops talking).
This is handled in the `AudioPacketReader`:
https://github.com/Splamy/TS3AudioBot/blob/4f17b2971e03bee94d1e630a2b5ce37d8a15e5ca/TSLib/Audio/AudioPacketReader.cs#L25-L26

So, if you put an `AudioPacketReader` before the `DecoderPipe`, it should work.

I tested the code you posted with the following pipeline and it worked fine (using the develop branch).
```cs
		client
			.Chain<AudioPacketReader>()
			.Chain<DecoderPipe>()
			.Chain<TestPipe>()
			.Chain<ClientMixdown>();

```

**Comment by blacktoby** [comment]
This is exactly the order I have it.
I think the problem still remains: Imagine having a packet with a size of 6. The slicing in the `AudioPacketReader` will change the length to 1. So maybe there are packages with length of 6 incoming and therefore I get packages of length 1 in the decoder?

**Comment by Flakebi** [comment]
You’re right, I missed that the packed id, etc. gets stripped off in the `AudioPacketReader`, so it should check for `length < 6`. I never saw invalid packets with more than one byte content.
I can’t reproduce this issue, somehow my teamspeak client doesn’t send these packets anymore, so I hope this fixes the exception.
