### ISSUE TITLE
import "mix" lists from youtube

### ISSUE THREAD

**Issue by liveuser1** [Splamy/TS3AudioBot#905]
bot command
"!list import list_1 https://www.youtube.com/watch?v=v4xZUr0BEfE&list=RDGMEMJQXQAmqrnmK1SEjY_rKBGA&start_radio=1" gives "Error: Could not load. (youtube: youtube-dl failed to load the resource.)".

on current develop version:
```
2021-02-24 13:01:55.7151| INFO|Core|Setup.LogHeader [============ TS3AudioBot started =============]
2021-02-24 13:01:55.8058| INFO|Core|Setup.LogHeader [ Date: Wednesday, 24 February 2021 13:01:55
2021-02-24 13:01:55.8933| INFO|Core|Setup.LogHeader [ Version: 0.12.0-alpha.56/develop/fcc3ab5e
2021-02-24 13:01:55.8933| INFO|Core|Setup.LogHeader [ Build: Release
2021-02-24 13:01:55.8933| INFO|Core|Setup.LogHeader [ Platform: Debian GNU/Linux 9 (stretch) (64bit)
2021-02-24 13:01:55.8933| INFO|Core|Setup.LogHeader [ Runtime: .NET Core (3.1.12) ServerGC:True GC:SustainedLowLatency
2021-02-24 13:01:55.8994| INFO|Core|Setup.LogHeader [ Opus: libopus 1.2~alpha2 (x64)
2021-02-24 13:01:55.8994| INFO|Core|Setup.LogHeader [==============================================]
2021-02-24 13:02:15.4683|DEBUG|0|Bot.OnMessageReceived TextMessage: {"NotifyType":"TextMessage", "InvokerId":"12", "InvokerName":"Wedny", "InvokerUid":{"Value":"EYNCtSc4lz5i+kj5ZOcFl+AN7R4="}, "Message":"!list import list_1 [URL]https:\/\/www.youtube.com\/watch?v=v4xZUr0BEfE&list=RDGMEMJQXQAmqrnmK1SEjY_rKBGA&start_radio=1[\/URL]", "Target":"Channel"}
2021-02-24 13:02:15.4844| INFO|0|Bot.OnMessageReceived User Wedny requested: !list import list_1 [URL]https://www.youtube.com/watch?v=v4xZUr0BEfE&list=RDGMEMJQXQAmqrnmK1SEjY_rKBGA&start_radio=1[/URL]
2021-02-24 13:02:15.4926|DEBUG|0|SessionManager.GetOrCreateSession ClientId 12 created session with the bot
2021-02-24 13:02:15.4984|DEBUG|0|Bot.CallScript Calling script (skipRights:False, answer:True): !list import list_1 [URL]https://www.youtube.com/watch?v=v4xZUr0BEfE&list=RDGMEMJQXQAmqrnmK1SEjY_rKBGA&start_radio=1[/URL]
2021-02-24 13:02:18.5644|DEBUG|0|YoutubeDlHelper.RunYoutubeDl youtube-dl failed to load the resource:
ERROR: This playlist type is unviewable.
2021-02-24 13:02:18.5848|DEBUG|0|Bot.TryCatchCommand Command Error (Could not load. (youtube: youtube-dl failed to load the resource.))
TS3AudioBot.AudioBotException: Could not load. (youtube: youtube-dl failed to load the resource.)
   at TS3AudioBot.ResourceFactories.ResourceResolver.LoadPlaylistFrom(ResolveContext ctx, String message, String audioType) in /home/TS3AudioBot/TS3AudioBot/ResourceFactories/ResourceResolver.cs:line 174
   at TS3AudioBot.MainCommands.CommandListImport(PlaylistManager playlistManager, ResolveContext resolver, String listId, String link) in /home/TS3AudioBot/TS3AudioBot/MainCommands.cs:line 980
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.ExecuteFunction(Object[] parameters) in /home/TS3AudioBot/TS3AudioBot/CommandSystem/Commands/FunctionCommand.cs:line 81
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in /home/TS3AudioBot/TS3AudioBot/CommandSystem/Commands/FunctionCommand.cs:line 203
   at TS3AudioBot.CommandSystem.BotCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in /home/TS3AudioBot/TS3AudioBot/CommandSystem/BotCommand.cs:line 131
   at TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in /home/TS3AudioBot/TS3AudioBot/CommandSystem/Commands/CommandGroup.cs:line 63
   at TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in /home/TS3AudioBot/TS3AudioBot/CommandSystem/Commands/CommandGroup.cs:line 63
   at TS3AudioBot.CommandSystem.Commands.RootCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in /home/TS3AudioBot/TS3AudioBot/CommandSystem/Commands/RootCommand.cs:line 41
   at TS3AudioBot.CommandSystem.CommandManager.Execute(ExecutionInformation info, String command) in /home/TS3AudioBot/TS3AudioBot/CommandSystem/CommandManager.cs:line 401
   at TS3AudioBot.Bot.<>c__DisplayClass42_0.<<CallScript>b__0>d.MoveNext() in /home/TS3AudioBot/TS3AudioBot/Bot.cs:line 503
--- End of stack trace from previous location where exception was thrown ---
   at TS3AudioBot.Bot.TryCatchCommand(ExecutionInformation info, Boolean answer, Func`1 action) in /home/TS3AudioBot/TS3AudioBot/Bot.cs:line 530
```
from console:
```
root@:~# youtube-dl --no-warnings --yes-playlist --flat-playlist --dump-single-json --id -- 'https://www.youtube.com/watch?v=v4xZUr0BEfE&list=RDGMEMJQXQAmqrnmK1SEjY_rKBGA&start_radio=1'
result - json playlist as expected

root@:~# youtube-dl --no-warnings --yes-playlist --flat-playlist --dump-single-json --id -- RDGMEMJQXQAmqrnmK1SEjY_rKBGA                  
ERROR: This playlist type is unviewable.

```

Found this in yt-dl git: https://github.com/ytdl-org/youtube-dl/issues/27502

It shouldn't be a problem to feed full link to youtube-dl for list importing, right?

**Comment by Flakebi** [comment]
Thanks for the report and the detailed description!
It’s fixed in the `develop` version.

**Comment by liveuser1** [comment]
It works, thank you for quick response.
