### ISSUE TITLE
PacketHandler

### ISSUE THREAD

**Issue by Minik7k2** [Splamy/TS3AudioBot#915]
**Describe the bug**
The error causes a large accumulation of logs. Finally, it kills the music bots from the server

**To Reproduce**
This is happening at randomow and I am not able to reproduce it.

**Version**
Version: 0.11.3
Branch: master
CommitHash: 24c92032b61bf8bb663f379e64b812de818218ed

**Platform**
Debian 10 64bit
dotnet --info:
.NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.202/

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  5.0.202 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.                                                                                                                                                             App]
  Microsoft.NETCore.App 3.1.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Log**
[============ TS3AudioBot started =============]
[ Date/Time: Friday, October 16, 2020 7:46:42 PM
[ Version: 0.11.3/master/24c92032
[ Platform: Debian GNU/Linux 9 (stretch) (64bit)
[ Runtime: .NET Core (3.1.9) ServerGC:False GC:SustainedLowLatency
[ Opus: libopus 1.2~alpha2 (x64)
[==============================================]
```
2021-04-24 01:37:04.0943| WARN|0|PacketHandler`2.FetchPackets Dropping not decryptable packet: 06 F7 4C 81 BE 65 A6 33 AF 79 00 19 38 5E 83 E7 8F 50 72 B7 28 09 80 CC FC CD FB 9C 0F 63 26 35 62 A1 FB B6 D5 E6 90 92 03 E4 C4 FF 89 CF 4C 9C AF 69 05 14 9F 10 73 B4 D9 2C 39 C0 5F 32 3C 2F B8 52 E6 F2 67 CC 43 1C 58 68 AA 62 0E 91 B9 18 6F 8B 34 EC 90 C2 9A 97 0E 20 FA 20 B8 0F C2 F2 11 77 C3 F2 F9 DE 83 B7 F8 3B 96 A0 F8 E2 4D 2C 78 35 C2 BC 20 41 4F CF 04 2C 82 34 B1 D6 BB E8 BC 3B 38 1A DC 31 DF F5 D7 2D A9 30 DC 78 12 FE 75 F3 24 39 9C 87 D1 AE 33 AC 48 EC 29 3B 6D D0 5F F6 4C EB F3 92 60 D0 1D 0B CA 02 75 CB 7F DC 87 B3 B8 A2 FA E4 72 0A CF 33 06 FC 04 1E C2 6D B2 36 1A 5A 31 45 CD 23 BE 06 1B 0A 5D FE 39 E2 8B 1D 83 49 3B 2A B5 
2021-04-24 01:37:04.1141| WARN|0|PacketHandler`2.FetchPackets Dropping not decryptable packet: 49 28 7B AC D0 43 41 73 AF 7A 00 2E AE D5 59 BD 8C DF D4 D4 08 8F 93 23 43 19 5D DE 53 A3 04 C4 4C 6E DA BC 3A 87 9F 5B 92 68 C8 DA C6 DE 73 A9 68 14 7C 8F 29 70 24 EF FD C7 AA 96 0A D6 34 96 8C 15 05 60 32 FD 30 4B FF D6 CE 4B B3 B8 4B 60 A6 2F 14 2D C4 E0 42 5D C7 31 EA 1D 89 96 05 F5 37 07 5F 86 D4 4F EC 34 D8 92 B2 5D B5 5B EB 64 D1 53 E9 7A 69 19 55 9F 3D 10 E5 6A 9B 19 90 9B BE 49 8C 98 8F B8 1A 9F 51 04 38 B1 B7 EE A3 FB 23 CD 48 14 5A AA 49 A3 8C E5 ED 7B 43 EA 28 3E A3 02 37 EB DE AA BB 1B F2 8C A6 4E 82 AD EF 97 3E BF 00 67 FC FA EC 50 E4 5D F0 A0 1E 77 90 02 40 D2 99 87 36 4D E1 84 C9 5C 4B 53 91 1D E9 DF 2C 19 3F 6D 3E 63 B9 
2021-04-24 01:37:04.1356| WARN|0|PacketHandler`2.FetchPackets Dropping not decryptable packet: 1D 7C 1C E7 29 80 8B E0 AF 7B 00 0B 8E F6 A7 4E BD 51 49 24 44 E2 28 35 46 E4 87 48 80 A1 BD 0C 1D EA BF C2 73 D0 4A 7B 07 57 E9 57 CF F1 C3 4B 3F E0 17 B9 28 DF 7C AB F2 47 86 94 DA 52 3D 02 F3 A4 D7 6C F6 D3 B7 A0 41 BD 97 76 26 A5 29 8A 79 03 E4 58 8D A1 33 1C B8 86 D3 D9 3A A1 F7 CA E4 C4 F8 DE FC 3E 2F 57 24 D9 A0 ED 58 D1 E7 A5 6F A0 F4 FA DA 3F 11 B5 5E 5E F4 27 A6 29 21 C9 10 0C 8D 9F 8E DC EE A4 67 32 36 11 91 84 C3 45 E0 FA B3 09 1F C0 14 16 1E D6 E7 86 6A 2C E1 05 B6 95 F4 6C 9D 11 C0 47 90 37 32 95 51 0E 93 E6 25 23 14 E9 C3 C0 74 FE 36 54 12 F9 D9 16 25 8C 6C 11 1E AA A3 C3 FA 60 A8 1B 25 A8 2F 92 D2 A5 3D 0E ED 03 13 80 1B 
2021-04-24 01:37:04.1552| WARN|0|PacketHandler`2.FetchPackets Dropping not decryptable packet: 33 8F 35 E4 16 49 EF E0 AF 7C 00 19 A3 DC A2 47 AC 35 09 47 FF CF E1 32 25 EC 42 AD 70 A6 46 EB 61 AE B7 46 35 F6 72 23 E7 A8 71 22 0F 52 E4 58 64 F9 5F 50 E3 FC 5C 0A 76 EA 8E 3B EA 3A DC EC 0E 86 D1 97 22 31 AD 61 AF 03 F6 6F 65 1E FD 03 A5 85 D2 9E AD 41 87 1B 4D 3F FA 69 53 9A 90 FF D7 45 BC 34 D4 99 D0 79 DF 5E 42 79 54 2C F3 23 24 AC 87 36 FC 93 87 AD 14 0D CE 90 9E D6 09 FE 62 5C 83 01 FD DD B3 EF 36 37 7A E1 40 54 00 34 47 C7 FA 1F 51 83 B5 AE 4B 62 7D B5 D9 EC 6E 59 29 C8 0A 9F B1 D1 24 3F CF 1A 1A 67 45 34 D0 3D 00 F9 1F 3A 87 72 EC F7 CD 74 EB 39 FD D2 64 54 9D 25 F1 89 FB FC 91 5F 1E F9 FA 02 46 5F 16 A4 EE A8 58 B6 2E D8 7C 
2021-04-24 01:37:04.1746| WARN|0|PacketHandler`2.FetchPackets Dropping not decryptable packet: F9 DA D9 E5 EC 76 A2 6A AF 7D 00 F2 DD 6F 92 36 D2 81 2B 2F 73 7C 27 31 A8 F3 A7 9A 21 65 F8 FF D6 D8 16 AA 27 C0 65 65 9B 69 0E BE FB 68 20 8D CE DD C6 FE 1F 88 55 58 10 29 43 59 6E 08 03 2B F7 A1 B9 8F 89 BD 4E CB 02 C8 E0 7E 73 9D 31 9F 64 1F 3C 9A BD 76 B2 E9 2B 07 A6 2F 19 FF 6A 46 63 D3 14 04 73 43 0A B6 3A EB D3 98 C5 29 6B FB 9E FB 84 D1 5B 21 8C A2 71 9A E0 DA D7 D3 36 64 5D 9D 49 DC B9 AF 23 5E ED AD C9 82 7D 69 F2 8E 8C CB 69 D0 DB D3 E8 F5 F1 F5 85 3E 65 0D 80 1A 02 22 A1 07 5C 5B E9 47 D9 73 19 AB 55 80 16 17 1A 93 F5 66 D7 E4 38 C7 0E 97 A1 D9 66 A9 1C E4 91 FC FA 13 0E 5C 4E 2B 56 CD AE 9E AE EA 25 36 FE 0C 4A E3 EC FD EA 
2021-04-24 01:37:04.1940| WARN|0|PacketHandler`2.FetchPackets Dropping not decryptable packet: C9 B2 E9 8A 80 21 81 0E AF 7E 00 5C 62 79 44 94 86 61 CD BA A8 30 89 D9 83 E0 A2 95 6E FA 49 45 8A CA 49 5B 61 EA EC 51 9C F4 4F E2 BC 45 7F C8 92 10 5B 70 86 2C D4 CC D1 20 5D 80 9A 91 60 BD EE 13 BA 90 12 DB CB 0E 6B DB 90 2F D7 ED E4 16 E7 A7 AB 9E AA D8 84 B4 47 40 48 E6 EF B8 62 7F 0A BB 06 C7 33 5A 28 02 8E DF 2B 2F 71 1A 6E 3A 56 1F A1 9E 46 6E EC 56 56 4D 2D 4B 12 0D 50 61 4D 1B D2 2E 98 D4 C8 25 20 96 76 95 A2 B9 A4 04 F8 40 AA 93 CD 31 55 CA 0E E8 38 9A 88 1D FB 64 84 03 81 ED 60 1F 5D BC DF C5 69 C4 40 B4 80 38 1C 81 6E 82 5F AC E3 2E CA 50 25 95 27 14 89 A4 0B 19 89 7C 5C 50 D4 E8 DF AB 1C DF EE 17 57 14 B2 DA D8 E2 48 E7 2C 
2021-04-24 01:37:04.2155| WARN|0|PacketHandler`2.FetchPackets Dropping not decryptable packet: 92 9F FC 03 9F 4B D1 3D AF 7F 00 A3 DE 77 A7 04 B0 16 8D 70 03 71 8C E6 D3 59 F3 C5 5E 84 BF 06 50 81 6A F5 90 3C 41 DF 1C D8 C0 89 2A DF 18 06 67 CC 8B A6 DB BB 7D B1 26 59 95 80 F8 89 20 41 66 26 81 60 40 28 95 D7 F8 9A 9D 66 B2 2A A4 EE 15 95 2E 90 74 2E 59 22 41 BA 97 29 28 B2 D9 4D C7 A0 7F 7B 93 7B 6D 39 BC 4F 89 C6 56 A1 3F 5B 3F A3 07 97 12 A3 B0 76 78 F8 22 0B A5 86 5F AD 3B 97 EA 01 23 76 F1 D6 49 B2 F7 0C C2 9C FD 4F 62 B0 72 A2 5B 7E E5 95 C3 DD 3D 1F C5 17 CA D5 F6 A6 D1 10 B7 C4 68 22 3C 11 9C CB D1 E4 FA 2E 21 CE 05 D8 36 80 83 ED 25 4D A2 D4 CA 67 BD 64 84 B5 BB 14 66 94 FE B6 BF B2 72 24 5B 4C 2E 86 B3 15 3B 6F 9E C5 90 
2021-04-24 01:37:04.2351| WARN|0|PacketHandler`2.FetchPackets Dropping not decryptable packet: 9D 98 4C 46 4E 2A E4 95 AF 80 00 13 F6 35 07 70 45 BA 99 FA 20 41 88 7D B2 68 A4 C2 0C 26 3D 28 01 7D CC A0 43 97 19 C1 0F AA D2 1E 77 AF 06 55 7E AA 6A 61 16 91 F5 9F 99 CE 51 84 D8 C9 5D DD F9 9E CC B8 36 A9 2E 10 8C FA 27 A8 34 7C EC 20 CA 69 83 23 F5 B0 BF 00 2F 15 70 56 AF 53 3C 49 A6 17 24 E1 88 71 7D A5 46 87 C3 58 81 E7 69 5B 04 BD 80 07 83 D2 07 9B 10 86 C9 BC E3 5F DD 4D 3B 18 38 74 E0 5C D4 76 A2 E1 7F 32 D9 66 6C 1F 5A AA 7B 8E B0 2E C1 92 BE 2C 55 E4 05 08 B2 76 DF 90 3E 4C E3 88 54 70 1E D0 77 06 F7 AC C8 12 14 F8 14 21 A2 23 A4 7F 50 F7 6B 7D B1 3C 80 1A 92 DE B3 32 DE B2 39 06 08 E4 CB 76 AC 87 6B 0C D0 F9 CF 4B C8 79 E2 
2021-04-24 01:37:04.2550| WARN|0|PacketHandler`2.FetchPackets Dropping not decryptable packet: 94 77 AC C4 B5 D6 A9 F3 AF 81 00 5F F7 30 34 00 E6 E4 71 B9 D4 23 EB 09 36 C2 A7 7C 57 1D 9D D7 27 4E 91 5B 7C D1 76 DB 63 C0 C2 C6 7D F3 E1 A6 12 AA 0D 46 FA FC E2 49 44 A7 8F C6 50 41 DC 5A 67 8A 44 AC 93 E5 41 00 E5 EC 12 A1 F5 B9 F7 69 7A 3A FF A1 0D 61 98 65 49 D7 DA FB 30 2F E2 51 52 4D 6E 14 B7 8C 54 D9 E9 8D 79 D6 55 A5 E8 EC 08 F4 0D 4B A9 48 AF 30 C2 60 88 41 E6 5A B3 E2 81 FD 5C DB 96 E3 92 C7 6B 87 5B 43 21 E8 CB 80 6A B3 8C A3 73 E8 5E 07 84 F4 47 2B 76 E1 76 80 66 68 93 D5 D5 38 D2 EC 91 0C 09 26 65 4F EF FE 43 48 18 C4 19 14 85 48 AE B6 DB 80 6B 9E EA 12 DF 3A 4B 75 5C BA 7E 5C F5 A5 80 F1 44 BB 54 05 44 1C CD D1 F7 81 BB 
2021-04-24 01:37:04.2766| WARN|0|PacketHandler`2.FetchPackets Dropping not decryptable packet: 00 B0 F2 93 4D 7F A8 8E AF 82 00 F9 28 DE 81 6F 5F EC E5 3D C5 40 35 37 9E 9D 4F FC F4 D0 E1 AF 0A D4 F1 C4 8F F2 8E 8D ED 21 C6 7D 13 B6 C7 F5 9D DE B9 20 CF EF DC 6F 04 A7 4B 94 00 62 94 90 81 C7 D1 FB C4 68 4C AD 74 58 C3 07 B2 3A AB F1 F1 9F 1A 0C 47 E7 A8 F0 6A BB FA F1 20 23 E8 25 65 9C 85 48 71 7C 48 9D 25 87 6F 92 F7 31 09 1E 18 D0 61 BA FE DE C8 77 24 68 42 B3 5E 72 45 71 A5 2D 2F 34 CA AC 12 2D 65 70 B9 5A E4 64 7C 48 D6 77 97 FF 8E B4 82 7B 90 34 A3 48 53 29 AE D1 4E 95 D1 0D AC E8 CC AB BC D9 43 BB 6E FE 1D 76 C2 21 50 B8 32 95 F6 7F 1E FB 4F 97 8B 68 15 65 06 66 6F 4A 5F 06 7E F9 42 B3 D2 E3 6B A3 77 3B 21 7E 3F 26 DA 36 09 
2021-04-24 01:37:04.2939| WARN|0|PacketHandler`2.FetchPackets Dropping not decryptable packet: E4 E6 00 D6 F6 20 29 DE AF 83 00 79 FA 3A E7 47 26 8F 37 57 C8 F0 15 AB 26 2D BE 07 1A 18 DB 60 1A 62 01 54 49 3B 53 A5 41 93 7F 3C B8 AE C3 7B DB 1B 24 58 A2 3F 77 47 1E 99 0A FA C3 9A FE 7E B9 E3 23 BE 89 F2 EB AC 01 13 F6 75 AE 4E 16 CC 01 40 74 C7 E9 60 3F 35 6E A9 D0 D2 F9 40 9F CF 55 6A C9 5B EB 9C F6 9C 84 37 61 5A 67 04 3F 74 CD F0 54 E7 D4 42 E8 8A F8 35 55 2D 13 D3 98 F1 3D 17 43 18 B6 72 17 88 DA 66 B7 F1 93 5E 6F 34 A7 2B 72 23 48 9A DE 6A 9C 7A 4B 1F F3 5E 1A A2 15 86 E3 91 10 32 EE 81 D2 4B 1A DB 8E D1 21 1C B6 77 F7 AF AE 44 C1 B4 6B 87 BD A1 E3 41 D2 E3 2A 28 93 9E 3B 7E 4D 4F 43 1D B6 2E F0 04 F7 DD 4D 04 8B 96 A5 6F FE 
2021-04-24 01:37:04.3154| WARN|0|PacketHandler`2.FetchPackets Dropping not decryptable packet: D9 6F 3A FB 52 9D 55 F8 AF 84 00 B4 E9 1A 50 78 A0 25 56 60 8B 88 4D A6 A0 D0 75 3E 46 68 6D 04 A1 32 EB D2 B0 41 29 57 83 88 00 24 49 69 90 0D 62 FA DC 50 A6 44 41 61 87 D7 DB 9C A2 57 32 07 1A D6 66 C6 4E 56 16 86 9B 62 80 02 AF CE 13 82 B6 D8 92 4E FE 31 AC F5 70 D0 3E 1A 69 CD 68 E7 FF 90 B2 84 33 7A 4E B7 CB F8 26 B2 9E 3F 7E 6D 73 01 C9 9A EC 1A 1B DF 28 4B 74 01 D1 69 1E CC 0D E9 0D 69 38 56 E8 67 2E 1E 18 0E DE D1 86 F9 12 F1 04 EB 32 19 DC 44 E8 F5 B4 32 16 2A 4B B3 96 0F A9 52 1F DD 44 96 30 53 DD 40 B7 04 0C 4B D2 F7 EA 3B C6 C7 A1 36 64 73 D5 EC 5C 93 95 1A B4 97 EB D0 FF 47 B6 97 2A 13 08 F0 A5 B0 EB FB FD B6 2B 33 3B 27 BA 
2021-04-24 01:37:04.3354| WARN|0|PacketHandler`2.FetchPackets Dropping not decryptable packet: 97 BD 24 31 5D 3F 6A 38 AF 85 00 16 3B B9 21 F1 49 99 93 5F 0F CE 19 2F 46 A0 E3 84 40 BB 58 7C B4 E1 3F 5F 51 A5 88 6A 59 02 26 A4 87 6D 6C 8D 91 DE 40 E6 50 E6 10 5B 21 5F DC A0 A7 BE 95 FD D0 F6 28 2F 1E A4 54 F4 D6 85 E4 A9 D6 04 C5 63 6A E2 DF F0 56 51 A0 BD E1 E0 17 2F 43 9C 2C 06 8D EE 7B 1E C5 7C 6C B3 B3 7E 0E A9 C0 43 1E 08 EB E1 B2 C8 18 8F CF 6A 6F 73 6E E8 BE 69 CA 7C 99 DB 30 64 B6 4D F1 D9 13 AF 12 7F 2C 22 05 29 05 5B 4F 36 83 A3 52 43 8B 03 C1 6E 81 40 3D 26 08 D3 F3 C7 20 56 84 02 A3 B8 BE 65 2B 07 63 D0 F0 51 E2 1F 70 67 07 92 CF 09 AF DB EE 0C 2E 1A 0D 0E 8F 34 80 B4 22 FA 7E AB C2 36 6D 26 B7 77 D1 83 67 0C CF 13 58 
2021-04-24 01:37:04.3549| WARN|0|PacketHandler`2.FetchPackets Dropping not decryptable packet: 7A 5E 98 B0 B7 76 FC 87 AF 86 00 6F EC CA 5C 74 4C 79 C2 3C 1B 61 2C A7 64 FF 99 4C 45 A8 D2 E2 5C 1C 71 E1 D6 BC E4 1F EC 1D FC E2 A1 62 34 85 CD 37 64 90 81 85 58 09 D3 E6 6F A2 C5 EB 5B 1F DC 4C 3D D0 E3 7E B7 30 46 7B 16 8E B7 47 C7 04 D2 A6 0D 96 25 4B AA AC E2 55 D6 E2 CD 68 81 E0 C3 10 4F DD BB 02 40 B9 A1 6B BE 78 61 F5 65 AF 07 9E 26 49 55 3E 7E D3 08 45 92 A4 4E 55 E9 DB 07 9D 98 71 97 5D 31 8B B5 C6 83 89 73 AE 51 5C BE 59 01 83 64 AF 27 A5 62 0A DD 19 12 2D 77 7C 69 D5 B4 DA D7 58 83 71 2C 1E C4 99 1C DD 34 C2 A2 45 16 9C EB 73 38 FD FB 1D 98 D8 D8 68 B7 E7 14 50 2E 66 66 80 22 41 89 9B A1 8A 86 AD FC C8 0B E5 95 B6 27 E4 9C 
2021-04-24 01:37:04.3743| WARN|0|PacketHandler`2.FetchPackets Dropping not decryptable packet: E1 8F E1 8F B1 BF 94 C5 AF 87 00 14 2D 3E BF 55 07 38 14 97 85 EE CD 19 A3 87 17 B0 62 54 63 E4 80 86 26 DD AF 0E F9 C0 50 1C 43 CC 8C E3 92 5B 37 23 F8 75 35 B6 F5 01 72 80 CF 51 3D 67 03 28 02 33 C0 30 28 A6 CB A2 D5 F3 9F 80 95 5B 74 26 49 99 B8 89 ED 54 C4 80 5E 63 A0 A1 C6 B2 B4 50 37 D2 A2 1C 2B 5F 8C 30 45 04 E0 B3 CB 19 E8 DF 7D B4 D8 30 3A B8 57 E4 88 AF FE 85 E3 25 51 09 5B 8F 30 A3 25 03 7E E5 C9 D2 73 D6 E2 12 11 48 9B 8E 91 EB 27 3C 4F 4E 75 14 68 CD BC 51 51 3F 47 02 62 44 9F FE 8D AA F9 81 59 F2 64 51 AE 06 76 AA 31 24 B0 47 95 53 B1 55 6A BA 2E 09 2A 82 17 8E 2C 08 E6 B2 A8 FE 61 AC FB E7 6E B4 09 14 B8 5A A4 36 7A 7F DD 
2021-04-24 01:37:04.3956| WARN|0|PacketHandler`2.FetchPackets Dropping not decryptable packet: EC 52 76 6A 63 36 6B E0 AF 88 00 29 4C 19 DD 78 BF A9 7E FA C4 E6 51 20 ED 5E 3C 76 E4 28 3F ED A9 04 5C 0C 61 3D C8 0F A1 93 3B BA 21 6F 0B A8 D6 DC 14 F7 97 FE 96 3B 96 D4 6A 61 2E 39 79 CD 17 4B D4 56 C8 54 14 AA F9 50 10 EE 1F 29 6A 90 F5 03 9B 79 98 FC 82 F1 9F 81 DD AC BE 3A 86 53 0D 25 C3 4F 9B 58 0F C5 85 DE BF 9F 28 21 B8 A9 9F B9 8D 45 97 7D 4E E3 9C C8 CE F4 05 B6 AC 8B 6C 7E 52 5F D3 6B 57 9C 0B 77 BA F7 ED D6 F1 57 7E 37 ED 12 43 88 2D A0 18 7B 8B 31 DE 30 08 7A FE 04 CB 0F 96 E2 3C D0 61 CE 46 BC B4 A5 3C 87 00 05 0F 0C 32 B6 29 D6 3B 32 C6 C8 F0 89 6B 4A 91 D0 3F B3 7E B1 01 16 51 BD 28 E5 97 DA 48 1E D8 F4 A1 00 F0 20 CE 
2021-04-24 01:37:04.4152| WARN|0|PacketHandler`2.FetchPackets Dropping not decryptable packet: 92 E4 32 C1 5B E9 EF 16 AF 89 00 33 CC 2D 4A 01 12 FF BB D0 55 04 74 36 01 53 FC 12 77 0C 3A E5 9D DD 80 63 C3 BA 90 E8 99 89 6F C0 E9 BE A3 34 02 0F 2F 63 D4 12 0B F9 BE 83 84 1A 04 44 06 BF 2A ED 35 FF D6 41 19 9B 30 89 BC 34 40 A4 6B C7 40 CB A3 41 7E 3D 2A 1D 66 B0 A4 69 C2 9D B8 02 E7 22 27 36 0B CD DC AC 88 99 10 F1 9F 76 ED 8F 91 74 AF 64 A2 C2 14 B4 B7 87 23 05 55 07 8D F3 16 78 B8 CF D0 1C 22 D9 F0 51 FD C5 F5 BF A6 81 D8 82 C0 5F CB A2 15 90 98 7C 27 7C CD 18 2D 93 C6 B8 4D AE A5 4F 40 0D A3 4A 97 43 30 5E 30 4F 56 DC 05 30 46 95 FF AA 2B 9A 4F 04 41 B4 9B 0D 0A 1E C9 D1 88 EE DC D0 08 6E AF B2 E1 EB 76 B4 59 B7 AA 1F B0 7B 8A 
2021-04-24 01:37:04.4426| WARN|0|PacketHandler`2.FetchPackets Dropping not decryptable packet: 27 F7 14 25 2F 05 31 3B AF 8A 40 1C 95 B8 27 FE 88 
2021-04-25 21:07:35.2071|FATAL||Core.ExceptionHandler Critical program failure!
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at System.Text.ReusableTextReader.ReadAllText(Stream source)
   at Interop.procfs.TryReadFile(String filePath, ReusableTextReader reusableReader, String& fileContents)
   at Interop.procfs.TryParseStatFile(String statFilePath, ParsedStat& result, ReusableTextReader reusableReader)
   at System.Diagnostics.ProcessManager.CreateProcessInfo(ParsedStat& procFsStat, ParsedStatus& procFsStatus, ReusableTextReader reusableReader, String processName)
   at System.Diagnostics.ProcessManager.CreateProcessInfo(Int32 pid, ReusableTextReader reusableReader)
   at System.Diagnostics.Process.EnsureState(State state)
   at TS3AudioBot.Environment.SystemMonitor.CreateSnapshot() in C:\projects\ts3audiobot\TS3AudioBot\Environment\SystemMonitor.cs:line 62
   at TS3AudioBot.Helper.TickPool.Tick() in C:\projects\ts3audiobot\TS3AudioBot\Helper\TickPool.cs:line 85
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
2021-04-25 21:07:38.0531| INFO||Core.Dispose TS3AudioBot shutting down.
2021-04-25 21:07:40.4107| INFO||Bot.Dispose Bot (0) disconnecting.
2021-04-25 21:07:57.0305| INFO||WebServer.Dispose WebServer is closing.
```

**Comment by Splamy** [comment]
Could you update to the latest master and see if this still happens?

**Comment by Minik7k2** [comment]
just such information. "2021-05-04 23:13:37.5770| WARN|0|PacketHandler`2.ResendLoop Previous resend tick didn't finish"

**Comment by Splamy** [comment]
I have pushed a fix to **develop** which fixed a bug with en/decrypting packets.
Please try it out to see if this still happens

**Comment by Flakebi** [comment]
I hope this was fixed. If not, please comment or reopen the issue.
