### ISSUE TITLE
Critical program failure! Bot shutdown!

### ISSUE THREAD

**Issue by tomgewiese** [Splamy/TS3AudioBot#917]
My node always turns off and then the error comes.

> 17:54:57.3178|FATAL|2| Critical program failure!
> 17:54:57.3239| INFO|2| TS3AudioBot shutting down.
> 17:54:57.3239| INFO|2| Bot (1) disconnecting.
> 17:54:57.3239| INFO|2| Bot (0) disconnecting.
> Unhandled exception. System.InvalidOperationException: context should be set
>    at TSLib.Full.TsFullClient.<ProcessEachInitIvExpand2>d__610.MoveNext() in C:\projects\ts3audiobot\TSLib\Full\TsFullClient.cs:line 281
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
>    at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
>    at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
>    at System.Threading.QueueUserWorkItemCallback.Execute()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
> Aborted

Debain 10 LXC
dotnet 5.0.202

**Comment by Splamy** [comment]
Which AudioBot version are you running?
