### ISSUE TITLE
Bots Timingout

### ISSUE THREAD

**Issue by DyhnenTv** [Splamy/TS3AudioBot#928]
The bots have an increased ping between 800 and 1200, so lag and timing all the time. The following error occurs. 

2021-06-23 08:55:43.0863|ERROR|23|FfmpegInstance.ReadStreamLoop Failed too many times trying to access ffmpeg. Closing stream.
System.IO.IOException: Broken pipe
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.WriteSpan(ReadOnlySpan`1 source)
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at TS3AudioBot.Audio.FfmpegProducer.FfmpegInstance.ReadStreamLoop(Id id) in C:\projects\ts3audiobot\TS3AudioBot\Audio\FfmpegProducer.cs:line 426

**Comment by Flakebi** [comment]
That looks like your server may be running low on memory or too many processes want to run on the CPU.
How does the memory and cpu usage look in htop? (Or, without htop, use `uptime` and `free -h`)
