### ISSUE TITLE
Bot not play music

### ISSUE THREAD

**Issue by ghost** [Splamy/TS3AudioBot#938]
2021-08-27 19:24:56.9637| INFO|Core|Setup.LogHeader [============ TS3AudioBot started =============]
2021-08-27 19:24:56.9999| INFO|Core|Setup.LogHeader [ Date: Friday, 27 August 2021 19:24:56
2021-08-27 19:24:57.0849| INFO|Core|Setup.LogHeader [ Version: 0.12.2/master/4c6be036
2021-08-27 19:24:57.0849| INFO|Core|Setup.LogHeader [ Build: Release
2021-08-27 19:24:57.0849| INFO|Core|Setup.LogHeader [ Platform: Windows 6.2.9200.0 (64bit)
2021-08-27 19:24:57.0849| INFO|Core|Setup.LogHeader [ Runtime: .NET Framework 3.1.13 ServerGC:True GC:SustainedLowLatency
2021-08-27 19:24:57.0849| INFO|Core|Setup.LogHeader [ Opus: libopus 1.2.1-fixed (x64)
2021-08-27 19:24:57.0849| INFO|Core|Setup.LogHeader [==============================================]
2021-08-27 19:24:57.6035| INFO|Core|WebServer.StartWebServerInternal Starting Webserver on port 58913
2021-08-27 19:24:57.7938| INFO|Core|Bot.Run Bot "default" connecting to "8.140.142.207"
2021-08-27 19:24:58.4030| INFO|Core|Ts3Client.ConnectClient Client connected.
2021-08-27 19:25:02.5465| INFO|Api|WebApi.ProcessApiV1Call ::ffff:1.194.63.115 Requested: /api/bot/use/0/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))
2021-08-27 19:25:02.5465|ERROR|Api|WebServer.StartWebServerInternal System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at TS3AudioBot.Sessions.TokenManager.GetToken(String authId) in C:\projects\ts3audiobot\TS3AudioBot\Sessions\TokenManager.cs:line 91
   at TS3AudioBot.Web.Api.WebApi.Authenticate(HttpRequest request) in C:\projects\ts3audiobot\TS3AudioBot\Web\Api\WebApi.cs:line 339
   at TS3AudioBot.Web.Api.WebApi.ProcessApiV1Call(HttpContext context) in C:\projects\ts3audiobot\TS3AudioBot\Web\Api\WebApi.cs:line 68
   at NLog.Logger.SwallowAsync(Func`1 asyncAction)
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at TS3AudioBot.Sessions.TokenManager.GetToken(String authId) in C:\projects\ts3audiobot\TS3AudioBot\Sessions\TokenManager.cs:line 91
   at TS3AudioBot.Web.Api.WebApi.Authenticate(HttpRequest request) in C:\projects\ts3audiobot\TS3AudioBot\Web\Api\WebApi.cs:line 339
   at TS3AudioBot.Web.Api.WebApi.ProcessApiV1Call(HttpContext context) in C:\projects\ts3audiobot\TS3AudioBot\Web\Api\WebApi.cs:line 68
   at NLog.Logger.SwallowAsync(Func`1 asyncAction)
2021-08-27 19:25:02.6114| INFO|Api|WebApi.ProcessApiV1Call ::ffff:1.194.63.115 Requested: /api/bot/use/0/(/list/show/Music/0/20)
2021-08-27 19:25:03.2444| INFO|Api|WebApi.ProcessApiV1Call ::ffff:1.194.63.115 Requested: /api/bot/use/0/(/json/merge/(/volume/100)/(/volume))
2021-08-27 19:25:04.4083| INFO|Api|WebApi.ProcessApiV1Call ::ffff:1.194.63.115 Requested: /api/bot/use/0/(/settings/get)
2021-08-27 19:25:05.0318| INFO|Api|WebApi.ProcessApiV1Call ::ffff:1.194.63.115 Requested: /api/bot/use/0/(/json/merge/(/server/tree)/(/whisper/list))
2021-08-27 19:25:05.5367| INFO|Api|WebApi.ProcessApiV1Call ::ffff:1.194.63.115 Requested: /api/bot/use/0/(/settings/get)
2021-08-27 19:25:06.4482| INFO|Api|WebApi.ProcessApiV1Call ::ffff:1.194.63.115 Requested: /api/bot/use/0/(/list/list)
2021-08-27 19:25:07.4342| INFO|Api|WebApi.ProcessApiV1Call ::ffff:1.194.63.115 Requested: /api/bot/use/0/(/list/play/Music)
2021-08-27 19:25:07.4897|ERROR|Api|FfmpegProducer.StartFfmpegProcessInternal Ffmpeg could not be found (系统找不到指定的文件。)
System.ComponentModel.Win32Exception (2): 系统找不到指定的文件。
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at TS3AudioBot.Audio.FfmpegProducer.StartFfmpegProcessInternal(FfmpegInstance instance, String arguments) in C:\projects\ts3audiobot\TS3AudioBot\Audio\FfmpegProducer.cs:line 282
2021-08-27 19:25:07.7230| WARN|Api|Util.UnwrapToLog permissions_client_insufficient: the command failed to execute: insufficient client permissions (missing permission:b_client_modify_own_description)
2021-08-27 19:25:07.7718| WARN|Api|Util.UnwrapToLog custom_error: the command failed to execute: Avatar upload failed: permission_invalid_size: the command failed to execute: invalid size
2021-08-27 19:25:07.8204| INFO|Api|WebApi.ProcessApiV1Call ::ffff:1.194.63.115 Requested: /api/bot/use/0/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))
2021-08-27 19:25:07.8753| INFO|Api|WebApi.ProcessApiV1Call ::ffff:1.194.63.115 Requested: /api/bot/use/0/(/data/song/cover/get)
2021-08-27 19:25:08.3763| INFO|Api|WebApi.ProcessApiV1Call ::ffff:1.194.63.115 Requested: /api/bot/use/0/(/json/merge/(/volume/75)/(/volume))
2021-08-27 19:25:09.8846| INFO|Api|WebApi.ProcessApiV1Call ::ffff:1.194.63.115 Requested: /api/bot/use/0/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))
2021-08-27 19:25:11.8764| INFO|Api|WebApi.ProcessApiV1Call ::ffff:1.194.63.115 Requested: /api/bot/use/0/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))
2021-08-27 19:25:13.8771| INFO|Api|WebApi.ProcessApiV1Call ::ffff:1.194.63.115 Requested: /api/bot/use/0/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))
2021-08-27 19:25:14.0555| INFO|Api|WebApi.ProcessApiV1Call ::ffff:1.194.63.115 Requested: /api/bot/use/0/(/settings/get)
2021-08-27 19:25:14.4113| INFO|Api|WebApi.ProcessApiV1Call ::ffff:1.194.63.115 Requested: /api/bot/use/0/(/list/list)
2021-08-27 19:25:16.6328| INFO|Api|WebApi.ProcessApiV1Call ::ffff:1.194.63.115 Requested: /api/bot/use/0/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))
2021-08-27 19:25:18.6325| INFO|Api|WebApi.ProcessApiV1Call ::ffff:1.194.63.115 Requested: /api/bot/use/0/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))
2021-08-27 19:25:20.6308| INFO|Api|WebApi.ProcessApiV1Call ::ffff:1.194.63.115 Requested: /api/bot/use/0/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))
2021-08-27 19:25:22.6257| INFO|Api|WebApi.ProcessApiV1Call ::ffff:1.194.63.115 Requested: /api/bot/use/0/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))
2021-08-27 19:25:24.6316| INFO|Api|WebApi.ProcessApiV1Call ::ffff:1.194.63.115 Requested: /api/bot/use/0/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))
2021-08-27 19:25:26.6241| INFO|Api|WebApi.ProcessApiV1Call ::ffff:1.194.63.115 Requested: /api/bot/use/0/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))
2021-08-27 19:25:28.6335| INFO|Api|WebApi.ProcessApiV1Call ::ffff:1.194.63.115 Requested: /api/bot/use/0/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))
2021-08-27 19:25:30.6225| INFO|Api|WebApi.ProcessApiV1Call ::ffff:1.194.63.115 Requested: /api/bot/use/0/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))
2021-08-27 19:25:32.6349| INFO|Api|WebApi.ProcessApiV1Call ::ffff:1.194.63.115 Requested: /api/bot/use/0/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))
2021-08-27 19:25:34.6279| INFO|Api|WebApi.ProcessApiV1Call ::ffff:1.194.63.115 Requested: /api/bot/use/0/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))**Describe the problem**
A clear and concise description of what the problem is.

**To Reproduce**
Steps to reproduce the behavior

**System Information**
- **Platform**: (Ubuntu 16.04, Debian 8, Arch, etc)  
  
- **Mono version**: (`mono -V`)  
  
- **Which commit did you download**: (or on prebuilt: `mono TS3AudioBot.exe -V`)  
  
(If all fields in the TS3AudioBot log header are correctly filled you can
alternatively just post the header here.)

**Additional Logs, Exceptions, etc**
When applicable try to add relevant log excerpts here.

```
Put logs or code in triple backticks like here to properly format it.
```

**Comment by Flakebi** [comment]
The important error message from this log is `Ffmpeg could not be found`. You need to install ffmpeg or copy it into the ts3audiobot folder like described in the readme.
