### ISSUE TITLE
Critical program failure

### ISSUE THREAD

**Issue by KomischeLuna** [Splamy/TS3AudioBot#942]
```
2021-10-08 00:54:59.2624|FATAL|2|Core.UnhandledExceptionHandler Critical program failure!
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at TS3AudioBot.Config.ConfTimeExtensions.GetValueAsTime(ConfigArray`1 conf, Int32 index) in C:\projects\ts3audiobot\TS3AudioBot\Config\ConfigStructs.cs:line 353
   at TS3AudioBot.Ts3Client.TryReconnect(ReconnectType type) in C:\projects\ts3audiobot\TS3AudioBot\Ts3Client.cs:line 602
   at TS3AudioBot.Ts3Client.TsFullClient_OnDisconnected(Object sender, DisconnectEventArgs e) in C:\projects\ts3audiobot\TS3AudioBot\Ts3Client.cs:line 559
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

Version: 0.12.2
Branch: master
CommitHash: 4c6be03646d78cdbfe007ecc697596256ec23617

**Comment by Splamy** [comment]
You have an invalid reconnect time value in your config
