### ISSUE TITLE
Scheduling an Event in own Plugin

### ISSUE THREAD

**Issue by TrickShotMLG02** [Splamy/TS3AudioBot#945]
I am trying to create a plugin, which changes the name of the bot after a new song has started.
It doesn't  work at all. I have tried it with event scheduling but got the following error:

```
22:55:43.7040|ERROR|0| Current call is not scheduled correctly. Sched: S1, Own: 0. Stack:    at TSLib.Scheduler.DedicatedTaskScheduler.VerifyOwnThread()
   at TSLib.Full.TsFullClient.SendCommandBase(WaitBlock wb, TsCommand com)
   at TSLib.Full.TsFullClient.Send[T](TsCommand com)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at TSLib.Full.TsFullClient.Send[T](TsCommand com)
   at TSLib.TsBaseFunctions.SendVoid(TsCommand com)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at TSLib.TsBaseFunctions.SendVoid(TsCommand com)
   at TSLib.TsBaseFunctions.SendMessage(String message, TextMessageTargetMode target, UInt64 id)
   at TSLib.TsBaseFunctions.SendChannelMessage(String message)
   at BotRenamer.changeNameToDesc(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
````

Any Help?

**Comment by Splamy** [comment]
Hey sorry for the late response, the TS3AB is on a bit of a hiatus right now.
To your problem:
To reduce race conditions and multithreading problems, I build a kind of a actor system, requiring each bot running on a separate thread and requiring all modyfing actions to be also called from that same thread.
That said, it seems like you tried using a `System.Threading.Timer` to schedule your action. Instead inject the `TSLib.Scheduler.DedicatedTaskScheduler` into your plugin and use the `CreateTimer` method to create a timer which will aleays be executed in the bot thread. (As a nice bonus you don't need to worry about cleaning up this timer when a bot gets shut down, since it will be destroyed together with the bot)
That aside if you are in are in a situation where you don't know in which (bot)context or thread your code will be executed, you can use the `Invoke`/`InvokeAsync` methods on the `DedicatedTaskScheduler` to run a method in the context of that bot.
And if you didn't know there's also the `PlayManager` class with a `AfterResourceStarted` event which you can subscribe to instead of using timers. You can check out this wiki article here which has a nice example: https://github.com/Splamy/TS3AudioBot/wiki/Plugins#command-plugins

**Comment by TrickShotMLG02** [comment]
Thank you for your detailed explanation.
Which Value do I have to set ` new DedicatedTaskScheduler( "right here");`

I already tried to subscribe to the AfterResourceChanged Event, but I always get errors
![image](https://user-images.githubusercontent.com/43967908/141640548-23a3fa22-663d-4a94-9298-3dbd8ff3e7b7.png)

**Comment by TrickShotMLG02** [comment]
```csharp
using System;
using TSLib.Scheduler;
using TS3AudioBot.Audio;
using TS3AudioBot.Plugins;
using TSLib.Full;

public class BotRenamer : IBotPlugin /* or ICorePlugin */
{
	private PlayManager playManager;
	private TsFullClient tsClient;

	private string defaultName = "";

	TSLib.Scheduler.DedicatedTaskScheduler dedicatedTaskScheduler;

	public BotRenamer(PlayManager playManager, TsFullClient tsClient)
	{
		this.playManager = playManager;
		this.tsClient = tsClient;
		dedicatedTaskScheduler = new DedicatedTaskScheduler(new TSLib.Helper.Id(5));
	}

	public void Initialize()
	{
		dedicatedTaskScheduler.CreateTimer(changeNameToDesc, new TimeSpan(0,0,1), true);
	}

	public void changeNameToDesc()
	{
		tsClient.SendChannelMessage("test");
	}

	public void Dispose()
	{
	}
}
```



What is wrong with the code?
I get the following error:

<details>

```
13:00:54.4467|ERROR|0| Current call is not scheduled correctly. Sched: 0, Own: 5. Stack:    at TSLib.Scheduler.DedicatedTaskScheduler.VerifyOwnThread()
   at TSLib.Scheduler.DedicatedTaskScheduler.CreateTimer(Action method, TimeSpan interval, Boolean active)
   at BotRenamer.Initialize()
   at TS3AudioBot.Plugins.Plugin.StartInternal(Bot bot)
   at TS3AudioBot.Plugins.Plugin.Start(Bot bot)
   at TS3AudioBot.Plugins.PluginManager.StartPlugin(String identifier, Bot bot)
   at TS3AudioBot.MainCommands.CommandPluginLoad(PluginManager pluginManager, String identifier, Bot bot)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.ExecuteFunction(Object[] parameters)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.ExecuteFunction(Object[] parameters)
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at TS3AudioBot.CommandSystem.BotCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at TS3AudioBot.CommandSystem.BotCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at TS3AudioBot.CommandSystem.Commands.RootCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at TS3AudioBot.CommandSystem.Commands.RootCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments)
   at TS3AudioBot.CommandSystem.CommandManager.Execute(ExecutionInformation info, String command)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at TS3AudioBot.CommandSystem.CommandManager.Execute(ExecutionInformation info, String command)
   at TS3AudioBot.Bot.<>c__DisplayClass42_0.<<CallScript>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at TS3AudioBot.Bot.<>c__DisplayClass42_0.<CallScript>b__0()
   at TS3AudioBot.Bot.TryCatchCommand(ExecutionInformation info, Boolean answer, Func`1 action)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at TS3AudioBot.Bot.TryCatchCommand(ExecutionInformation info, Boolean answer, Func`1 action)
   at TS3AudioBot.Bot.CallScript(ExecutionInformation info, String command, Boolean answer, Boolean skipRights)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at TS3AudioBot.Bot.CallScript(ExecutionInformation info, String command, Boolean answer, Boolean skipRights)
   at TS3AudioBot.Bot.OnMessageReceived(Object sender, TextMessage textMessage)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at TS3AudioBot.Bot.OnMessageReceived(Object sender, TextMessage textMessage)
   at TS3AudioBot.Ts3Client.ExtendedTextMessage(Object sender, TextMessage textMessage)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at TS3AudioBot.Ts3Client.ExtendedTextMessage(Object sender, TextMessage textMessage)
   at TSLib.Full.TsFullClient.InvokeEvent(LazyNotification lazyNotification)
   at TSLib.Full.TsFullClient.<>c__DisplayClass37_1.<PacketEvent>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at TSLib.Scheduler.DedicatedTaskScheduler.DoWork()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
13:00:54.4538|ERROR|0| Plugin 'BotRenamer (BotPlugin)' failed to load: Cannot call from an outside thread.
```
</details>

**Comment by Splamy** [comment]
I've updated the example in the wiki.

Also you should not create a new Scheduler but inject the one of the bot like this:
```csharp
public BotRenamer(PlayManager playManager, TsFullClient tsClient, DedicatedTaskScheduler scheduler)
{
	this.playManager = playManager;
	this.tsClient = tsClient;
	dedicatedTaskScheduler = scheduler;
}
```

**Comment by TrickShotMLG02** [comment]
This code doesn't work correctly. The bot is in a stuck state after loading the plugin. The Bot is playing music but isn't replying to any commands. In addition the webinterface has also stopped working until I restart the whole program
