### ISSUE TITLE
My TS3AudioBot has a 4200 packet loss

### ISSUE THREAD

**Issue by andrethnc** [Splamy/TS3AudioBot#962]
, no matter what I do, if the bot is on the ts joint, it already has the packet loss!

![packet loss bot](https://user-images.githubusercontent.com/98653533/151665974-b1ed5bcb-26dc-4ba1-a1a5-d774743dbf76.PNG)

How i can Fix that ?

**Comment by Splamy** [comment]
Hehe, that's not quite a bug. I just havn't implemented packet loss calculation for input packets yet so this is a constant dummy value.
https://github.com/Splamy/TS3AudioBot/blob/develop/TSLib/Full/NetworkStats.cs#L152
If you want to change that you will need to modify that line and recompile the project.

**Comment by andrethnc** [comment]
can you explain to me how it works haha ​​I don't know that much about it yet

**Comment by Splamy** [comment]
Basically unless you really care about that number, there's no need to worry and can just leave it be.  
If you do care about the number, you need to download the project, then change those 4 values here to `0` https://github.com/Splamy/TS3AudioBot/blob/develop/TSLib/Full/NetworkStats.cs#L152-L155  
and compile the project by following the guide on our readme: https://github.com/Splamy/TS3AudioBot#building-manually

**Comment by andrethnc** [comment]
Okay but how i can creat the webinterface


npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ts3abweb@2.0.0-alpha build: `webpack --config webpack.production.config                   .js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the ts3abweb@2.0.0-alpha build script.
npm ERR! This is probably not a problem with npm. There is likely additional log                   ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-30T16_08_16_209Z-debug.log

wtf is this :D

**Comment by andrethnc** [comment]
why can't I set up the webinterface?


0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.13.4
3 info using node@v8.17.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ts3abweb@2.0.0-alpha~prebuild: ts3abweb@2.0.0-alpha
6 info lifecycle ts3abweb@2.0.0-alpha~build: ts3abweb@2.0.0-alpha
7 verbose lifecycle ts3abweb@2.0.0-alpha~build: unsafe-perm in lifecycle true
8 verbose lifecycle ts3abweb@2.0.0-alpha~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/TS3AudioBot/WebInterface/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/root/.dotnet/tools
9 verbose lifecycle ts3abweb@2.0.0-alpha~build: CWD: /root/TS3AudioBot/WebInterface
10 silly lifecycle ts3abweb@2.0.0-alpha~build: Args: [ '-c', 'webpack --config webpack.production.config.js' ]
11 silly lifecycle ts3abweb@2.0.0-alpha~build: Returned: code: 2  signal: null
12 info lifecycle ts3abweb@2.0.0-alpha~build: Failed to exec build script
13 verbose stack Error: ts3abweb@2.0.0-alpha build: `webpack --config webpack.production.config.js`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid ts3abweb@2.0.0-alpha
15 verbose cwd /root/TS3AudioBot/WebInterface
16 verbose Linux 4.9.0-17-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v8.17.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 2
22 error ts3abweb@2.0.0-alpha build: `webpack --config webpack.production.config.js`
22 error Exit status 2
23 error Failed at the ts3abweb@2.0.0-alpha build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

did everything as instructed.!

**Comment by andrethnc** [comment]
is the npm log file
from the error
