### ISSUE TITLE
Unknown command error

### ISSUE THREAD

**Issue by SupperCraft5000** [Splamy/TS3AudioBot#963]
**Describe the bug**
A clear and concise description of what the bug is or what you expected to happen instead.

**To Reproduce**
https://shadowgaming.de/public/2022-01-30%2012-36-12.gif

**Version**
Version: 0.13.0-alpha.38/develop/3eae109c

**Platform**
Debian GNU/Linux 11 (bullseye) (64bit)
.NET (6.0.1) ServerGC:True GC:SustainedLowLatency

**Log**
```
11:30:39.1943| INFO|Api| 127.0.0.1 Requested: /api/bot/use/0/(/data/song/cover/get)
11:30:39.7091| INFO|Api| 127.0.0.1 Requested: /api/bot/use/0/(/json/merge/(/volume/100)/(/volume))
11:30:41.2045| INFO|Api| 127.0.0.1 Requested: /api/bot/use/0/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))
11:30:43.2133| INFO|Api| 127.0.0.1 Requested: /api/bot/use/0/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))
11:30:45.6331| INFO|Api| 127.0.0.1 Requested: /api/bot/use/0/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))
11:30:47.5041| INFO|Api| 127.0.0.1 Requested: /api/bot/list
11:30:48.2773| INFO|Api| 127.0.0.1 Requested: /api/bot/use/0/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))
11:30:48.2773| INFO|Api| 127.0.0.1 Requested: /api/bot/use/0/(/json/merge/(/server/tree)/(/whisper/list))
11:30:48.2785|ERROR|Api| Unknown command error
11:30:48.3003| INFO|Api| 127.0.0.1 Requested: /api/bot/use/0/(/data/song/cover/get)
11:30:48.8031| INFO|Api| 127.0.0.1 Requested: /api/bot/use/0/(/json/merge/(/volume/100)/(/volume))
11:30:49.7913| INFO|Api| 127.0.0.1 Requested: /api/bot/list
11:30:50.8555| INFO|Api| 127.0.0.1 Requested: /api/bot/use/0/(/json/merge/(/server/tree)/(/whisper/list))
11:30:50.8555| INFO|Api| 127.0.0.1 Requested: /api/bot/use/0/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))
11:30:50.8555|ERROR|Api| Unknown command error
11:30:50.8776| INFO|Api| 127.0.0.1 Requested: /api/bot/use/0/(/data/song/cover/get)
11:30:51.3862| INFO|Api| 127.0.0.1 Requested: /api/bot/use/0/(/json/merge/(/volume/100)/(/volume))
11:30:51.7781| INFO|Api| 127.0.0.1 Requested: /api/bot/list
11:31:16.1795| INFO|Api| 127.0.0.1 Requested: /api/bot/use/0/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))
11:31:16.1795| INFO|Api| 127.0.0.1 Requested: /api/bot/use/0/(/json/merge/(/server/tree)/(/whisper/list))
11:31:16.1795|ERROR|Api| Unknown command error
11:31:16.2048| INFO|Api| 127.0.0.1 Requested: /api/bot/use/0/(/data/song/cover/get)
11:31:16.6808| INFO|Api| 127.0.0.1 Requested: /api/bot/list
11:31:16.7263| INFO|Api| 127.0.0.1 Requested: /api/bot/use/0/(/json/merge/(/volume/100)/(/volume))
11:33:44.0147| INFO|2| User SupperCraft5000 requested: !bot diagnose
11:36:32.2646| INFO|Api| 127.0.0.1 Requested: /api/bot/list
11:36:37.8892| INFO|Api| 127.0.0.1 Requested: /api/bot/use/0/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))
11:36:37.9048| INFO|Api| 127.0.0.1 Requested: /api/bot/use/0/(/json/merge/(/server/tree)/(/whisper/list))
11:36:37.9048|ERROR|Api| Unknown command error
11:36:37.9143| INFO|Api| 127.0.0.1 Requested: /api/bot/use/0/(/data/song/cover/get)
11:36:38.4199| INFO|Api| 127.0.0.1 Requested: /api/bot/use/0/(/json/merge/(/volume/100)/(/volume))
11:36:39.9253| INFO|Api| 127.0.0.1 Requested: /api/bot/use/0/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))
11:36:40.3159| INFO|Api| 127.0.0.1 Requested: /api/bot/list
11:36:41.8280| INFO|Api| 127.0.0.1 Requested: /api/bot/use/1/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))
11:36:41.8280| INFO|Api| 127.0.0.1 Requested: /api/bot/use/1/(/json/merge/(/server/tree)/(/whisper/list))
11:36:41.8280|ERROR|Api| Unknown command error
11:36:41.8506| INFO|Api| 127.0.0.1 Requested: /api/bot/use/1/(/data/song/cover/get)
11:36:42.3691| INFO|Api| 127.0.0.1 Requested: /api/bot/use/1/(/json/merge/(/volume/40)/(/volume))
11:36:44.6491| INFO|Api| 127.0.0.1 Requested: /api/bot/use/1/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))
11:36:44.6909| INFO|Api| 127.0.0.1 Requested: /api/bot/list
11:36:46.0420| INFO|Api| 127.0.0.1 Requested: /api/bot/use/2/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))
11:36:46.0420| INFO|Api| 127.0.0.1 Requested: /api/bot/use/2/(/json/merge/(/server/tree)/(/whisper/list))
11:36:46.0420|ERROR|Api| Unknown command error
```

**Comment by Splamy** [comment]
Can you show the same except from the logfile? There should be a stacktrace in there

**Comment by SupperCraft5000** [comment]
```
2022-01-30 11:36:46.0420|ERROR|Api|WebApi.ReturnError Unknown command error
System.NotSupportedException: The type 'TSLib.ChannelGroupId' is not a supported dictionary key using converter of type 'TSLib.ChannelGroupId+Converter'. The unsupported member type is located on type 'TSLib.Full.Book.ChannelGroup'. Path: $.ChannelGroups.
 ---> System.NotSupportedException: The type 'TSLib.ChannelGroupId' is not a supported dictionary key using converter of type 'TSLib.ChannelGroupId+Converter'.
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_DictionaryKeyTypeNotSupported(Type keyType, JsonConverter converter)
   at System.Text.Json.Serialization.JsonConverter`1.WriteAsPropertyName(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.WriteAsPropertyNameCore(Utf8JsonWriter writer, T value, JsonSerializerOptions options, Boolean isWritingExtensionDataProperty)
   at System.Text.Json.Serialization.Converters.DictionaryOfTKeyTValueConverter`3.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryWrite(Utf8JsonWriter writer, TDictionary dictionary, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWriteAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.ArrayConverter`2.OnWriteResume(Utf8JsonWriter writer, TElement[] array, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(WriteStack& state, NotSupportedException ex)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteStringUsingSerializer[TValue](TValue& value, JsonTypeInfo jsonTypeInfo)
   at TS3AudioBot.Web.Api.JsonValue.Serialize() in C:\projects\ts3audiobot\TS3AudioBot\Web\Api\JsonValue.cs:line 57
   at TS3AudioBot.Web.Api.WebApi.ProcessApiV1Call(HttpContext context) in C:\projects\ts3audiobot\TS3AudioBot\Web\Api\WebApi.cs:line 142
```

**Comment by Splamy** [comment]
Thanks, I can reproduce it.
That's indeed a regression.

**Comment by Splamy** [comment]
Fixed version is up and built on nightly

**Comment by SupperCraft5000** [comment]
Now it works perfectly 

[============ TS3AudioBot started =============]
[ Date: Sunday, 30 January 2022 21:08:00
[ Version: 0.13.0-alpha.39/develop/588b5d09
[ Build: Release
[ Platform: Debian GNU/Linux 11 (bullseye) (64bit)
[ Runtime: .NET (6.0.1) ServerGC:True GC:SustainedLowLatency
[ Opus: libopus 1.3.1 (x64)
 [==============================================]

![image](https://user-images.githubusercontent.com/17689259/151718046-7d9f2eae-1126-4f68-8633-5dc2868f814a.png)
