### ISSUE TITLE
Command Error

### ISSUE THREAD

**Issue by SupperCraft5000** [Splamy/TS3AudioBot#965]
**Describe the bug**
When i try to play a url for example "https://streams.ilovemusic.de/iloveradio1.mp3" the error shows up but the bot plays it fine

**To Reproduce**
Playing the url "https://streams.ilovemusic.de/iloveradio1.mp3" directly or in a playlist

**Version**
Version: 0.13.0-alpha.39/develop/588b5d09

**Platform**
Platform: Debian GNU/Linux 11 (bullseye) (64bit)
Runtime: .NET (6.0.1) ServerGC:True GC:SustainedLowLatency
Opus: libopus 1.3.1 (x64)

**Log**
```
2022-01-30 21:24:16.7117| INFO|Api|WebApi.ProcessApiV1Call ::ffff: Requested: /api/bot/use/0/(/list/play/ILoveRadio)
2022-01-30 21:24:17.6448| WARN|Api|Bot.TryCatchCommand Command Error (Command 'CommandGetChannel' missing execution context 'ClientCall')
TS3AudioBot.CommandSystem.MissingContextCommandException: Command 'CommandGetChannel' missing execution context 'ClientCall'
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.FitArguments(ExecutionInformation info, IReadOnlyList`1 arguments) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\FunctionCommand.cs:line 145
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\FunctionCommand.cs:line 205
   at TS3AudioBot.CommandSystem.BotCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\BotCommand.cs:line 119
   at TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\CommandGroup.cs:line 64
   at TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\CommandGroup.cs:line 64
   at TS3AudioBot.CommandSystem.Commands.RootCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\RootCommand.cs:line 42
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.FitArguments(ExecutionInformation info, IReadOnlyList`1 arguments) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\FunctionCommand.cs:line 174
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\FunctionCommand.cs:line 205
   at TS3AudioBot.CommandSystem.BotCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\BotCommand.cs:line 119
   at TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\CommandGroup.cs:line 64
   at TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\CommandGroup.cs:line 64
   at TS3AudioBot.CommandSystem.Commands.RootCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\RootCommand.cs:line 42
   at TS3AudioBot.MainCommands.CommandXecute(ExecutionInformation info, IReadOnlyList`1 arguments) in C:\projects\ts3audiobot\TS3AudioBot\MainCommands.cs:line 1826
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.ExecuteFunction(Object[] parameters) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\FunctionCommand.cs:line 110
   at TS3AudioBot.CommandSystem.Commands.FunctionCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\FunctionCommand.cs:line 205
   at TS3AudioBot.CommandSystem.BotCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\BotCommand.cs:line 119
   at TS3AudioBot.CommandSystem.Commands.CommandGroup.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\CommandGroup.cs:line 64
   at TS3AudioBot.CommandSystem.Commands.RootCommand.Execute(ExecutionInformation info, IReadOnlyList`1 arguments) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\Commands\RootCommand.cs:line 42
   at TS3AudioBot.CommandSystem.CommandManager.Execute(ExecutionInformation info, String command) in C:\projects\ts3audiobot\TS3AudioBot\CommandSystem\CommandManager.cs:line 389
   at TS3AudioBot.Bot.<>c__DisplayClass43_0.<<CallScript>b__0>d.MoveNext() in C:\projects\ts3audiobot\TS3AudioBot\Bot.cs:line 543
--- End of stack trace from previous location ---
   at TS3AudioBot.Bot.TryCatchCommand(ExecutionInformation info, Boolean answer, Func`1 action) in C:\projects\ts3audiobot\TS3AudioBot\Bot.cs:line 570
2022-01-30 21:24:18.4776| WARN|Api|HistoryManager.LogAudioResource AudioLogEntry could not be created!
System.Exception: Track name is empty
2022-01-30 21:24:18.4879| WARN|Api|Util.UnwrapToLog file_invalid_path: the command failed to execute: invalid file path
2022-01-30 21:24:18.5068| INFO|Api|WebApi.ProcessApiV1Call ::ffff: Requested: /api/bot/use/0/(/json/merge/(/bot/info)/(/info/%40-1/5)/(/song)/(/repeat)/(/random)/(/volume))
2022-01-30 21:24:18.5306| INFO|Api|WebApi.ProcessApiV1Call ::ffff: Requested: /api/bot/use/0/(/data/song/cover/get)
```

**Comment by Splamy** [comment]
Thanks, I'll see if I can look into it tomorrow
