### ISSUE TITLE
[Solved] After editing ts3audiobot.toml bot won't start.

### ISSUE THREAD

**Issue by AddictedToNight** [Splamy/TS3AudioBot#967]
Hello there and thanks for your work..

I have been using TS3AudioBot for a while and i haven't come across any problems till now.. It has been a mouth since I last installed TS3AudioBot and that time worked perfectly..

I downloaded last version of it from your site and installed it without problems. After that I run it and still worked perfectly, but after editing ts3audiobot.toml bot keep giving me error (I will post it at the end). After that I deleted ts3audiobot.toml and run it again where that file got auto generated. So I run in again and worked perfectly. Then I shut down bot and run it again, and again it worked perfectly.

So the problem is when i edit ts3audiobot.toml, bot keep crashing with some error.
The purpose for editing ts3audiobot.toml was to write youtube-dl location so that youtube search works.

OS: Linux 
Version: Debian 10  64 bit

Error that pop up when i edit ts3audiobot.toml :

--------------------------------------------------------------------------------------------------------------------------------------------

16:30:12.0965| INFO|Core| [============ TS3AudioBot started =============]
16:30:12.1612| INFO|Core| [ Date: Saturday, 05 February 2022 16:30:12
16:30:12.1882| INFO|Core| [ Version: 0.13.0-alpha.39/develop/588b5d09
16:30:12.1882| INFO|Core| [ Build: Release
16:30:12.1882| INFO|Core| [ Platform: Debian GNU/Linux 10 (buster) (64bit)
16:30:12.1882| INFO|Core| [ Runtime: .NET (6.0.1) ServerGC:True GC:SustainedLowLatency
16:30:12.1882| INFO|Core| [ Opus: libopus 1.3 (x64)
16:30:12.1882| INFO|Core| [==============================================]
16:30:12.2572|ERROR|Core| Could not load core config.
16:30:12.2664|FATAL|Core| Critical program failure!
16:30:12.2664| INFO|Core| TS3AudioBot shutting down.
16:30:12.2664| INFO|Core| Bye
Unhandled exception. System.Exception: Could not create config
   at TS3AudioBot.Core.Run(ParameterData setup) in C:\projects\ts3audiobot\TS3AudioBot\Core.cs:line 54
   at TS3AudioBot.Setup.StartBot(ParameterData setup) in C:\projects\ts3audiobot\TS3AudioBot\Setup.cs:line 92
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
Aborted

--------------------------------------------------------------------------------------------------------------------------------------------

**Comment by AddictedToNight** [comment]
I made a dumb mistake when typing path in youtube-dl.. I typed like "\Bot\ytdl\youtube-dl" insted of "/Bot/ytdl/youtube-dl", so as i said really dumb mistake.

But keep this post if someone else also makes the same mistake as i did.
